src/pages/settings/localization/components/CustomLabels.tsx

This fixes the bug with a dropdown on the custom labels settings page.
After selecting a word from a dropdown and removing it from the list, the word was removed from the dropdown, this fix fixes this behavior.

Fixes for custom labels dropdown

---

src/common/guards/guards/enterprise-plan.ts
src/common/guards/guards/pro-plan.ts

For self-hosted, plan is empty string. This fixes handling with features that are only available for pro & enterprise users.

Fixes for self-hosted feature accessing

---

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx

This switches to markdown editor for the templates and reminders.

Templates and reminders: Switch to markdown editor

---

src/components/DataTable.tsx

This defaults stale time of DataTables to 5 seconds.

Set default stale time of DataTable to 5s

---

src/pages/authentication/Login.tsx

This fallbacks to default index of 0, in case of undefined company.

Fixes for login

---

src/components/forms/DebouncedCombobox.tsx

This fixes issue with blank comboboxes if initial load doesn't include default value.

Implement `with` support for comboboxes

---

src/pages/recurring-invoices/common/components/InvoiceDetails.tsx

Fixes for setting `next_send_date` on the recurring invoice.

Set `next_send_date` instead of `date`

---

src/pages/recurring-invoices/common/components/InvoiceDetails.tsx

Changing this from `date` to `next_send_date`
One point to note is using native date javascript functions are adjusting the props to the client timezone.. this is wrong, we need to show the date as returned from the API.
I'm am simplying slicing the string if it exists, but this is something we'll want to be careful of elsewhere in the application.

Fixes for recurring invoice start date

---

src/pages/invoices/common/hooks/useDownloadPdf.ts

This will indicate something is happening in background once we start the PDF download process.

Implement download indicator for the PDF

---

src/components/DataTable.tsx

This drops "With selected" label next to datatable actions.

Drop `With selected`

---

src/pages/settings/tax-settings/components/Selector.tsx

This makes three taxes selector same as Flutter version.

Improve tax rate settings clarity

---

src/components/clients/ClientSelector.tsx
src/components/forms/DebouncedCombobox.tsx
src/components/products/ProductSelector.tsx

Changes:
- We pull default of 500 products. 
- Products are sorted a-z by product key.
- Clients are sorted  a-z by display name. 
(ref. 363)

Improving client & product selectors

---

src/components/cards/Element.tsx

This fixes "typos" by parsing HTML from the translation strings (ref. 368-394).

Allow parsing HTML from the string

---

src/components/CopyToClipboard.tsx

Fixes for showing blank copy button.

Don't show copy button unless `value` is present

---

src/components/cards/Card.tsx
src/components/cards/NonClickableElement.tsx
src/pages/dashboard/components/Activity.tsx
src/pages/dashboard/components/Chart.tsx
src/pages/dashboard/components/PastDueInvoices.tsx
src/pages/dashboard/components/RecentPayments.tsx
src/pages/dashboard/components/UpcomingInvoices.tsx
src/pages/dashboard/hooks/useGenerateActivityElement.tsx

As per task requirements (RU-298), following had to be implemented.
Skipped:
- Card titlebars should use primary color: This is totally off when it comes to rest of the app. Putting accent color on the card makes every other card look incoherent.
- Sub cards need to be grayish color: I think we should keep tables headers accent color. Not change them to gray, because previously mentioned task isn't implemented. Gray on white doesn't create enough contrast for such important element.
Missing:

Improve dashboard cards styles

---

src/components/products/ProductSelector.tsx

This changes the limiting param from `limit` to`per_page` for `ProductSelector` component.

Product selector limiting 

---

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx

@beganovich I've been looking for a solution to disable the MDEditor component from the @uiw/react-md-editor npm package, but I haven't found one. Here's a link to the source where I found it's not yet possible for this component: https://github.com/jrm2k6/react-markdown-editor/issues/56. Please let me know if I'm wrong.
@turbo124 Regarding this situation that I don't have permission to disable this component, I decided not to show this component if the user is not allowed to do so. Please let me know if you agree with this kind of solution if Ben confirms that disabling is not possible.
Here is the screenshot of how it looks without body template:

[Feature] Disable email template

---

src/pages/payments/create/Create.tsx

This shows validation errors on the payment creation page.

Add validation errors to payments create page

---

src/pages/settings/bank-accounts/index/BankAccounts.tsx

@turbo124 gave me a feedback that the base URL is not okay for purpose of this feature and that should look like: 
https://invoicing.co/yodlee/onboard/mb4mvHNH1l6Hv3afamgoHmq3qj0EeZwgowVPAiOfez6gTgS3IKriH5JVteMnAGNt
So, I just changed the redirection URL.

Changed redirection URL for connect accounts

---

src/pages/settings/gateways/index/Gateways.tsx

Here is screenshot of just added edit payement gateway functionality to more actions:
@beganovich  @turbo124 You can see in the screenshot that we disagree with the wording in the more-actions dropdown menu. My recommendation is to keep `edit_company_gateway` keyword as is and change the other two for archive and delete to 'Archive Gateway' and 'Delete Gateway', as it is obvious that we are on the payment gateway page. Also, as an example, on the `new_gateway` button we have 'New Gateway' but not 'New Payment Gateway'. Let me know your thoughts.

[Feature] Payment gateway edit on more actions

---

src/components/forms/InputField.tsx
src/pages/settings/gateways/create/hooks/useResolveInputField.tsx

Here is an implemented solution for hiding sensitive data on payment gateway cards and the ability to display them if the user wants when the field type is password!
The solution also applies to all password type fields such as the login/registration form!
@beganovich  I've been trying to find if the DebounceInput component contains a property to add some icons to the field, but I haven't found anything in the documentation and other resources. So I think this component does not contain that and implemented this solution. Some MUI TextField components contain properties like end adornment that we can use to implement this functionality, but we're not using MUI so this isn't available.
@turbo124 This workaround is implemented on all input fields on the Credential tab (the other tabs do not …

[Feature] Hide sensitive data

---

src/pages/settings/tax-rates/TaxRates.tsx
src/pages/settings/tax-rates/common/hooks/useTaxRateColumns.tsx

Here is the screenshot of reafactored table and columns for tax rates:
@turbo124 @beganovich Also, I noticed that this table is not consistent with other tables and through testing I didn't notice any difference or specific case why we don't use the same table as for other features, so I refactored it. If there is no reason why we used a custom table, there are two new keywords to add, `delete_tax_rate` and `restore_tax_rate`. One small thing about keywords, as you can see in the screenshot `edit_tax_rate` the keyword has a value of `Edit tax rate` so I recommend that you change all the words to uppercase as well as the other tax rate related keywords.
One more thing about the UI for tax rates. On the edit page we have archive and delete functionality, if we have those functionalities in …

[Cleanup] Tax rate formatting

---

src/pages/purchase-orders/common/hooks.tsx
src/pages/purchase-orders/index/PurchaseOrders.tsx

Here is the screenshot of implemented solution for custom Purchase Order filters:
@turbo124 I set `purchase_order_status` as a placeholder for this dropdown. So we're missing that in the translation files. If you agree with this keyword, just add it.

[Feature] Purchase Order Filters

---

src/pages/transactions/common/hooks/useTransactionFilters.tsx
src/pages/transactions/index/Transactions.tsx

Here is the screenshot of implemented solution for custom filters of Bank Transactions:
@turbo124 I set `transaction_status` as a placeholder on the filter dropdown. If you agree with it, just add it to the translation files.

[Feature] Transaction Filters

---

src/components/DataTable.tsx

Here is the screenshot of resolved bug with payment sorting:
@turbo124 We also had a bug with the perPage parameter. We sent 50 through the endpoint but only got 10 in the result (the default value). So this PR also includes a fix for this also.

[Bug Fix] Payments sorting

---

src/pages/settings/user/components/Notifications.tsx
src/pages/settings/users/edit/components/Notifications.tsx

Here is the screenshot where we have added missing options for user details:
@turbo124 As you can notice on the second option we don't have a proper label, there we used the `notification_invoice_sent` keyword, to fix this label bug I replaced it with `invoice_sent`, but this one contains the `:count` parameter. Also, this one parameter has been replaced with '', but now our label is `invoice sent` instead of `Invoice sent`. If you agree with this type of translation implementation, just update the `invoice_sent` keyword.
Here is the screenshot with updated translation keyword:

[Feature] User details notification options

---

src/pages/invoices/index/Invoices.tsx
src/pages/recurring-invoices/index/RecurringInvoices.tsx

@turbo124 The custom placeholder filters have been changed to `'status'` for Invoices and Recurring invoices and there are only two places where we missed it.

[Bug fix] Custom filter placeholders

---

src/components/Alert.tsx
src/pages/settings/company/documents/components/Upload.tsx

Here are two screenshots of the document tab when the user does not have permission to upload them:
@turbo124 The uploading area is disabled when the user plan is different from `Enterprise` and this includes only `HOSTED` users. Apart from these two screenshots, this warning message will be placed on all routes where we have this kind of upload. The upgrade plan link is set to `user.company_user.ninja_portal_url`. I used `upgrade_to_upload_images` translation keyword (Upgrade to the enterprise plan to upload images). IMO it might be better to change the images keywords to documents since we can actually upload any type of file, but let me know your thoughts.

[Feature] Disabling documents

---

src/common/interfaces/generic-selector-props.ts
src/common/interfaces/transactions.ts
src/pages/transactions/common/hooks/useHandleChange.tsx
src/pages/transactions/common/hooks/useResolveCurrencySeparator.tsx
src/pages/transactions/common/queries.ts
src/pages/transactions/components/TransactionForm.tsx
src/pages/transactions/components/TransactionMatchDetails.tsx
src/pages/transactions/create/Create.tsx
src/pages/transactions/edit/Edit.tsx

@turbo124 We only had a small bug with setting the default value for the currency separators when creating the transaction, so the amount field actually works like this. To manage this field, we use the `DecimalNumberInput` input component and set the currency separators from the currently selected `currency` in the drop-down menu in the field below. When we change the currency, the separators in the amount field will change automatically. The implementation is the same as for invoices.
@beganovich Also, I saw a chance for a good refactoring and renaming of some things. I hope you are okay with this type of refactoring. Now the code is easier to maintain and more readable.

[Bugfix/Cleanup] Transaction amount

---

src/pages/purchase-orders/common/hooks.tsx
src/pages/purchase-orders/create/Create.tsx
src/pages/purchase-orders/edit/Edit.tsx
src/pages/purchase-orders/edit/components/Actions.tsx
src/pages/purchase-orders/edit/components/Details.tsx
src/pages/purchase-orders/edit/components/Footer.tsx
src/pages/purchase-orders/index/PurchaseOrders.tsx

Here is the screenshot of implemented solution for cloning purchase orders:
@beganovich @turbo124 Actually, this action was implemented earlier (atom and logic were created) and not implemented in all places where it is needed. In addition to the implementation of this solution, I noticed some minor bugs and solved them. In Flutter, the purchase order table has several more clone options, for invoice, quote, credit, recurring invoice. This PR probably shouldn't be about adding those cloning options, but if you specifically want them, I can include them here. This task may possibly include other cloning options: https://invoiceninja.atlassian.net/browse/RU-478. Let me know your thoughts.

[Feature] Clone to purchase order

---

src/pages/invoices/common/components/ProductsTable.tsx

Here is a screenshot of the updated UI for the product table when creating a purchase order:

[Bugfix] Purchase order line items text

---

src/components/Modal.tsx
src/pages/settings/account-management/component/DangerZone.tsx

Here is a screenshot of the danger zone when we only have one company created on the account:
Here is a screenshot of the danger zone when we have multiple companies created on the account:
@turbo124 Just one thing to mention as my suggestion. We already have the same help text on the modal after clicking one of those actions, it might be better to avoid one place to put the help text. IMO, it's good to have right below the action buttons or just on the modal. The text messages on modals are also adjusted. Here are screenshots of the modal:

[Cleanup] Danger zone CTA

---

src/pages/quotes/common/components/QuoteStatus.tsx

@turbo124 @beganovich Me and David were talking on Slack today about the `Sent` and `Expired` status code and we found a solution that the -1 status code is correct for the `Expired` Quote status.

[Bugfix] Quote error status badge

---

src/App.tsx

@beganovich @turbo124 This PR only slightly changes the modal displaying logic. Currently in production, we show the modal by default, but if the user has verified their email, we hide it. On this PR we just reversed the logic to avoid the current behavior to avoid unnecessary rendering of this modal.

[Bugfix] Confirm email modal showing

---

src/pages/settings/account-management/component/Overview.tsx

@turbo124 The logic is reversed for the Activate Company toggle button, if the company property `is_disabled` == false it will turn the switch on, but if `is_disabled` == true it will turn it off.

[Bugfix] Company activity toggle button

---

src/common/helpers.ts
src/pages/credits/create/Create.tsx
src/pages/invoices/create/Create.tsx
src/pages/purchase-orders/create/Create.tsx
src/pages/quotes/create/Create.tsx
src/pages/recurring-expenses/create/Create.tsx
src/pages/recurring-invoices/create/Create.tsx

These fixes create pages (after cloning) of resources going undefined due React 18 strict mode.

Fixes for client dismissing

---

src/pages/invoices/edit/components/Actions.tsx
src/pages/invoices/pdf/Pdf.tsx
src/pages/invoices/pdf/components/Actions.tsx

Here is the screenshot of implemented view delivery action for invoice:
@turbo124 @beganovich The action is performed as easily as possible. For me the best way to do this was something like creating an entity from the client overview page, with search parameters, so in this case the URL would look like `http://localhost:3000/#/invoices/M7e5yXYe2v/pdf?delivery_note=true`. Everything after that is handled in code. I've included two keywords in the dropdown menu for this action: `view_delivery_note` and `pdf`. So the action would be like this `View Delivery Note (PDF)`, because it's also in PDF as a regular `view_pdf` action. I hope you agree with me. I can not find the `view_delivery_note` keyword in the translation files so please just add it.
The same action we have from the table as …

[Feature] View delivery note action

---

src/pages/expenses/create/Create.tsx
src/pages/purchase-orders/create/Create.tsx
src/pages/recurring-expenses/create/Create.tsx
src/pages/vendors/Vendor.tsx
src/pages/vendors/show/pages/Expenses.tsx
src/pages/vendors/show/pages/PurchaseOrders.tsx
src/pages/vendors/show/pages/RecurringExpenses.tsx

Here are screenshots of implemented solution for missing tabs on the Vendor overview page:

[Feature] Vendor overview page - missing tabs

---

src/common/queries/statics.ts

@turbo124 As I can see, `X-NINJA-TOKEN` is stored in local storage after login to the app. When the user logs out it will be removed. So I used it as a condition to enable the `/api/v1/static query`. If we have that query in local storage, we will enable this query, if we don't have it, it will be disabled.

[Cleanup] Statics query enabling 

---

src/pages/clients/index.ts
src/pages/clients/show/pages/Tasks.tsx
src/pages/tasks/create/Create.tsx

Here is the screenshot of implemented solution for task table on the client overview page:
@turbo124 A `status` filter is also implemented here, I thought if we can offer why not add to this `Task` table. Also, some other tables don't have the status filter implemented on the Client Overview page, but that's a minor change to add. Let me know your thoughts.

[Feature] Task table - client overview page

---

src/components/CompanySwitcher.tsx

Here is the screenshot of how it looks when we do not have any name set for specific company:
@turbo124 You mentioned in the ticket that maybe we can use `company.settings.name`, but I'm not sure that's possible and that's good logic. Here we only have a list of all available companies and that company has no name set now we set `untitled_company`. If I set `company.settings.name` we will get what we have in the settings of the currently selected company, regardless of whether other companies may not have that name. I hope that you agree with me.
Before opening dropdown the logic is to display `untitled_company` if there is no entered name:

[Cleanup] Company name displaying in dropdown

---

src/common/helpers/invoices/invoice-sum.ts
src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
src/pages/invoices/common/hooks/useTotalVariables.ts
tests/unit/helpers/invoice-sum.test.ts

Here is the screenshot of implemented solution for additonal fields in the total section:
@turbo124 I was a bit confused about what this task was about. But I hope I understood correctly what we need to finish here https://invoiceninja.atlassian.net/browse/RU-451. Totals section has been updated with new fields you mentioned in the Jira's ticket. Let me know your thoughts.

[Cleanup] Missing fields in total section

---

src/components/layouts/Default.tsx
src/components/layouts/Settings.tsx

Here are screenshots of the Settings page on different screen sizes:
Lg:
Md:
@turbo124 In my opinion, this is the clearest solution for our case. If we want everything to fit on the md screen we will have to get smaller text and other things and it won't look good. Let me know how this looks for you now.

[Bugfix] Settings responsiveness

---

src/pages/clients/show/pages/RecurringExpenses.tsx

@turbo124 On the Client overview page, in the query for Recurring expense table, the objects Vendor and Client are also included.

[Bugfix] Recurring expense query include (vendor and client)

---

src/pages/settings/users/edit/components/Notifications.tsx

@turbo124 Changed `notification_invoice_sent` keyword to `invoice_sent_notification_label` when creating User.

[Bugfix] Invoice sent keyword when create user

---

src/pages/invoices/edit/hooks/useMarkSent.ts

@turbo124 We had the `notification_invoice_sent` keyword when we marked the invoice as sent, I didn't find a similar keyword for your recommendation on the Jira ticket (:invoice marked sent...). I search everything with the word :invoice, but there is no good keyword for our purpose. But I found `marked_invoice_as_sent` which I believe gives us exactly what we need, message: `Successfully marked invoice as sent`.

[Bugfix] Marking invoice sent success message

---

src/pages/invoices/edit/components/Actions.tsx

@turbo124 @beganovich Only one mistyped translation keyword of `view_delivery_note` to `delivery_note` has been changed here.
I additionally noticed that we don't have the `clone_to_recurring_invoice` keyword in the translation files. This is used for `Quotes` actions. Do we need to add this one or change to something else?

[Cleanup] Translation keywords changing

---

src/components/Tooltip.tsx
src/pages/products/common/hooks.tsx

Here are three screenshots of implemented solution for `Tooltip` and truncated text for `Notes` column on `Products` table:
@beganovich @turbo124 The `Tooltip` will be displayed on truncated text.

[Cleanup] Product notes - adjusting

---

src/pages/recurring-expenses/components/Details.tsx

@turbo124 @beganovich As with `Expenses`, the query from the `ClientSelector` component is cached on the Create/Edit `Recurring Expenses` pages.

[Bugfix] Clients query caching - Recurring expense pages

---

src/common/interfaces/bank-accounts.ts
src/pages/settings/bank-accounts/common/queries.ts
src/pages/settings/bank-accounts/components/Details.tsx
src/pages/settings/bank-accounts/create/Create.tsx
src/pages/settings/bank-accounts/create/hooks/useHandleCreate.ts
src/pages/settings/bank-accounts/edit/Edit.tsx
src/pages/settings/bank-accounts/show/BankAccount.tsx
src/pages/transactions/components/BankAccountSelector.tsx
src/pages/transactions/components/CreateBankAccountModal.tsx
src/pages/transactions/components/TransactionForm.tsx

@turbo124 The bank account selector has been improved and now, after creation via the modal, the newly created bank account will be immediately selected in the selector. 
One important thing to mention. I refactored the code a bit and used `bank_integrations/create` end point for the first time. When we try to create a bank account (POST method `bank_integrations`) we get an error because of the `nickname` property in this object. If I remove it everything works perfectly. So to make everything work I removed this property before saving the new bank account. But is there any way to fix this on the API side and make it work with the `nickname` property, same as for the PUT method?
@beganovich I've included a few more files in this PR, not just the two main files. The reason for this is the …

[Cleanup] Bank account selector

---

src/pages/products/common/components/ProductForm.tsx

Here is the screenshot of changed quantity label to default_quantity for Product pages:

[Cleanup] Products Create/Edit page - Quantity label

---

src/pages/clients/show/components/Contacts.tsx

@turbo124 @beganovich Tbh, the title of this ticket confused me a bit. I hope the point is to change mailto:[emailValue] to copy to the clipboard with email as the value. https://invoiceninja.atlassian.net/browse/RU-524 Let me know what you think.

[Cleanup] Contant mailto link changed to CopyToClipboard

---

src/components/expense-categories/ExpenseCategorySelector.tsx
src/pages/settings/expense-categories/components/CreateExpenseCategoryForm.tsx
src/pages/settings/expense-categories/components/CreateExpenseCategoryModal.tsx

@turbo124 @beganovich The bug that was fixed on this PR was selecting the `Expense category` in the combobox after creating it via modal. Let me know your thoughts.

[Bugfix] Expense category creation stickying

---

src/components/vendors/VendorSelector.tsx
src/pages/invoices/common/components/InvoiceFooter.tsx
src/pages/vendors/components/CreateVendorForm.tsx
src/pages/vendors/components/CreateVendorModal.tsx

@turbo124 @beganovich This PR is related to this Jira ticket https://invoiceninja.atlassian.net/browse/RU-518. So David mentioned here that there are bugs for `Project` and `Vendor` selections throughout the app. I should mention that all bugs related to `Project` selectors like selection after creation or anything else have been fixed in the `Project Creation Modal` PR. For this PR, I fixed `Vendor` selector and modal issues. I've tested every case I know of and it looks good. Let me know your thoughts.

VendorSelector - Invoice Footer and the rest of App

---

src/common/interfaces/company.interface.ts
src/pages/tasks/common/hooks/useStart.ts
src/pages/tasks/create/Create.tsx

@turbo124 As we know we already have `auto_start_tasks` field under `Task settings` but we didn't have that feature. So, I implemented it here. If this setting is on, after creating a task we will call the API to run this task and after that the user will be navigated to the edit page of that created task. With this setting the task will be created without running. Let me know your thoughts.

[Feature] Auto start task

---

src/pages/settings/company/components/Defaults.tsx
src/pages/settings/online-payments/OnlinePayments.tsx

@turbo124 @beganovich As David mentioned in this list https://invoiceninja.atlassian.net/browse/RU-533, we need to move two fields from the `Defaults` page to the `Payment Settings` page. Let me know if there's anything else I need to change.
Here are screenshots of updated UI for those pages:

[Cleanup] Payment Settings - Defaults - Pages - Refactoring

---

src/pages/settings/localization/components/Settings.tsx

@turbo124 @beganovich As David mentioned in the Jira ticket, I had to remove the `decimal_comma` on the localization settings page. That's why I just commented out this part of the code, so that if we decide to bring it back, we can just uncomment it.

[Cleanup] Commented Decimal Comma Option - Localization

---

src/pages/quotes/common/hooks.tsx
src/pages/quotes/common/hooks/useBulkAction.ts
src/pages/settings/company/components/Defaults.tsx

Here is the screenshot of added action to more-actions dropdown menu:
@turbo124 As we discussed in Slack, we already have the option to `use quote terms` in Defaults settings page, but we missed the `Convert To Invoice` Quote functionality for this property. It is now added and works perfectly on my end. Let me know your thoughts.

[Feature] Convert To Inovice - Quote Functionality

---

src/pages/settings/client-portal/ClientPortal.tsx

Here is the screenshot of implemented tabs for Client portal page:

[Cleanup] Client portal - tabs

---

src/pages/settings/email-settings/EmailSettings.tsx

@turbo124 @beganovich Here is the screenshot of UI with removed helper text for `send_time` field:

[Cleanup] Send time helper text

---

src/pages/settings/client-portal/components/Registration.tsx

Here is the screenshot of UI with added `currency` field:
@beganovich @turbo124 Besides just adding this field, I noticed that updating the company field `client_registration_fields` doesn't work. So this PR includes that part as well, I think it works correctly now and the API will get an array with objects that include the `field key` and the `required (boolean)`. Let me know your thoughts.

[Cleanup] Currency registration field and fixing bug on registration card

---

src/pages/settings/localization/components/CustomLabels.tsx

Here is the screenshot of updated UI for Localization page:
@turbo124 @beganovich Now, the left side (keyword for custom field) will be translated instead of just showing keyword on the UI.

[Bugfix] Translating custom label keyword

---

src/pages/settings/bank-accounts/create/Create.tsx
src/pages/settings/invoice-design/components/GeneralSettings.tsx

@beganovich @turbo124 PR includes a bug fix on the invoice design page, just added optional chaining so they don't break the app if we don't have that property. The second part of the PR is to add a restriction to disable the create bank account button. So, if the user has a pro or enterprise plan, he will be able to create a bank account, otherwise the save button will be disabled.

[Bugfix] Create Bank Account - Permission handling - Invoice Design Optional Chaining

---

src/pages/invoices/common/components/InvoiceStatus.tsx
src/pages/invoices/common/hooks/useInvoiceFilters.ts

Here is the screenshot with added overdue status badge added to invoice entity:
@turbo124 If you look at the screenshot, you can notice that even if I selected the `overdue` status, it included one invoice for me that has a date less than the current date. The conditiion looks like this:
`if (props.entity.due_date && new Date(props.entity.due_date) < new Date())`
Please let know if I missed anything in this condition, maybe I have to take a look into date value?

[Cleanup] Overdue invoice status badge

---

src/common/interfaces/company.interface.ts
src/pages/settings/email-settings/EmailSettings.tsx

Here is the screenshot of UI after implemented field for handling `show_email_footer` email settings property:
@beganovich @turbo124 Let me know your thoughts.

[Feature] show_email_footer email settings property

---

src/pages/settings/company/components/Defaults.tsx

Here is the screenshot of UI with added field for handling `mark_paid_payment_email` property:
@beganovich @turbo124 Let me know your thoughts.

[Feature] mark_paid_payment_email company settings property

---

src/pages/settings/generated-numbers/clients/Clients.tsx
src/pages/settings/generated-numbers/common/components/LinkToVariables.tsx
src/pages/settings/generated-numbers/credits/Credits.tsx
src/pages/settings/generated-numbers/expenses/Expenses.tsx
src/pages/settings/generated-numbers/invoices/Invoices.tsx
src/pages/settings/generated-numbers/payments/Payments.tsx
src/pages/settings/generated-numbers/projects/Projects.tsx
src/pages/settings/generated-numbers/purchase-orders/PurchaseOrders.tsx
src/pages/settings/generated-numbers/quotes/Quotes.tsx
src/pages/settings/generated-numbers/recurring-expenses/RecurringExpenses.tsx
src/pages/settings/generated-numbers/recurring-invoices/RecurringInvoices.tsx
src/pages/settings/generated-numbers/tasks/Tasks.tsx
src/pages/settings/generated-numbers/vendors/Vendors.tsx

Here's a screenshot of the current UI for the Generated Numbers tabs:
@turbo124 The plain text on the screenshot has been replaced with `click_to_variables` translation keyword. If you agree with me, please just add it to translation files.
@beganovich Just to mention, we had one unnecessary card component nested on all the cards. IMO it made the bottom of each card look a little weird. So, I removed them and set Dividers. IMO, it looks better now.
Let me your thoughts.

[Cleanup] Link To GitHub - Variables

---

src/pages/recurring-expenses/common/components/RecurringExpenseStatus.tsx
src/pages/recurring-expenses/common/hooks.tsx

Here is the screenshot of UI when `completed` status for recurring expense has been added:
@beganovich @turbo124 So, when we have `remaining_cycles === 0` this status badge will be shown. Let me know your thoughts.

[Bugfix] Remaining Cycles - Completed Recurring Expense Status

---

src/pages/projects/Project.tsx
src/pages/projects/create/Create.tsx

@beganovich @turbo124 PR include query invalidation for project endpoints after creation and editing. We didn't have it before and that's the reason why we didn't have updated selectors after creating/updating the projects. Let me know your thoughts.

[Bugfix] Project query invalidation

---

src/components/clients/ClientSelector.tsx
src/components/expense-categories/ExpenseCategorySelector.tsx
src/components/products/ProductSelector.tsx
src/components/projects/ProjectSelector.tsx
src/components/users/UserSelector.tsx
src/components/vendors/VendorSelector.tsx

Here is the screenshot of updated UI for project pages when error message is correctly mapped:
@turbo124 @beganovich Actually, we have correctly added the error messages to the components, but only some custom selector components do not have error message prop mapped. I just fixed it and it works as it should. In one of the previous tickets, I made sure that all components add error message props. Let me know your thoughts.

[Cleanup] Project pages 422 errors / Selector components error message

---

src/common/interfaces/company.interface.ts
src/pages/settings/email-settings/EmailSettings.tsx

Here is the screenshot of implemented solution for email providers (Postmark and Mailgun):
@beganovich @turbo124 I just noticed one thing that we don't have `gmail` as a translated keyword, but `microsoft` was in the translation files. Should we have `gmail` and `microsoft` as translated keywords or can we put it as `plain text`. 
Also, David mentioned in the ticket that this should only be possible for Pro/Enterprise plans. The entire page (Email Settings) is available for saving only if the user has one of those plans. That covers that part.

[Feature] Postmark / Mailgun - Email providers

---

src/pages/settings/invoice-design/components/GeneralSettings.tsx

Here is the screenshot with added helper text for `hide_empty_columns_on_pdf` company settings property:
@beganovich @turbo124 When property has set to true text should be Hide but when it is set to false, text should be Show. Let me know your thoughts.

[Cleanup] Empty columns - Helper text

---

src/pages/invoices/email/components/Mailer.tsx

@beganovich @turbo124 PR includes changes to the condition of disabling the `subject` property on the emailing invoice page. So far we've disabled it if the user only has `freePlan()`, but we haven't covered that this field should be enabled for `SELF-HOSTED` users. So I just added that part of the condition. Let me know your thoughts.

[Bugfix] Subject property - Disabling - Emailing Invoice

---

src/pages/transactions/components/ListBox.tsx

@beganovich @turbo124 The PR fixes a bug showing `display_name` instead of the classic `Client name`. The `display_name` property will display the name of some of the contacts assigned to the `Client` if there is no entered classic `name` property. Let me know your thoughts.

[Bugifix] Invoice client name - Transaction match slider

---

src/pages/invoices/common/components/InvoiceStatus.tsx

@beganovich @turbo124 We had a bug with a `overdue` status. Me and David talked on Slack about the conditions for those statuses, so I adjusted the others according to David's instructions to match the API's conditions. It should look good now. Let me know your thoughts.

[Bugfix] Invoice statuses

---

src/pages/invoices/common/components/ProductsTable.tsx
src/pages/invoices/common/hooks/useResolveInputField.tsx

@beganovich @turbo124 David noticed an bug in misplacing line items when cloning an invoice from a table. The reason for this is because we don't have an `_id` property for each line item in the table response. On the edit page in the response we have this property for each line item and we haven't had any bugs there. Looking deep into the code, the line item index is calculated using the `_id` property with this line of code:
`const index = resource.line_items.findIndex((item) => item._id === _id);`
Then I realized that we actually get the same result if we just pass the `lineItemIndex` from the line item table map. I've tested all the cases I know about this and I haven't seen any bad impact just this and also the code is formatted a bit (unnecessary code removed). Ben, if you know any …

[Bugfix] Cloning Invoice - Line items

---

src/components/vendors/VendorSelector.tsx

This fixes the `VendorSelector` stale state if quickly going from edit to create the page.

Fixes for vendor selector stale state

---

src/common/helpers/number.ts
src/pages/invoices/common/hooks/useFormatMoney.ts

@beganovich @turbo124 We had a bug with incorrect formatting of money values ​​when cloning entities (invoice, quote, etc.). The actual bug was missing UI rerendering when we tried to clone entities with the same `client_id/vendor_id` twice in a row. On the second attempt, we will not have the proper UI displayed (with formatted values). The `atom` and `resolveClient` parts of the logic we actually use on creation pages (especially atom) have the biggest impact to resolve it like this. This change will resolve the bug in all entities where we had this bug. Let me know your thoughts.

[Bugfix] Formatting money on cloning

---

src/pages/invoices/create/Create.tsx
src/pages/tasks/common/hooks/useInvoiceTask.ts

This fixes the bug of dismissing the value of `invoice` when creating it from the tasks.

Fixes bug with invoicing tasks

---

src/pages/products/common/hooks.tsx

@beganovich @turbo124 We had a bug with displaying bulk actions when switching to the `Documents/Product Fields` tabs. It's resolved now and looks good from my end. Here's a screenshot:

[Bugfix] Displaying bulk actions | Product Edit Page

---

src/components/layouts/Default.tsx

@beganovich @turbo124 PR includes changing the label in the upgrade CTA in the top navigation bar to translate the `purchase_white_label` keyword. Here's a screenshot:
We do not have this keyword in the translation files, so if it is okay from your end also, please just add it. Let me know your thoughts.

[Cleanup] Upgrade CTA Label - Self Hosted

---

src/pages/credits/common/hooks.tsx
src/pages/invoices/edit/components/Actions.tsx
src/pages/quotes/common/hooks.tsx
src/pages/recurring-invoices/common/hooks.tsx

@beganovich @turbo124 PR includes settings `due_date` property to `'' value` on any cloning invoice. Let me know your thoughts.

[Cleanup] Setting due_date to empty value | Cloning Invoice

---

src/common/queries/transaction-rules.ts
src/pages/transactions/components/Details.tsx
src/pages/transactions/components/TransactionMatchDetails.tsx
src/pages/transactions/index/Transactions.tsx

@beganovich @turbo124 PR includes a bug fix for opening and closing transaction matching sliders. Additionally, I did pre-selection the vendor or expense category if the transaction has the `matched` status. Let me know your thoughts.

[CleanUp] Transaction slider bugfix && Vendor/Expense category pre-selection

---

src/pages/clients/index/Clients.tsx
src/pages/projects/index/Projects.tsx
src/pages/settings/bank-accounts/components/transaction-rules/TransactionRules.tsx
src/pages/settings/bank-accounts/index/BankAccounts.tsx
src/pages/settings/expense-categories/ExpenseCategories.tsx
src/pages/settings/gateways/index/Gateways.tsx
src/pages/settings/integrations/api-tokens/ApiTokens.tsx
src/pages/settings/integrations/api-webhooks/ApiWebhooks.tsx
src/pages/settings/schedules/index/Schedules.tsx
src/pages/settings/subscriptions/index/Subscriptions.tsx
src/pages/settings/task-statuses/TaskStatuses.tsx
src/pages/settings/tax-rates/TaxRates.tsx
src/pages/transactions/components/BankAccountSelector.tsx
src/pages/transactions/index/Transactions.tsx
src/pages/vendors/index/Vendors.tsx

@beganovich @turbo124 We had a bug with bulk route for some entities. The reason for this is that we didn't specify `bulkRoute` before, so after adding `?sort=id|desc` the route was broken. Now that's fixed. Let me know your thoughts.

[Bugfix] Bulk Routes

---

src/common/hooks/permissions/useHasPermission.ts
src/components/layouts/Default.tsx

@beganovich @turbo124 PR includes adding the `view_reports` permission to show/hide `Reports` option in the left bar. I'm not sure we have any other place to use this permission yet, other than the show/hide Reports menu option. Let me know your thoughts.

[Feature] Report permissions

---

src/pages/payments/create/Create.tsx
src/pages/projects/create/Create.tsx
src/pages/projects/edit/Edit.tsx
src/pages/settings/users/create/Create.tsx
src/pages/settings/users/edit/components/Details.tsx
src/pages/transactions/components/BankAccountSelector.tsx

@beganovich @turbo124 I checked all the entities, I tried to find as many bugs as possible regarding the error messages that must be displayed to the user. About a month ago I had a very similar task to this and regarding that I didn't find too many bugs regarding error messages. These are the bugs found:
- I think we had one page with an unnecessary ValidationAlert, this alert just duplicated the messages we already had in each field. I hope you agree with removing this part. Screenshot:
- Added required (*) property on Project pages for fields where it is needed
- We didn't have error messages implemented on the User creation page, it is now implemented. We have a validation message for the number of users that user can create. We don't have a specific field for this, so I moved it to …

[Cleanup] Error messages - All entites

---

src/pages/expenses/common/hooks.tsx

@beganovich @turbo124 While working on the columns task, I saw that we have the `column_by` column on Expenses page active and available for use. This is not the case for other entities, that part of the code is commented out on every other entity with the message that we need to resolve the relationship. I just wanted to remove this column from the dropdown list until we resolve the relationship so that it is available to use this column properly. Screenshot:
Of course, let me know if we already have this relationship resolved. Let me know your thoughts.

[Bugfix] created_by column | Expenses

---

src/pages/expenses/edit/Edit.tsx

@beganovich @turbo124 The PR includes just changing title on edit expense page. We had title `Expense` but it should be `Edit Expense`. Let me know your thoughts.

[Bugfix] Title - Edit Expense Page

---

src/components/PasswordConfirmation.tsx

@beganovich @turbo124 PR includes improving the UX when closing the password confirmation modal on the `Edit User` page. Previously, when we close the password confirmation modal, we got this weird UI where we don't have any tab because the user didn't enter the correct password and from this page the user can't open the modal again. Screenshot:
Now, instead of just hiding the modal when the user just closes the password confirmation modal, we navigate the user to the `/settings/users` page where he is available again to open the same `Edit User` page and enter the correct password. IMO, this behavior improves the UX for this case. But, let me know your thoughts.

[Bugfix] UX - Edit User Page - Closing Password Confirmation Modal

---

src/common/interfaces/company.interface.ts
src/pages/settings/task-settings/TaskSettings.tsx
src/pages/tasks/common/components/TaskTable.tsx
src/pages/tasks/common/helpers/calculate-time.ts

@beganovich @turbo124 PR includes adding a `Billable` column to the time logs table and a toggle field to handle the `allow_billable_task_items` property. Screenshots:
I added two keywords that we don't have in the translation files yet to the toggle field, `allow_billable_task_items` and `allow_billable_task_items_help`. So if you agree with me, please just add them to the translation files.

[Feature] Task Time Logs | Allow Billable

---

src/components/layouts/Default.tsx

This disables the "Purchase white label"  or upgrade buttons in the demo.

Disable white label or unlock pro buttons in demo

---

src/components/PasswordConfirmation.tsx

@beganovich @turbo124 The last time when I was working on improving the behavior of the `/settings/users/:id/edit` page when the user closes the `Password Confirmation` modal, I didn't notice that we were using the same component in the rest of the app. So when the user clicks the `X` on any Password Confirmation modal, the user will be navigated to the `/settings/users` page, even though it's a completely different page.
So I fixed that and just added a condition to navigate the user to the `/settings/users` page only if the user closes the modal from the `/settings/users/:id/edit` page. 
Note: Sorry for this little mistake on the last PR.

[Bugfix] Password Confirmation Navigation/Closing

---

src/pages/invoices/common/components/InvoiceTotals.tsx
src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
src/pages/invoices/common/hooks/useTotalVariables.ts
src/pages/settings/invoice-design/common/hooks.tsx

@beganovich @turbo124 PR includes reordering for total variables and invoice design tabs. Screenshots:
Note: The `Total Fields` tab has just been moved from the last place to the second place.

[Bugfix] Total Fields Reordering | Invoice Design Tabs Reordering

---

src/pages/invoices/common/components/ClientSelector.tsx

@beganovich @turbo124 PR includes changing `view_in_portal` link for `Invoice|Recurring Invoice` Edit page. Now, navigation will go to `invoice.invitations.link/recurringInvoice.invitations.link` link. Let me know your thoughts.

[Bugfix] View In Portal Link | Invoice Edit Page

---

src/common/interfaces/product.ts
src/pages/products/common/components/ProductForm.tsx

@beganovich @turbo124 PR includes adding new fields for the `Product` entity (`Max Quantity and Image URL`). I added both fields without any conditions. I hope that is correct approach. Screenshot:

[Feature] New Fields | Product Entity

---

src/pages/products/common/components/ProductForm.tsx

@beganovich @turbo124 PR includes changing labels for two `Product` fields. 
`Product -> Item` and `Notes -> Description` 
Here is the screenshot:

[Cleanup] Product fields | Labels

---

src/pages/credits/pdf/Pdf.tsx
src/pages/invoices/pdf/components/Actions.tsx
src/pages/quotes/pdf/Pdf.tsx

@beganovich @turbo124 PR includes refactoring for navigation bar for `View Pdf` pages. We have a PDF preview page for `Credits, Invoices, Purchase Orders, Quotes and Recurring Invoices entities`. We've implemented a `More Actions` drop-down menu with email and download functionality for `Credits, Invoices and Quotes`. So I refactored it there, but didn't add actions where we probably missed them (`Recurring Invoices and Purchase Orders`). Please let me know if I need to add actions to View Pdf pages where we don't have them. Screenshot:

[Cleanup] View Pdf Pages | Navigation Bar Refactoring

---

src/pages/settings/online-payments/OnlinePayments.tsx

@beganovich @turbo124 PR includes vertical centering of the `Payment Terms` text on the `Payment Settings` page. This bug occurred because we had the text `Configure Payment Terms` in the same box with dropdown menu on the right side. Screenshot with fixed bug:

[Bugfix] Payment Terms Text Centering

---

src/pages/invoices/common/components/ClientSelector.tsx

@beganovich @turbo124 While I was working on the `view_in_portal` action link on the `medium@example.com` account for testing last night, I didn't have a chance to find this bug when we need to check the length of the invitations. But after updating the seeder and working on the e2e tests task, I found that we need to check the contact invitations length so that we don't break the app. Everything is the same, I just added this security condition. A bug occurred in some cases when we selected a client when creating an invoice. Let me know your thoughts.

[Bugfix] View In Portal Link | Checking Invitation Length

---

src/components/forms/DebouncedCombobox.tsx

This implements a fallback to empty records when organizing (fixes for clearing the results).

Fixes for organising results (clearing)

---

src/components/layouts/Default.tsx
src/pages/invoices/common/components/ClientSelector.tsx
src/pages/recurring-invoices/common/hooks.tsx
src/pages/recurring-invoices/create/Create.tsx
src/pages/recurring-invoices/edit/Edit.tsx

@beganovich @turbo124 PR includes adding new save options to the `Recurring Invoice` creation and editing page to avoid two steps for sending and starting invoice. I've tried several solutions and this one makes the most sense for me, and this one is much more customizable than the others.
- We have a solution to put additional actions in the `More Actions` dropdown, but I haven't implemented it because I'm not sure it will be good for UX. I don't think the user will ever open that extra drop down menu to see if there is an extra way to save the invoice.
- Also, I tried the solution from the Flutter app with all separate buttons. But it will create a problem with responsiveness, there will be many more buttons to fit on a small screen. Screenshot:
There is a solution to keep only the …

[Cleanup] Additional Save Options | Recurring Invoice

---

src/common/routes.tsx
src/components/NotFound.tsx

@beganovich @turbo124 PR includes creating a `Not-Found` page for all routes that we don't have in our application, but the user somehow enters them. I tried to make the page as simple and clear as possible without any background images and stuff like that. Here is a screenshot:
`Note`: I used plain text with no translation keywords to show how the UI might end up looking once we get the translation keywords. If you agree with this text concept, just give me suggestions for translation keywords.
Let me know your thoughs.

[Feature] Not Found Page

---

src/pages/purchase-orders/common/queries.ts

@beganovich @turbo124 PR includes changing the translation keyword when Purchase order is marked sent to `marked_purchase_order_as_sent`. Let me know your thoughts.

[Cleanup] Translation Keyword | Marking PO Sent

---

src/components/forms/DebouncedCombobox.tsx
src/components/tax-rates/TaxRateSelector.tsx

This passes `null` if the tax_rate value is 0 (essentially fixes the bug with tax rate valued at 0%).

Tax rate selector improvements

---

tests/e2e/product.spec.ts

@beganovich @turbo124 I wrote the tests for the `Product` entity before David created the entity-specific accounts. We had created the tests using the standard `permissions@example.com` account, but like everyone else, I implemented the scope tests using `products@example.com` on this PR. So this PR only includes just an update for the currently correctly written tests. Let me know your thoughts.

[Cleanup] E2e tests scoping |  Product Entity

---

tests/e2e/expenses.spec.ts

@beganovich @turbo124 The PR includes:
- Improving the `can view expense` test with additional checks
- Creating a expense deletion test
- Creating test for archiving expense
- Creating test for cloning expense
- Creating test for previewing documents tab
- Creating test for uploading documents

[Feature] Additional e2e tests - Expense Entity

---

playwright.config.ts

This provides a safe fallback to 2 retries when e2e testing.

Change default retries for the tests

---

src/components/layouts/Default.tsx

@beganovich @turbo124 PR includes resolving bug for enabling/disabling `Recurring Invoice module`. We just had bad logic caused with wrong brackets position. Now, it is resolved and works perfectly on my end. Let me know your thoughts.

[Bugfix] Recurring Invoice Module

---

tests/e2e/credits.spec.ts

@beganovich @turbo124 The PR includes:
- Improving the `can view credit` test with additional checks
- Creating a credit `deletion` test
- Creating test for `archiving` credit
- Creating test for `cloning` credit
- Creating test for `previewing documents` tab
- Creating test for `uploading documents`

[Feature] Additional e2e tests - Credit Entity

---

src/pages/settings/user/common/hooks/useUserDetailsTabs.tsx

@beganovich @turbo124 PR includes changing `connect` translation keyword to `oauth_mail` keyword. Screenshot:

[Cleanup] Connect Translation Keyword

---

src/common/hooks/entities/useQuickCreateActions.ts

@beganovich @turbo124 PR includes changing `connect_bank` translation keyword to `add_bank_account`. Screenshot:

[Cleanup] connect_bank Translation Keyword Change

---

src/pages/settings/account-management/component/Plan.tsx

@beganovich @turbo124 PR includes changing the text format for the current user's plan. David, you mentioned in the ticket to specify the number of users with text like `1-3 Users`, but I did not find such a result in the `account` object, I only found the `num_users` property. Regarding that, I have implemented this solution and I hope this is satisfying. Screenshot:

[Cleanup] Plan Text Refactoring

---

src/pages/invoices/common/hooks/useHandleProductChange.ts
src/pages/invoices/common/hooks/useResolveInputField.tsx

@beganovich @turbo124 PR includes fixing a bug in `product selection` when a user entered a search term. We didn't have the combobox value updated correctly when the user finally clicked on one of the filtered product. This behavior occurred in the Products/Tasks table for each item. Additionally, I added a clear option to this combo box, we didn't have that and IMO the UX was a bit weird. When we selected a product we had to delete the entire line item to change to something else.
`Note`: David also mentioned in the ticket that an `onKeyDown` option would be nice to have to select product. If you mean product selection by clicking enter, that option is already available. But, if you think of any other option, just let me know.

[Bugfix] Line Items | Product Selection

---

src/pages/credits/email/Email.tsx
src/pages/invoices/email/Email.tsx
src/pages/purchase-orders/email/Email.tsx
src/pages/quotes/email/Email.tsx

@beganovich @turbo124 PR includes changing redirection URL after sending email for `Credit`, `Invoice`, `Purchase Order` and `Quote` entities. So, user will be navigated to the `Client/Vendor` view page. Let me know your thoughts.

[Cleanup] Redirection URL After Emailing

---

src/common/interfaces/schedule.ts
src/pages/clients/common/hooks/useScheduleStatement.tsx
src/pages/clients/statement/Statement.tsx
src/pages/invoices/common/hooks/useScheduleEmailRecord.tsx
src/pages/settings/schedules/common/components/EmailStatement.tsx
src/pages/settings/schedules/common/hooks/useFormatSchedulePayload.tsx
src/pages/settings/schedules/common/hooks/useHandleChange.tsx
src/pages/settings/schedules/create/Create.tsx

@beganovich @turbo124 PR includes adding the functionality of the `show_credits_table` property to the `Client Statement page`, but also to the `Schedule` pages. Screenshots:
`Note`: We don't have the `show_credits_table` keyword in the translation files, so just add it to them.

[Feature] Show Credits Table | Client Statement

---

src/common/interfaces/company.interface.ts
src/pages/expenses/create/Create.tsx

@beganovich @turbo124 Alex reported a bug for the `Mark Paid` field in the support-ninja group, but I noticed that we also have a bug with the `Should be invoiced` and `Add documents to invoice` fields, so the PR includes bug fixes for mismatched settings on `Expense` pages. We missed setting the `Should Invoice`, `Mark Paid` and `Add Documents to Invoice` fields due to changes in the cost settings. This is only important on the `Expense creation page`, on the expense edit page we will display the saved details. Let me know your thoughts.

[Bugfix] Expense Settings | Expense Pages

---

src/common/hooks/useTitle.ts

@beganovich @turbo124 The PR includes a bug fix for the first part of the document title/browser tab title. Now if we have `import.meta.env.VITE_APP_TITLE`, it will be displayed as the first part of the title, if we don't have it but we have `company.settings.name`, the company name will be displayed, otherwise we will display the translated `untitled` keyword as the first part of the title. Let me know your thoughts.

[Bugfix] Document Title

---

src/common/interfaces/product.ts
src/pages/products/common/components/ProductForm.tsx

@beganovich @turbo124 PR includes implementation for new Product's field (`Tax Category`). Screenshot:
We miss just a few translation keywords: `reduced_tax`, `override_tax`, `zero_rated` and `reverse_tax`. Let me know your thoughts.

[Feature] Add Field - Tax Category | Products

---

src/pages/settings/bank-accounts/show/BankAccount.tsx

@beganovich @turbo124 Changed `bank_account_details` translation keyword to `bank_account`. Screenshot:

[Cleanup] bank_account_details translation keyword

---

src/components/forms/SelectField.tsx
src/pages/settings/company/components/Defaults.tsx

@beganovich @turbo124 PR includes implementation of `Expense Payment Type` field under `Defaults`. Screenshot:
We miss `expense_payment_type` translation keyword from the translation files, so if you agree please just add it. Let me know your thoughts.

[Feature] Expense Payment Type Field

---

src/pages/settings/bank-accounts/index/BankAccounts.tsx

@beganovich @turbo124 The PR includes adding a `Refresh` functionality to the main page of bank accounts. It is a `POST` request to the `'/api/v1/bank_integrations/refresh_accounts'` endpoint with an `empty object payload`. Screenshot:
This is only available for `Enterprise` plan on the `Hosted` platform. Let me know your thoughts.

[Feature] Refresh | Bank Accounts

---

src/pages/payments/refund/Refund.tsx

@beganovich @turbo124 The PR includes improving the logic for the `Gateway Refund` option. Now we will first take the `gateway_type_id` from the `Payment` object and using this `gateway.options[gatewayTypeId].refund` logic we will take the right `optionObject` from the `gateway.options` and check the refund value. If the refund value is true, we will display a toggle. Let me know your thoughts.

[Cleanup] Improve Gateway Refund Logic

---

src/pages/clients/show/pages/Credits.tsx
src/pages/clients/show/pages/Invoices.tsx
src/pages/clients/show/pages/Payments.tsx
src/pages/clients/show/pages/Projects.tsx
src/pages/clients/show/pages/Quotes.tsx
src/pages/clients/show/pages/RecurringInvoices.tsx

@beganovich @turbo124 We had a bug of missing client name in some tables on the Client view page. It is fixed and here is the screenshot:

[Bugfix] Missing Client Name | Client View Page

---

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx

@beganovich @turbo124 PR includes adding functionality for `Reminders` under `Templates & Reminders`. Screenshot:
@turbo124 Just to make sure one thing, by default always `Invoice` template should be selected, we do not have any property for storiying last time selected template?

[Feature] Template & Reminders | Reminders Settings

---

src/common/queries/common/headers.ts
src/pages/settings/user/components/Connect.tsx

Sets default headers so we can differentiate in the API which AP type has sent the request

Add default headers

---

src/components/layouts/Default.tsx
src/env.d.ts

There can be scenario's where if .env is not available, whiteLabelLink will return null. hardcoding this here

White label link

---

src/App.tsx
src/components/Banner.tsx
src/components/EmailConfirmationBanner.tsx
src/components/layouts/Default.tsx
src/components/layouts/components/DesktopSidebar.tsx

@beganovich @turbo124 PR includes implementing banner at the top of the page instead of modal we already had. Here is the screenshot:
The CTA `Resend Email` will resend email via API through `/api/v1/user/:id/reconfirm` endpoint. This banner will be displayed only for `HOSTED` users.

[Cleanup] Email Confirmation Banner | Implementation

---

src/components/forms/Combobox.tsx

This fixes empty results set when we delete the input (query).

Fixes for combobox showing nothing on empty value

---

src/pages/settings/account-management/component/Plan.tsx

This hides license management buttons in the demo mode.

Hide licence management for demo

---

src/components/banners/VerifyPhone.tsx

This returns null if we don't have an account (yet) fixing the signup issue.

Fixes for signup crash

---

src/common/interfaces/invoice-item.ts
src/pages/credits/create/Create.tsx
src/pages/credits/edit/Edit.tsx
src/pages/invoices/create/Create.tsx
src/pages/invoices/edit/Edit.tsx
src/pages/quotes/edit/Edit.tsx
src/pages/recurring-invoices/create/Create.tsx
src/pages/recurring-invoices/edit/Edit.tsx

Previously we only allowed `InvoiceItemType.Product` (1) to be part of the products table. This fixes it to support other types except for tasks.
The current filter:
```
InvoiceItemType.Product,
InvoiceItemType.UnpaidFee,
InvoiceItemType.PaidFee,
InvoiceItemType.LateFee,
```

Fixes for filtering line items

---

src/components/clients/ClientSelector.tsx
src/pages/clients/edit/components/AdditionalInfo.tsx
src/pages/clients/edit/components/Contacts.tsx
src/pages/clients/edit/components/Details.tsx
src/pages/invoices/common/components/ClientCreate.tsx

@beganovich @turbo124 While testing query invalidation for comboboxes, I discovered a few bugs in the Client creation modal that I have prioritized to resolve in this PR:
- The combobox for clients had sorting by `display_name|asc`, which caused an issue when there were more than 20 clients. If a newly created client appeared after the first 20 clients based on this sorting, it wouldn't be selected in the combobox after creation. To resolve this, I have decided to use sorting by `created_at|desc`, which seems to be a logical solution. I hope you agree with this change, as it will fix the bug.
- When opening the modal twice in a row, we encountered 2-3 strange bugs related to setting the Client object. As a result, we ended up with a situation where a Client was created without any entered …

[Bugfix] Client Create Modal | Client Combobox

---

src/components/DataTable.tsx

This fixes an issue with the datatable caching mechanism.

Stack both keys for cache invalidation

---

src/common/hooks/emails/useHandleSend.ts
src/pages/invoices/email/components/Mailer.tsx

@beganovich @turbo124 This PR includes the addition of missing validation for Mailing pages. Here is a screenshot of the updated functionality:
@turbo124 Validation will be shown for the `template`, `subject`, and `cc_email` fields, I'm not sure that I see any other fields where we can have scenario of showing validation. Let me know if we have any other scenarios.

[Bugfix] Adding Validation | Emailing Pages

---

src/common/queries/clients.ts
src/common/queries/company-gateways.ts
src/components/DataTable.tsx
src/pages/settings/system-logs/SystemLog.tsx
src/pages/tasks/common/components/CreateTaskModal.tsx
src/pages/transactions/components/TransactionMatchDetails.tsx

@turbo124 @beganovich I went through the entire app to ensure how we `defined` queries and how we `invalidate` them regarding the bug that Shalom reported for Client view page and David noticed in the Transactions. Both of them have been resolved, and additionally, I fixed the queries' definition where we were not doing it correctly. I have extensively tested this, and it appears to me that we do not have any instances of invalidation query bugs.

[Bugfix] Query Invalidation Across the App

---

src/pages/projects/common/hooks.tsx
src/pages/projects/common/hooks/useInvoiceProject.tsx
src/pages/projects/show/Show.tsx

@beganovich @turbo124 I noticed this bug of duplicating actions for the Projects table:
Additionally, I found a bug when we create a Project and then delete the Client that was used for Project creation. When we return to the Project page, the page breaks. Therefore, it has also been fixed here.

[Bugfix] Project Dropdown | Project Client

---

src/pages/clients/edit/components/AdditionalInfo.tsx

This fixes an issue currently where we potentially send incorrect types for client settings.
If no setting is present, we should remove the prop from the settings object completely. 
This PR resolves the issue, unsure if this is the cleanest way to tackle the problem, but it is certainly safer than the current implementation.

Refactor send reminders toggle

---

src/components/DataTable.tsx
src/pages/clients/show/pages/Projects.tsx
src/pages/credits/index/Credits.tsx
src/pages/invoices/create/hooks/useHandleCreate.ts
src/pages/invoices/index/Invoices.tsx
src/pages/projects/common/hooks.tsx
src/pages/projects/common/hooks/useCombineProjectsTasks.ts
src/pages/projects/index/Projects.tsx
src/pages/purchase-orders/index/PurchaseOrders.tsx
src/pages/quotes/index/Quotes.tsx

@beganovich @turbo124 The PR includes implementation for bulk invoicing project functionality. Screenshot:
@turbo124 Additionally, this PR includes improvements for UX as we discussed when saving an invoice while the tasks tab is selected. Now, when a user saves the invoice with `table=tasks` in the URL (for invoicing projects and similar functionalities), the tasks tab will also be selected on the edit page.

[Feature] Bulk Invoice Project

---

src/common/interfaces/company.interface.ts
src/pages/settings/company/components/Defaults.tsx
src/pages/settings/online-payments/OnlinePayments.tsx

@beganovich @turbo124 The PR includes replacing Payment Settings from `Default` page to `Payment Settings` page. Screenshot:

[Cleanup] Payment Settings Replacement

---

src/components/forms/MarkdownEditor.tsx

prevents tinymce from overriding the browser context menu on right click.

Remove tinymce context menu

---

src/components/forms/Combobox.tsx

@beganovich @turbo124 The PR includes slightly decreasing the debounce for the Combobox component from 1000 to 600. If we include the time of the request and this debounce, in my opinion, it looks great. With 1 sec debounce it looks like too much waiting for the response. Let me know your thoughts.

[Bugfix] Combobox Debounce Change

---

src/pages/settings/online-payments/OnlinePayments.tsx

@beganovich @turbo124 The PR includes removing blank option for `Auto Bill Recurring Invoices Dropdown` on Payment Settings page. If we do not have any value returned from the API we will set `off` as default value. Screenshot:

[Bugfix] Auto Bill Recurring Invoices Dropdown Removing Blank Option

---

src/components/clients/ClientSelector.tsx

@beganovich @turbo124 The PR includes resolving a bug when the ID value of the client is passed, but there is no selected client with that ID. This query parameter will bring an additional client, which should be selected. Let me know your thoughts.

[Bugfix] Client Selector Additional Query Parameter

---

src/common/queries/recurring-expense.ts
src/pages/recurring-expenses/common/hooks.tsx

@beganovich @turbo124 The PR includes adding Archive/Restore/Delete actions on Edit Recurring Expense page. Screenshot:
@turbo124 `One note`: For `deleted_recurring_expense` translation key we get the message `Successfully deleted project`. So that is just small bug that we have to fix regarding translation files.

[Cleanup] Recurring Expense Edit Page | Missing Bulk Actions

---

src/pages/tasks/common/hooks.tsx
src/pages/tasks/kanban/components/EditSlider.tsx

@beganovich @turbo124 The PR includes resolving a bug that prevents the `Time Log` modal on Kanban from updating correctly when any of the pickers (Start Date, End Date, Start Time, End Time) are changed. If you switch to the `develop` branch and attempt to change the `End Time` picker, for example, the `Duration` will not be updated. Additionally, if you modify any of the pickers and click "Done" to close the modal, when you reopen it, you will find the old values still present. All of these issues have been resolved in this PR.

[Bugfix] Time Log Modal Time Updating | Kanban

---

src/pages/clients/show/Client.tsx
src/pages/clients/show/hooks/useTabs.ts
src/pages/dashboard/Dashboard.tsx

@beganovich @turbo124 The PR includes handling `Quotes` tables on the `Dashboard` and handling the Quotes tab on the Client overview page. So, if the Quote module is enabled, it will be shown, if not, it will not be shown. Let me know your thoughts.

[Cleanup] Handling Quote Module On Dashboard & Client Overview Page 

---

src/pages/tasks/common/components/TaskDetails.tsx

The task rate will now be populated in two ways:
1. When we're on the project page and click "New task", the project/rate will auto-fill.
2. When we create a new task, after changing the project task rate will auto-fill.

Bring the rate with a project

---

src/common/queries/invoices.ts
src/pages/invoices/common/hooks/useCustomBulkActions.tsx
src/pages/invoices/edit/components/Actions.tsx
src/pages/invoices/index/Invoices.tsx

@beganovich @turbo124 The PR includes implementation of `auto_billing` functionality for Invoices. The `auto_bill` option will be shown if three requirements are passed:
- The `balance` of invoice must be > 0
- The Invoice must be in one of two statuses `Send` | `Partial` (2,3)
- The Invoice's Client must have at least one "gateway_token" in the array of `gateway_tokens`
To display the bulk action in the dropdown, we can have two situations, if no invoices are selected, the option will be shown or if only one of the selected invoices passes those three checks, the action will also be shown in the dropdown.
`Important note`: Only the `invoice_ids` that are eligible for auto-billing will be included in the payload. Others will be excluded, even if they are selected during the bulk action. …

[Feature] Auto Billing Invoices Functionality

---

src/components/Tabs.tsx
src/pages/dashboard/Dashboard.tsx
src/pages/projects/show/Show.tsx
src/pages/settings/account-management/component/EnabledModules.tsx
src/pages/vendors/Vendor.tsx
src/pages/vendors/show/hooks/useTabs.tsx

@beganovich @turbo124 The PR includes implementation `enable_modules` across the app. This affects the `Client show page (tabs)`, `Dashboard page (tables)`, `Project show page for the Tasks table`, and `Vendor show page (tabs)`. If a module is disabled, the corresponding table/tab will not be shown on the mentioned pages. 
I think that this PR cover all pages where we need implementation of enabling modules, but let me know if there are some additional. Since the implementation for enabling modules is already present in the main left sidebar, no additional changes are required there. 

[Cleanup] Applying Enable Modules Across The App Same As We Did For Quotes

---

src/pages/dashboard/components/ExpiredQuotes.tsx
src/pages/dashboard/components/UpcomingQuotes.tsx

@beganovich @turbo124 The PR includes bug fixes for incorrect navigation when a user clicks on the `number` link in the `number column` on the Quotes tables on the Dashboard. Previously, it would navigate to the `invoices edit page` instead of the quotes edit page. Now, this has been corrected, and it navigates to the quotes edit page as intended. Let me know your thoughts.

[Bugfix] Navigation Links For Quotes Tables On Dashboard

---

src/App.tsx
src/components/CompanySwitcher.tsx
src/pages/authentication/Register.tsx
src/pages/settings/company/create/CompanyCreate.tsx

@beganovich @turbo124 The PR includes logic for populating `company_users` once a user signs up. Additionally, the PR includes resolving a bug that prevented the `Company Edit Modal` from showing when a user has just signed up or when a company is just created. Let me know your thoughts.

[Cleanup] Populating Company Object When Signup | Showing Company Setup Wizard

---

src/components/forms/Combobox.tsx

@beganovich @turbo124 As per David's recommendation during Monday's meeting, I created a PR to improve a any part of the app. My choice was to enhance the Combobox component, specifically by improving the UX when the user clicks on an already selected option in the dropdown. 
So, currently in the app, if the user clicks on already selected value in the dropdown, the selection icon on the right side will hide, and the text will look like all the others (unselected), but nothing will happen with the value. As a result, in the dropdown, it looks like the specific value is unselected, but actually, it is not.
I recorded two short videos to show the difference between the old behavior and the new one.
Old:
https://github.com/invoiceninja/ui/assets/51542191/366a34a7-3cd3-46d7-b615-86aeec1848ce …

[Improvement] Combobox Async Component | Weekly Challenge

---

src/pages/settings/account-management/component/Overview.tsx

@beganovich @turbo124 The reason we had a broken app when the user clicked the "activate_company" button on the banner is that we did not have optional chaining in the "set_default_company" logic. So, there was a moment when the "company" object was undefined, and we tried to read "id" and "settings.name" from that undefined value (`company.id` and `company.settings.name`).
The reason you, David, were not able to see the "activate_company" banner locally is that we show the banner only for the `HOSTED` platform. Please let me know if I should remove this constraint and display the banner for both types of platforms.

[Bugfix] Activate Company Link Breaks App

---

src/common/hooks/useAdjustColorDarkness.ts
src/pages/tasks/common/components/TaskStatus.tsx
src/pages/tasks/common/hooks.tsx

@beganovich @turbo124 We encountered a non-covered case where the default color was `#fff`. As a result, the text color adjustment was incorrect, and the text appeared white, making it invisible in this edge case. However, I have fixed the issue, and now it looks good on my end. Let me know your thoughts.

[Bugfix] Hex Color Edge Case | Task Statuses

---

src/pages/recurring-invoices/common/components/InvoiceDetails.tsx
src/pages/recurring-invoices/create/Create.tsx

This prefills the next_send_date of the recurring invoices if it's empty (on create page).

Fixes for recurring invoices next send date

---

src/pages/credits/common/hooks.tsx
src/pages/invoices/common/hooks/useInvoiceColumns.tsx
src/pages/quotes/common/hooks.tsx
src/pages/vendors/common/hooks.tsx

despite the truncate prop, the notes are not truncating as expected for items in the following entities. this is a stop gap until a proper solution can be found that respects the tailwind truncate property.

Truncate text in list views

---

src/common/interfaces/company.interface.ts
src/pages/invoices/common/hooks/useHandleProductChange.ts

@beganovich @turbo124 The PR includes implementing functionality for the `default_quantity` property in company settings. I believe that we have now replicated the behavior of the Flutter app in the React app.
One note regarding the video in the Jira ticket, David. I believe the product you selected in the video had a quantity of `1`, which is why you ended up choosing a quantity of `1`, even though the `default_quantity` was set to `false`.
Of course, we now have the entire functionality implemented, but for that specific reason, I believe that was the case.

[Bugfix] Default Quantity Functionality

---

src/pages/settings/invoice-design/pages/custom-designs/pages/create/Create.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx

@beganovich @turbo124 The PR includes the addition of missing validation for Design Selectors on Custom Designs pages. Screenshot:

[Bugfix] Missing Validation For Design Selectors | Custom Designs

---

src/pages/settings/account-management/component/Integrations.tsx
src/pages/settings/routes.tsx

@beganovich @turbo124 The PR includes the addition of guards and conditions for accessing API Tokens routes. As a result, only SELF-HOSTED users or users with a PRO/ENTERPRISE plan will be able to access these routes. Free plan users will NOT have access to this section of the app. Below is a screenshot of the hidden button to access these routes:

[Cleanup] Adding API Tokens Guards

---

src/components/forms/Combobox.tsx

instead of searching when the result list hits 0, we increment this to 3, so that we preempt the search results, improves user experience when the string partially matching existing records, but the exact record is not shown.

Fixes for combo box logic

---

src/pages/dashboard/components/Chart.tsx

@beganovich @turbo124 The PR includes the resolution of a bug for the YAxis label when dealing with long numbers. I have now implemented a solution that ensures a consistently dynamic width. Screenshot:

[Bugfix] YAxis Labels Width | Chart | Dashboard

---

src/pages/invoices/common/components/ProductsTable.tsx

@beganovich @turbo124 The PR includes a fix for a bug related to automatically creating a line item when a client/vendor is selected. Please share your thoughts on this.

[Bugfix] Preventing Line Items Creation on Client/Vendor Selection

---

src/pages/invoices/common/hooks/usePrintPdf.ts

@beganovich @turbo124 The PR addresses a bug related to printing PDFs in the Firefox browser. The reason for encountering blank PDFs during printing was the inconsistent behavior of `document.body.appendChild` across various browsers. Particularly in the case of `Firefox`, there was a slight delay when appending the `iframe` element into the `body` of the `document`, leading to the issue of blank PDFs. The problem has been resolved by utilizing an asynchronous approach to ensure the proper appending of this element within the document's body. Here is the screenshot:

[Bugfix] Print PDF | Firefox

---

src/pages/invoices/index/Invoices.tsx

@beganovich @turbo124 The PR includes the same bug that David noticed with the Recurring Invoice Slider. When a user attempts to open the slider twice in succession for the same invoice, the slider will appear blank. This PR resolves this issue. Let me know your thoughts.

[Bugfix] Invoice Slider Opening Twice In A Row

---

src/common/hooks/useEntityCustomFields.ts
src/pages/credits/common/components/CreditDetails.tsx
src/pages/credits/common/hooks.tsx
src/pages/quotes/common/components/QuoteDetails.tsx
src/pages/quotes/common/hooks.tsx
src/pages/settings/invoice-design/pages/general-settings/components/CreditDetails.tsx
src/pages/settings/invoice-design/pages/general-settings/components/QuoteDetails.tsx

@beganovich @turbo124 The PR includes bug fixes for `custom_fields` related to the Credit and Quote entities. This encompasses table pages, create/edit pages. Additionally, I identified another bug on the `invoice_design` page under the `general_settings` tab, where incorrect `custom_fields` were also being applied. Let me know your thoughts.

[Bugfix] Quote | Credit Custom Fields

---

src/common/queries/documents.ts
src/common/queries/recurring-expense.ts
src/pages/recurring-expenses/common/hooks.tsx
src/pages/recurring-expenses/common/hooks/useCustomBulkActions.tsx
src/pages/recurring-expenses/index/RecurringExpenses.tsx

@beganovich @turbo124 The PR includes the implementation of custom bulk actions for the `Recurring Expense` entity.
I noticed a small bug in the Flutter app while comparing. When stopping and starting a recurring expense, there is actually a message for a recurring invoice.
Note: We are missing two keywords in the translation files: `started_recurring_expense` and `stopped_recurring_expense`. If you agree with me, please just add them.

[Feature] Custom Bulk Actions Implementation | Recurring Expense

---

src/common/queries/documents.ts
src/pages/expenses/common/hooks/useCustomBulkActions.tsx
src/pages/expenses/index/Expenses.tsx

@beganovich @turbo124 The PR includes the implementation of custom bulk actions for the `Expense` entity. In this case, it only includes a bulk action for downloading documents (I cannot see any additional actions in the Flutter app). Let me know your thoughts.

[Feature] Custom Bulk Actions Implementation | Expenses

---

src/pages/settings/gateways/create/Create.tsx

@beganovich @turbo124 The PR includes adding the missing part of the logic for displaying the `WePay` logo in the quick creation section. Screenshot:

[Bugfix] Missing Wepay Logo

---

src/components/import/UploadImport.tsx

if hints exist in the preimport - these are used to select / match the corresponding fields.

Import CSV hints

---

src/components/forms/Combobox.tsx
src/components/forms/InputField.tsx
src/pages/payments/create/Create.tsx

@beganovich @turbo124 The PR includes a couple of improvements:
- The dropdown of the combobox component closes after selecting a value
- Unable to select the same invoice/credit twice from the dropdown menus on the payment creation page
- Setting the `invoices` and `credits` properties in the Payment object to an empty array after clearing the value from the Client combobox
- Resolving a bug with classes in the Combobox Component (as explained in the comment)

[Cleanup] Payment Creation Page && Combobox Selector Improvements

---

src/pages/recurring-invoices/common/components/IncreasePricesAction.tsx

@beganovich @turbo124 The PR includes changing the type for the `percent` field on the "Increase Prices" action for recurring invoices. This will require the user to enter a numeric value instead of allowing the possibility of a string value. Screenshot:

[Cleanup] Increase Prices Action | Percent Field Changing Type To Number

---

src/pages/settings/gateways/common/components/GatewaysTable.tsx
src/pages/settings/gateways/common/hooks/useGatewayUtilities.ts

@beganovich @turbo124 The PR includes adding logic to cover the edge case of setting the `company_gateway_ids` property to '0' when all gateways are removed from group/client settings. Let me know your thoughts.

[Bugfix] Property Value '0' When All Gateways Are Removed | Group & Client Settings

---

src/pages/invoices/common/hooks/useCustomBulkActions.tsx

@beganovich @turbo124 The PR includes changing the logic for downloading invoice documents and aligning it with the rest of the project. So, now we use the POST route `/api/v1/documents/bulk` with the action: `download` and document IDs in the payload. Let me know your thoughts.

[Cleanup] Correcting Route For Downloading Invoice Documents

---

src/pages/quotes/common/hooks.tsx

@beganovich @turbo124 The PR includes the addition of additional filters for quotes (`upcoming` and `converted`). We already had `expired` added to those filters, so I simply added these two. Screenshot:
@turbo124 We are missing the `upcoming` translation keyword in the files. Please add it there.

[Feature] Additional Custom Filters | Upcoming & Converted | Quotes

---

src/components/DataTable.tsx
src/components/tables/Td.tsx

@beganovich @turbo124 The PR includes an improvement in clickability for rows across all tables. Now, the entire `<td>` related to the Checkbox will be clickable for checking/unchecking the Checkbox. Additionally, sliders will now only open on the first three columns in a row after the Checkbox column. Let me know your thoughts.

[Cleanup] Clickability On Rows | Improvement

---

src/pages/settings/email-settings/EmailSettings.tsx

@beganovich @turbo124 The PR includes adding part of the logic that we missed for catching the 422 error when uploading a certificate. Screenshot:
@turbo124 As we discussed on Slack, we would like to align the settings pages with the rest of the app by displaying validation messages under the fields, as we have done on other pages. For this purpose and to make adjustments to the settings pages, I will create a specific ticket for it. I hope that you will agree.

[Bugfix] Upload Certificate Validation Message

---

src/components/cards/Element.tsx
src/pages/clients/show/components/Address.tsx
src/pages/clients/show/components/Standing.tsx

@beganovich @turbo124 The PR includes the implementation of private/public notes on the Client overview page. Public notes are placed on the `Address` card, while private notes are placed on the `Standing` card, just like we have in the Flutter app. Screenshot:
@turbo124 I would like to explain a few things here. I noticed on the Flutter app that we have truncated text for notes on this page, which appears as a single line without wrapping and displays '...' at the end if it is too long. To display the text as it is entered, preserving all the formatting, we need to use the `dangerouslySetInnerHTML` property in the HTML. However, when using this property and wanting to display the text as a single line with '...' at the end if it's too long, this property does not add the '...'. I wasn't …

[Cleanup] Implementation Of Notes On Client Overview Page && Little Refactoring Of Standing Component

---

src/pages/settings/tax-settings/components/Selector.tsx

@beganovich @turbo124 The PR includes fixing the type for the properties tax_rate1, tax_rate2, and tax_rate3 across all settings levels that we send to the payload. We sent them as strings, but they need to be numbers. Let me know your thoughts.

[Bugfix] Default Tax Rates Parsing To Number

---

src/components/forms/MarkdownEditor.tsx

This fixes an issue of TinyMCE header overlapping due to the wrong z-index (vendors edit page).

Fixes for TinyMCE z-index

---

src/components/forms/Combobox.tsx

@beganovich @turbo124 The PR includes fixing the bug related to opening/focusing the comboboxes after closing the modal. It's important to pinpoint the source of this bug. In reality, the `Dialog` component from `@headlessui/react` focuses on the first focusable element in the `DOM` when we `close` it in any manner. The presence of an `onFocus` event on the `HeadlessCombobox.Input` component (`onFocus={() => setIsOpen(true)}`) caused the comboboxes to open when the modal was closed. David noticed this bug in the `Kanban` with `Project` combobox, but upon my examination of the rest of the application, I observed it occurring wherever the first focusable element is a combobox. I extensively researched the Dialog component, but I couldn't find any solutions provided for this bug. I might be …

[Bugfix] Opening Comboboxes After Closing Modal

---

src/components/forms/Combobox.tsx

@beganovich @turbo124 The PR addresses the bug related to query invalidation for comboboxes across the entire app. In the old component, `Debounced Combobox`, we had a query key specified to the `pathname of the URL`. This was the method for invalidating queries throughout the application. However, when we changed it in the newly created comboboxes, query invalidation broke. I've simply added the `queryKey` definition under the new combobox component, which should resolve the bug throughout the app. Let me know your thoughts.

[Bugfix] Comobox Query Invalidation Across Whole App

---

src/common/hooks/clients/useClientResolver.ts
src/components/forms/Combobox.tsx
src/pages/credits/edit/Edit.tsx
src/pages/invoices/edit/Edit.tsx
src/pages/quotes/edit/Edit.tsx
src/pages/recurring-invoices/edit/Edit.tsx

This fixes and reduces double query for vendors (and all other comboboxes) on the expenses edit page.

Fixes for vendors double query

---

src/pages/invoices/common/components/EmailInvoiceAction.tsx
src/pages/invoices/common/components/SendEmailBulkAction.tsx
src/pages/invoices/common/hooks/useCustomBulkActions.tsx
src/pages/invoices/edit/components/Actions.tsx
src/pages/invoices/edit/components/CommonActions.tsx

@beganovich @turbo124 The PR includes the implementation of a modal to inform the user that the client does not have any email contacts to email an invoice. The modal also provides an additional CTA to navigate to the client's edit page and add some contacts. Screenshot:

[Cleanup] Client Does Not Have Contact Email | Email Invoice Action

---

src/components/forms/Combobox.tsx
src/pages/clients/edit/components/AdditionalInfo.tsx
src/pages/payments/create/Create.tsx

@beganovich @turbo124 The PR includes finalizing the query key invalidation/caching for Combobox components and all adjustments related to it. The additional bug that I found, which actually caused the screen to go blank, is on the Client creation page. We had a case where the `client?.settings` object did not exist, and we were trying to read currency_id from it, which resulted in the page going blank. Let me know your thoughts.

[Bugfix] Combobox Invalidation/Caching && Additional Optional Chaining On Client Page

---

src/pages/clients/common/hooks/useActions.tsx

@beganovich @turbo124 The `new_invoice` action was not navigating to the `invoice` creation page at all. Therefore, this PR addresses and fixes this issue. Let me know your thoughts.

[Bugfix] New Invoice Navigation | Client Action

---

src/components/clients/ClientSelector.tsx
src/pages/invoices/common/components/ClientSelector.tsx

@beganovich @turbo124 The PR includes bug fixes for not showing the Client selector when a user has appropriate permissions. Additionally, I noticed that if a user does not have the "create_client" permission, we still show the "new_client" action in the combo list, which allows us to open the client slider for client creation. I believe there is no need to show this action without having the necessary permission. So, if a user has the "create_client" permissions, the "new_client" action will be shown, otherwise, it will not. Let me know your thoughts.

[Bugfix] Client Selector Not Showing For Some Permissions

---

src/common/helpers/request.ts
src/components/DataTable.tsx
src/pages/settings/company/edit/CompanyEdit.tsx
src/pages/settings/users/edit/components/Actions.tsx

@beganovich @turbo124 The PR includes fixes for displaying a 401 error message in the toaster. To ensure that the entire logic is correct, here it is:
- If a user receives a 429 OR 403 error, they will be logged out of the app.
- If a user receives a 404 error, they will be navigated to the "not_found" page.
- If a user receives a 412 error, it will be displayed as a "wrong password" message in the toaster. It is catched throughout the entire app.
- If a user receives a 422 error, it will be displayed as a validation message under the field.
- If a user receives any error between 400 (including 400) and 500, the message will be displayed in the toaster.
- If a user receives a 500 error, we will display a "Something went wrong" message in the toaster.

[Bugfix] Ensuring 400 erros are shown in toaster

---

src/common/hooks/useRefetch.tsx
src/components/DataTable.tsx

This improves cache revalidation by providing the `refetchByUrl` function which allows us to pass the endpoint for te cache entry. This should improve query invalidation after bulk actions.

Improve cache validation after bulk actions (datatable)

---

src/pages/settings/company/create/CompanyCreate.tsx
src/pages/settings/company/edit/CompanyEdit.tsx

@beganovich @turbo124 The PR fixes this bug:
Additionally, we did not display the message in the toaster regarding the number of companies that the user is able to create. The reason for that is because it is a 422 error, and we needed to show it in the toaster instead of displaying it under the field. Now, it is shown to the user in the toaster. Screenshot:

[Bugfix] Overflow Issue On The Company Edit Modal && Showing Missing Toaster Error Message

---

src/common/generic/DesignSelector.tsx
src/common/queries/designs.ts
src/common/queries/expense-categories.ts
src/components/payment-types/PaymentTypeSelector.tsx
src/components/tax-rates/TaxRateSelector.tsx
src/pages/expenses/common/hooks/useCustomBulkActions.tsx
src/pages/settings/localization/components/Settings.tsx

@turbo124 @beganovich The PR includes changes that order lists for `expense_categories`, `designs`, `tax_rates`, `payment_types`, and `timezones`. These changes involve ordering them in `ascending` order by the `name` of the entity `(A -> Z)`. This adjustment applies to comboboxes or selectors. Let me know your thoughts.

[Cleanup] Sorting Lists In Alphabetical Order

---

src/pages/tasks/kanban/Kanban.tsx

@beganovich @turbo124 The PR includes fixing a bug to display only tasks with the 'Active' status in the Kanban. Let me know your thoughts.

[Bugfix] Displaying Only 'Active' Task Statuses In The Kanban

---

src/pages/tasks/common/components/AddTasksOnInvoiceAction.tsx

@beganovich @turbo124 The PR addresses the bug with the "Add Tasks To Invoice Bulk Action." The bug was related to setting selected resources as an empty string at the wrong time, which is why we did not have any new task line items on the invoice page. Let me know your thoughts.

[Bugfix] Add Tasks To Invoice Bulk Action | Tasks

---

src/pages/clients/edit/Edit.tsx
src/pages/clients/edit/components/AdditionalInfo.tsx

@beganovich @turbo124 The PR involves removing the tabs for Client and Contact fields from the Edit Client page. Screenshot:
Additionally, I have addressed the spacing issue between cards on this page. The screenshot of issue:

[Cleanup] Removing Client And Contact Fields Tabs From Edit Client Page && Quick UI Fix With Spacing

---

src/pages/invoices/common/hooks/useResolveInputField.tsx

@beganovich this PR helps to set the correct number of tax rates that may be configured on the product itself.
If a user later disables tax rates, we continue to set the tax rates which is unexpected. this PR checks when adding a product the configured number of tax rates, and cleans the product prior to adding.
I *think* this was the best place to add this?

Set appropriate taxes depending on how many are configured

---

src/common/queries/payments.ts

@beganovich @turbo124 The PR includes changing the query key for the single Payment query from `['/api/v1/payment_terms', params.id]` to `['/api/v1/payments', params.id]`. We had correct invalidation, but instead of using 'payments' in the query key, we had 'payment_terms', which directly affected the update of the edit payment page. So, try changing something on the already created Payment, go back to the payments table, and then return to the Payment edit page. The changes will not be reflected there. Let me know your thoughts.

[Bugfix] Single Payment Query Key Definition

---

src/pages/products/routes.tsx
tests/e2e/product.spec.ts

@beganovich @turbo124 The PR includes a quick UI fix caused by defining the route for the "product_fields" tab and additional improvements to tests for Products. These changes cover the case and ensure that `documents` and the `product_fields` tabs are correctly rendered. Screenshot of bug:

[Bugfix] Product Fields Tab UI Fix && Additional Test To Check Correct Rendering

---

src/pages/recurring-invoices/common/queries.ts

@beganovich @turbo124 The PR includes changing the translation keywords for bulk actions on Recurring Invoices, instead of having translation keywords for regular Invoices. Let me know your thoughts.

[Bugfix] Bulk Actions Toaster Messages | Recurring Invoices

---

src/pages/invoices/common/hooks/useHandleProductChange.ts

@beganovich @turbo124 The PR involves changing the logic for clearing the Product selector on the Products table. Instead of just removing the value for the Product, we will reset all values in the line item to the blank line item. Let me know your thoughts.

[Cleanup] Product Selector | Clear Value Functionality

---

src/common/queries/task-statuses.ts
src/components/task-statuses/TaskStatusSelector.tsx
src/pages/tasks/create/Create.tsx

@beganovich @turbo124 The PR includes the implementation of the "new_task_status" action on the Task Status selector and creation modal for creating this entity. Screenshot:

[Cleanup] Task Status Action Implementation Along With Modal

---

src/pages/products/common/hooks/useInvoiceProducts.ts

@beganovich @turbo124 The PR addresses a bug related to incorrect mapping of the invoice object when created from the products. Instead of matching the `product_key` to the `product_key` property, we inadvertently set the ID of the product to the product_key property. This issue has now been fixed. Let me know your thoughts.

[Bugfix] New Invoice | Products

---

src/components/datatables/Actions.tsx
src/components/forms/InputField.tsx
src/pages/credits/common/components/CreditDetails.tsx
src/pages/invoices/common/components/InvoiceDetails.tsx
src/pages/invoices/common/hooks/useHandleProductChange.ts
src/pages/purchase-orders/edit/components/Details.tsx
src/pages/quotes/common/components/QuoteDetails.tsx

This PR allows us to use an override on the Inputfield in order to combine both onBlur and onChange.
There are some inputs which require immediate reactivity (partial) and search fields.
This PR addresses this edge case.

Allow both onChange and onBlur selectively

---

src/pages/payments/common/hooks/usePaymentColumns.tsx

@beganovich @turbo124 The PR includes displaying all invoices linked to the payment instead of just the first one in the invoice number payment column. Screenshot:

[Cleanup] Showing All Invoice In Invoice Number Payment Column

---

src/pages/purchase-orders/edit/components/VendorSelector.tsx

@beganovich @turbo124 The PR includes fixes for the Vendor Selector when cloning the Purchase Order. The root cause of the bug originates from the purchase_order object response. In this object, the `vendor_id` property is NOT populated, preventing us from fetching the correct Vendor. I have adjusted the logic to retrieve the vendor ID from the Vendor's object under the Purchase Order if the vendor_id property is not populated. Otherwise, we will use the vendor_id property. Here's a quick demo of the bug:
https://github.com/invoiceninja/ui/assets/51542191/857ad95a-4c64-468c-9e7b-b5682089fbc8

[Bugfix] Purchase Order Cloning

---

src/App.tsx
src/components/CompanySwitcher.tsx
src/components/PublicRoute.tsx
src/pages/Index.tsx
src/pages/settings/company/create/CompanyCreate.tsx

@beganovich @turbo124 The PR addresses two bugs. The first one occurs when the user switches the company or creates a new one, and they've been navigated to the "/" (Dashboard). Now, even if the user creates a new company or switches to another, they will stay on the SAME page.
The second bug that the PR addresses involves adjusting the logic when the user does not have the "view_dashboard" permission. I attempted to address it in the first permission PR, but I realized that it did NOT work. Now, it is fixed as well. If the user has the "view_dashboard" permission, they will be navigated to the "/dashboard" page upon login or manual navigation through the browser. If not, they will be directed to the "user_details" page because it is the only one they must be able to access.
Let me know …

[Cleanup] Switching Company Adjustment && Adjusting Logic if User Does Not Have Dashboard Permission to Go to User Details Page

---

src/components/RemoveLogoCTA.tsx
src/components/forms/Link.tsx
src/pages/credits/edit/Edit.tsx
src/pages/invoices/common/components/InvoicePreview.tsx
src/pages/invoices/edit/Edit.tsx
src/pages/purchase-orders/edit/Edit.tsx
src/pages/quotes/edit/Edit.tsx
src/pages/recurring-invoices/edit/Edit.tsx

@beganovich @turbo124 The PR includes the implementation of the Remove Logo CTA for all edit pages with PDF preview, which encompasses `Invoices`, `Recurring Invoices`, `Quotes`, `Credits`, and `Purchase Orders`. Screenshot:
@turbo124 Currently, this is shown only for `HOSTED` users with a `FREE PLAN`. Is it supposed to be like that?

[Cleanup] Remove Logo CTA Implementation On All Edit Pages With PDF Preview

---

src/pages/reports/common/components/SortableColumns.tsx

@beganovich @turbo124 The PR includes adjustments for column names for Reports. Therefore, if a user has defined the name of a custom field for a specific entity, it will be displayed when customizing columns. Screenshot:

[Cleanup] Custom Fields Translations | Reports

---

src/common/hooks/useResolveCurrency.ts
src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx
src/pages/settings/bank-accounts/components/Details.tsx

@beganovich @turbo124 The PR includes fixes for the `balance` value formatting for bank accounts in the table as well as on the Bank Account show page. So, from now on, we will take the `bankAccount.currency` property, using that property we will resolve the currency to get the `currency_id`, and then we will pass it to the `formatMoney` function to get the correct balance value format. Let me know your thoughts.

[Bugfix] Bank Account Balance Formatting

---

src/pages/dashboard/components/Totals.tsx

@beganovich @turbo124 The PR includes adding optional chaining and adding fallback values for properties of the `dashboard_charts` object. However, I was not able to recreate the bug in the production environment, and also locally, it seems that David found a very edge case here. Nevertheless, I believe that these changes will ensure 100% that we do not have any `null` values passed to the chart. Let me know your thoughts.

[Bugfix] dashboard_charts props null values

---

src/pages/dashboard/hooks/useGenerateActivityElement.tsx
src/pages/invoices/common/components/InvoiceSlider.tsx

@beganovich @turbo124 The PR includes fixes for labels on activities for invoices. Screenshot before:
Screenshot after:
Note: The bug has occurred on the Invoice slider activity as well.

[Bugfix] Activities label for Invoices

---

src/pages/quotes/edit/Edit.tsx
tests/e2e/quotes.spec.ts

@beganovich @turbo124 The PR involves implementing a split button for quotes on the Edit page, accompanied by necessary test adjustments to accommodate these changes. Screenshot:

[Cleanup] Quotes Split Button

---

src/pages/dashboard/components/Chart.tsx
src/pages/dashboard/hooks/useGenerateWeekDateRange.ts

@beganovich @turbo124 The PR includes fixes for chart points for the 'week' and 'month' periods. Previously, our logic for generating date ranges to obtain the chart was not optimal. I have now addressed this issue, eliminating unnecessary chart points.
It's important to note that the exact same logic applies to the 'day' period. However, for the 'week' period, we will consistently obtain the last date of the week. Similarly, for the 'month' period, the logic remains unchanged. In cases where the end date of the selected period does not encompass the last date of the week/month, the chart's end date will be the last date within the selected range.

[Bugfix] Chart Points | Dates

---

src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx

@beganovich @turbo124 The PR includes the implementation of a fallback action for design export. If copying to the clipboard fails, the design will be exported to a .txt file. Here is what will happen when copying to the clipboard fails:
https://github.com/invoiceninja/ui/assets/51542191/b3dcec0f-3b00-4e5d-b168-74d5b32be698
Note: The file will be named as `designName_[translating the 'export' keyword to lowercase].txt`.

[Bugfix] Custom Designs Export

---

src/components/ResourceActions.tsx
src/pages/clients/show/Client.tsx
tests/e2e/clients.spec.ts

@beganovich @turbo124 The PR includes refactoring of the Client show page navigation (implementing a split button) along with adjustments to tests. Screenshot: 

[Cleanup] Split Button | Client Show Page

---

src/pages/invoices/common/hooks/useHandleProductChange.ts

@beganovich @turbo124 The PR includes mapping the "product_cost" of the line item to the value of "product.cost". So, once the product is selected, the "lineItem.product_cost" will be populated with the value of "product.cost." Let me know your thoughts.

[Bugfix] Mapping the "product_cost" line item property to the "cost" property of the product when selecting

---

src/common/hooks/emails/useHandleSend.ts

@beganovich @turbo124 The PR includes fixes for not updating the tables once the 'send_email' action is triggered on the `**/email` page. Now, it is fixed. Let me know your thoughts.

[Bugfix] Send Email Functionality | Query Updating

---

src/pages/reports/common/components/ProductItemsSelector.tsx
tests/e2e/product.spec.ts

@beganovich @turbo124 The PR addresses the bug related to updating the list of products in the Product selector for Reports/Schedules. The bug was not due to invalidation, we had the correct invalidation in place. However, the issue originated from a logic problem within the selector. Let me know your thoughts.

[Bugfix] Updating Products Selector List After Query Invalidation | Reports/Schedules

---

src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts

@beganovich @turbo124 The PR includes fixing the bug with the "add_to_invoice" tasks action. I've prepared a quick demo as a guideline on how to recreate the bug. The issue was that a new "line_item" was added to the list every time the action was triggered, regardless of whether we saved the invoice or not. As a result, our stack kept increasing with new "line_item" instances, even though there should only be one. The problem was related to referencing objects. Quick demo:
https://github.com/invoiceninja/ui/assets/51542191/f5376e8f-914d-4b01-8630-9943098f4f49

[Bugfix] Add To Invoice Tasks Action

---

src/pages/credits/edit/Edit.tsx
tests/e2e/credits.spec.ts

@beganovich @turbo124 The PR implements the split button for the Credit's edit page with additional adjustments to tests regarding the UI change. Screenshot:

[Cleanup] Credits Split Button && Additional Tests Adjustment

---

src/pages/projects/Project.tsx
tests/e2e/projects.spec.ts

@beganovich @turbo124 The PR includes the implementation of a split button on the edit Project page, along with additional test adjustments related to the UI change. Screenshot:

[Cleanup] Project Split Button && Additional Test Adjustment

---

src/common/interfaces/company.interface.ts
src/pages/settings/bank-accounts/common/components/ConnectAccounts.tsx

@beganovich @turbo124 The PR includes the refactoring of the UI for the button related to the connecting_account for bank_integrations. If the user is on the `SELF-HOSTED` platform where only `Nordigen` is available, and the `disabled_upstream` property is true, then we will show the `reconnect_account` translation text instead of `connect_accounts`. However, if it is a `HOSTED` platform and the user is trying to connect `Nordigen`, and `disabled_upstream` is true, instead of the `connect` button, we will have a `reconnect` button there. Screenshot:

[Feature] Nordigen Redirect Button

---

src/common/interfaces/transactions.ts
src/components/forms/InputField.tsx
src/pages/transactions/components/Details.tsx
src/pages/transactions/components/FilterModal.tsx
src/pages/transactions/components/SearchArea.tsx
src/pages/transactions/components/TransactionForm.tsx

@beganovich @turbo124 The PR adds two new transaction fields that are read-only on the transaction edit page and transaction slider. Screenshots:
@turbo124 If you agree with the translation keywords "participant" and "participant_name," please add them to the translation files.

[Feature] Participant And Participant Name Transaction Fields | Edit Page && Transaction Slider

---

src/pages/products/Product.tsx
tests/e2e/product.spec.ts

@beganovich @turbo124 The PR includes the implementation of a split button for the Product entity and additional adjustments to the tests. Screenshot:

[Cleanup] Product Split Button && Additional Test Adjustment

---

src/pages/tasks/edit/Edit.tsx
tests/e2e/tasks.spec.ts

@beganovich @turbo124 The PR includes the implementation of a split button for tasks and additional adjustments to tests related to the changes. Screenshot:

[Cleanup] Tasks Split Button Implementation && Additional Tests Adjustment

---

src/common/hooks/useDisableNavigation.ts
src/common/hooks/useEntityAssigned.ts
src/common/interfaces/transactions.ts
src/common/queries/expense-categories.ts
src/common/queries/vendor.ts
src/pages/recurring-expenses/RecurringExpense.tsx
src/pages/recurring-expenses/components/Details.tsx
src/pages/recurring-expenses/components/Taxes.tsx
src/pages/recurring-expenses/documents/Documents.tsx
src/pages/recurring-expenses/index/RecurringExpenses.tsx
src/pages/settings/bank-accounts/common/queries.ts
src/pages/transactions/common/hooks/useTransactionColumns.tsx
src/pages/transactions/edit/Edit.tsx
src/pages/transactions/index/Transactions.tsx
tests/e2e/bank-transactions.spec.ts
tests/e2e/recurring-expense.spec.ts

@beganovich @turbo124 The PR includes permission adjustments for Recurring Expenses and Transactions. Once we merge the last two open PRs for permissions, the adjustments will be applied throughout the entire app, along with corresponding tests.
Important note: Currently, two transaction tests fail because we experienced an issue with the transaction archive/delete functionality. Once we address this issue in the API, those two tests should pass.

[Cleanup] Permissions Adjustment Recurring Expenses && Transaction With Additional Tests Fixes

---

src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx

@beganovich @turbo124 The PR includes fixes for RI caching conflicts. The slider endpoint has different parameters but the same caching query key, which caused a bug that prevented the correct data from being displayed for the slider. Let me know your thoughts.

[Bugfix] Recurring Invoices Caching Conflict

---

src/pages/reports/common/components/Preview.tsx

@beganovich @turbo124 The PR includes fixing the bug related to having a comma (,) in the value of a cell in the CSV file. This caused the second part of the value to be moved to the next cell. It is now resolved. Screenshot:

[Bugfix] Report Preview | Download CSV File | Comma In Cell Value Issue

---

src/pages/quotes/import/Import.tsx

@beganovich @turbo124 The PR includes fixes on the Breadcrumb URL to the Quotes table page. Let me know your thoughts.

[Bugfix] Breadcrump URL On Quote Import Page

---

src/components/EmailRecord.tsx

@beganovich @turbo124 The PR includes adjustments for dark mode on the email_history invoice tab and client show page. Let me know your thoughts.

[Cleanup] Email History Dark Mode Adjustments

---

src/pages/dashboard/components/Search.tsx

@beganovich @turbo124 The search functionality in the navbar had a plain "Search" word instead of the "search" translation keyword. So, now it has been replaced. Let me know your thoughts.

[Cleanup] Plain "Search" Word Replaced With search Translation Keyword

---

src/pages/vendors/Vendor.tsx
src/pages/vendors/edit/Edit.tsx
tests/e2e/vendors.spec.ts

@beganovich @turbo124 The PR includes the implementation of split buttons for showing and editing the Vendor page. Screenshots:

[Cleanup] Vendor Split Button Implementation && Tests Adjustment

---

src/pages/purchase-orders/edit/Edit.tsx
tests/e2e/purchase-orders.spec.ts

@beganovich @turbo124 The PR includes the implementation of a split button for purchase_orders, along with adjustments to tests regarding these changes. Screenshot:

[Cleanup] Purchase Order Split Button Implementation && Tests Adjustment

---

src/common/queries/invoice-design.ts
src/components/layouts/Default.tsx
src/components/layouts/common/hooks.ts
src/pages/invoices/common/components/InvoiceViewer.tsx
src/pages/settings/invoice-design/common/hooks/useActions.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/Edit.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx
tests/e2e/invoice-designs.spec.ts

@beganovich @turbo124 The PR includes the implementation of bulk actions on the edit page of invoice_design along with a split button. Additionally, the PR implements the render_html action to retrieve HTML code instead of PDF, allowing users to inspect the structure of the rendered design. Screenshot:
Note: If you agree with the translation keyword "render_html," please just add it to the translation files.

[Feature] Custom Designs Preview Action + Bulk Actions On Edit Page && Additional Tests

---

src/pages/clients/show/components/Gateways.tsx

@beganovich @turbo124 The PR includes implementation of a link to the customer Stripe page. So, the gateway token contains a `company_gateway_id`. I used that ID to find the `company_gateway` object from the pulled list from the API. After that, we have a `gateway_key` prop in `company_gateway`, and instead of searching for "cus_" in the `gateway_customer_reference` property, I will compare the `gateway_key` with the Stripe keys that David provided in the ticket. If it matches, then the icon/link to the customer Stripe page will be shown. I think this is the most secure and cleaner way. Screenshot:

[Feature] Customer Stripe URL

---

src/pages/expenses/Expense.tsx
tests/e2e/expenses.spec.ts

@beganovich @turbo124 The PR includes the implementation of a split button for the expense edit page, along with adjustments to tests regarding the changes. Screenshot:

[Cleanup] Expense Edit Page Split Button && Tests Adjustment

---

src/common/interfaces/company.interface.ts
src/pages/settings/email-settings/EmailSettings.tsx

@beganovich @turbo124 The PR includes the implementation of the missing `from_email` field for `Postmark` and `Mailgun` email providers. Screenshot:

[Cleanup] From Email Missing Field Postmark/Mailgun

---

src/pages/credits/common/components/SendEmailBulkAction.tsx

@beganovich @turbo124 The PR includes a fix for a tiny UI issue: the background color behind the "Yes" text in the button. Screenshot:

[Bugfix] Background Color On "Yes" Button For Email Credit Bulk Action

---

src/pages/vendors/edit/components/Form.tsx

@beganovich @turbo124 The PR includes the addition of missing validation to the `classification` vendor field. Screenshot:
Note: I've checked out all the other vendor fields, and this is the only one that missed the errorMessage prop.

[Bugfix] Classification Field Validation

---

src/common/interfaces/company.interface.ts
src/pages/expenses/common/hooks.tsx
src/pages/expenses/common/hooks/useCalculateExpenseAmount.ts
src/pages/expenses/create/Create.tsx
src/pages/expenses/create/components/AdditionalInfo.tsx
src/pages/expenses/create/components/Details.tsx
src/pages/expenses/create/components/Taxes.tsx
src/pages/recurring-expenses/common/hooks.tsx
src/pages/recurring-expenses/components/AdditionalInfo.tsx
src/pages/recurring-expenses/components/Details.tsx
src/pages/recurring-expenses/components/Taxes.tsx
src/pages/recurring-expenses/create/Create.tsx
src/pages/settings/expense-settings/ExpenseSettings.tsx
src/pages/settings/tax-settings/TaxSettings.tsx
tests/e2e/expenses.spec.ts
tests/e2e/recurring-expense.spec.ts
tests/e2e/taxes-helpers.ts

@beganovich @turbo124 The client reported the issue on Slack (https://invoiceninja.slack.com/archives/C9KSLL0TE/p1707207816191849) that the expense amount does not include entered taxes by rate or by amount. On the table, we had only been showing the pure `expense.amount` value, and we didn't do anything with taxes there. So, I included calculations for taxes by rate or by amount to show the gross amount rather than the net amount. After implementation, I compared the results with the Flutter app, which always gave me exactly the same result. 
The exactly same issue occurred with Recurring Expenses and their amounts, so that has also been fixed.

[Bugfix] Expenses/Recurring Expenses Amount Calculation

---

src/pages/invoices/common/components/SendEmailModal.tsx
src/pages/invoices/email/components/Mailer.tsx
tests/e2e/invoices.spec.ts

@beganovich @turbo124 The PR includes changing labels for custom templates when sending email. So, until now, the label will be entered in the subject on the templates_and_reminders page. Screenshots:

[Cleanup] Custom Templates Labels && Test Adjustment

---

src/common/queries/expense-categories.ts
src/components/DataTableColumnsPicker.tsx
src/components/dropdown/DropdownElement.tsx
src/components/expense-categories/ExpenseCategorySelector.tsx
src/pages/expenses/common/components/ExpenseCategory.tsx
tests/e2e/expenses.spec.ts

@beganovich @turbo124 The PR includes adding permission for the `new_expense_category` action in the dropdown on the category status badge. So, this action should only be displayed if the user is an `admin` or `owner` because it is the only permission that can create the expense category. Additionally, I've added two tests to check the visibility of the action. Screenshot:

[Bugfix] Adding Permission On new_expense_category Action In Dropdown On Category Status Badge && Additional Tests

---

src/pages/clients/edit/components/Details.tsx
src/pages/settings/company/components/Details.tsx
src/pages/vendors/edit/components/Form.tsx

@beganovich @turbo124 The PR includes adding missing classification options for Client/Vendor/Company entities. So, currently, we have `individual`, `business`, `company`, `partnership`, `trust`, `charity`, `government`, and `other` options available. Screenshot:

[Cleanup] Adding Missing Classification Options For Client/Vendor/Company

---

src/common/helpers/country/country-resolver.ts
src/pages/invoices/common/components/ProductsTable.tsx
src/pages/invoices/common/hooks/useFormatMoney.ts
src/pages/invoices/common/hooks/useResolveInputField.tsx

@beganovich @turbo124 The PR includes adjusting the logic for manipulation with line_items on creation pages when the client/vendor is not selected. The only thing that is important to mention is that the formatting of money is done with company settings details (currency_id and country_id) instead of using client/vendor details for doing it. Once the user selects the client/vendor, formatting will be done using those details. Let me know your thoughts.

[Cleanup] Adjusting Logic For Manipulation With Line Items Without Selecting Client/Vendor

---

src/common/interfaces/payment-activity.ts
src/common/queries/payments.ts
src/pages/payments/common/components/PaymentSlider.tsx
src/pages/payments/common/hooks/useActions.tsx
src/pages/payments/index/Payments.tsx

@beganovich @turbo124 The PR includes implementing the Payment slider. The main difference between this slider and others that we have implemented is that we do not have a `History` and `Email History` tabs here. I noticed that the response of the payment actually does not include the `activities` array that we used in other entities, even though I clearly included `activities.history` in the query, the same as for other entities. Is there any issue, or do we not support history for this entity?
Also, when I tried to pull `email_history`, I received a 422 error indicating that the passed `entity` is invalid. So, I assume that for payments, we also do not support the Email History tab here?
Screenshot:

[Feature] Payment Slider

---

src/common/interfaces/company.interface.ts
src/pages/settings/online-payments/OnlinePayments.tsx

@beganovich @turbo124 The PR includes the implementation of the new company settings field "use_unapplied_payment." Screenshot:

[Feature] New Company Settings Field "use_unapplied_payment"

---

src/pages/settings/invoice-design/pages/general-settings/components/PurchaseOrderDetails.tsx

@beganovich @turbo124 The PR includes fixes for labels on the purchase_order_details card under the Invoice Design page. We had fixed translations for values like `custom1`, etc. However, we missed it when the custom field name is entered. Screenshot:

[Bugfix] Purchase Order Custom Fields Labels | Invoice Design

---

src/components/DataTable.tsx
src/pages/clients/show/pages/Credits.tsx
src/pages/clients/show/pages/Expenses.tsx
src/pages/clients/show/pages/Invoices.tsx
src/pages/clients/show/pages/Payments.tsx
src/pages/clients/show/pages/Projects.tsx
src/pages/clients/show/pages/Quotes.tsx
src/pages/clients/show/pages/RecurringExpenses.tsx
src/pages/clients/show/pages/RecurringInvoices.tsx
src/pages/clients/show/pages/Tasks.tsx
src/pages/vendors/show/pages/Expenses.tsx
src/pages/vendors/show/pages/PurchaseOrders.tsx
src/pages/vendors/show/pages/RecurringExpenses.tsx

@beganovich @turbo124 The PR includes the implementation of hiding the `client` and `vendor` columns on tables that are on the client and vendor show pages, even if they are selected in the columns. Screenshots:

[Cleanup] Client/Vendor Column Hidding On Client and Vendor Show Page

---

src/pages/transactions/common/hooks/useCleanDescription.ts
src/pages/transactions/common/hooks/useTransactionColumns.tsx
src/pages/transactions/edit/Edit.tsx

@beganovich  @turbo124 The PR includes the implementation for cleaning the value of transaction description in the edge case if the API returns it. The "\n" will be replaced with an empty string. For testing, you can force entering the "\n" in the description, and after saving, you will see that part of the description will be replaced. Let me know your thoughts.

[Bugfix] Transaction Description 

---

src/components/AboutModal.tsx

@beganovich @turbo124 The PR includes the implementation of an additional label on the health check info modal. Currently, we do not have it in the response, but I assumed it is there. The label will be the translated keyword "api_version," but the value will be the `api_version` property from the response. Screenshot:

[Feature] API Version On Health Check Modal

---

src/pages/settings/company/components/Defaults.tsx
src/pages/settings/workflow-settings/components/Quotes.tsx

@beganovich @turbo124 The PR includes replacing the "use quote terms" field. Screenshot:

[Cleanup] Replacing "Use Quote Terms" Field

---

src/pages/projects/common/hooks/useInvoiceProject.tsx

@beganovich @turbo124 The PR includes fixes in the logic of invoicing project action. Actually, we already had an implementation for showing the project name in the line item description, but we had one unnecessary part of the logic. We showed the project name only if the `company.invoice_task_project` is turned on. I checked the Flutter app, and it does not work like that there. So, I removed this part of the logic to make it work always. Screenshot:

[Cleanup] Invoicing Project | Project Name In Line Item Description

---

src/pages/settings/company/components/Defaults.tsx
src/pages/settings/online-payments/OnlinePayments.tsx

@beganovich @turbo124 The PR includes moving the Payment fields from the Defaults page to the Payment Settings page. Screenshot:

[Cleanup] Moving Payments Fields From Defaults Page To Payment Settings Page

---

src/components/layouts/Settings.tsx

@beganovich @turbo124 The PR includes adding the subtext "PRO" to the "Advanced Settings" text. Screenshot:

[Feature] PRO Text On Advanced Settings

---

src/pages/settings/email-settings/EmailSettings.tsx

@beganovich @turbo124 The PR includes adding missing e-invoice type select field options. We missed `XInvoice_3_0` and `XInvoice_2_3`. Screenshot:

[Bugfix] Adding Missing E-Invoice Type Options

---

src/pages/clients/show/components/Standing.tsx

@beganovich @turbo124 The PR includes fixes for the private_notes icon on the client show page. So, even if we did not enter any private notes, we were still showing the icon, which slightly breaks the UX here. Screenshot:

[Bugfix] Private Notes Icon | Client Show Page

---

src/pages/reports/common/components/SortableColumns.tsx

@beganovich @turbo124 The PR includes fixes for translations of custom fields on the reports page. To recreate this specific edge case, you need to create a custom field for the `Client` entity named "client1". 
Currently, on the develop, if you do this, you will get the translated label "Custom Value 1". However, this is translation of the "client1" keyword, which is incorrect behavior. It should remain as "client1" since that is the name of the field. Therefore, I have made a fix so that any entered value will not be translated, but instead, the value will be displayed as entered. Screenshot:

[Bugfix] Custom Fields Labels Translations On Reports Page

---

src/pages/invoices/common/components/InvoiceStatus.tsx
src/pages/invoices/common/hooks/useInvoiceFilters.ts

@beganovich @turbo124 The PR includes changing "overdue" to "past_due" in translated text. The terminology is not just changed in the status badge but also in the custom filter section. Of course, the same value will be sent in the query parameter, the change is only on the UI. Screenshot:

[Cleanup] Past Due/Overdue Terminology Changing

---

src/pages/settings/subscriptions/common/components/Overview.tsx
src/pages/settings/subscriptions/common/hooks/useSubscriptionColumns.tsx
src/pages/settings/subscriptions/create/Create.tsx

@beganovich @turbo124 The PR includes the implementation of the `purchase_page` column. Screenshot:
Additionally, I noticed that we display the `purchase_page` link on the creation page. However, at that point, we do not yet have the correct URL since the ID for the object is not defined. Therefore, I removed this link from the creation page.

[Feature] Purchase Page Column Implementation && Removing Purchase Page Link From Creation Page

---

src/pages/settings/import-export/common/components/Export.tsx

@beganovich @turbo124 The PR includes the implementation of new export types under the import_export section. The only thing we miss here is the `purchase_order_items` translation keyword, which should be added. Screenshot:

[Feature] New Export Types

---

src/pages/invoices/common/components/ProductCreate.tsx

@beganovich @turbo124 I did not succeed in recreating the bug when the product is not selected in the combobox or created, but the modal is just closed. The logic seems very clear, it's just a function that creates the product. However, I made a little cleanup for this edge case that you experienced. Since we have an endpoint on the combobox that pulls 800 products on the first page, I consider that it could be a possible reason for this bug. 
Maybe it just needed a little bit more time for the endpoint to pull all products. I added a tiny timeout for the product selection in the combobox once the products are refetched in the list. It is not even visible on the UI, but I think it can help to always have a selected product in the combobox. Let me know your thoughts.

[Cleanup] Product Modal Creation On Invoice Edit Page

---

src/components/import/UploadImport.tsx
src/pages/settings/import-export/common/components/UploadImport.tsx

@beganovich @turbo124 The PR includes additional checks for row lengths on files uploaded under the Import | Export functionality. Therefore, if we encounter a single row/header, we will not consider those files as prepared for the final import, and we will display a toaster error message with the translation keyword `csv_rows_length`. This translation keyword should display a message similar to "Please check your files, as it appears the data is too short...". Please let me know if you agree with this translation keyword. Let me know your thoughts.

[Bugfix] Rows Length On Import

---

src/common/interfaces/company.interface.ts
src/pages/settings/localization/components/Settings.tsx

@beganovich @turbo124 The PR includes the implementation of the new localization field "Rappen Rounding". Screenshot:
Note: We're missing the "enable_rappen_rounding" translation keyword from files. If you agree with it, please just add it there.

[Feature] Rappen Rounding Field | Localization

---

src/common/hooks/useEntityPageIdentifier.ts
src/common/queries/transactions.ts
src/pages/transactions/common/hooks/useActions.tsx
src/pages/transactions/common/hooks/useCustomBulkActions.tsx
src/pages/transactions/index/Transactions.tsx

@beganovich @turbo124 The PR includes the implementation of bulk and single "Unlink Payment" actions for transactions. Screenshots:
`Note`: We are missing the "unlinked_payment" and "unlink_payment" translation keywords from files, so if you agree, please just add it there.

[Feature] "Unlink Payment" Transaction Action

---

src/pages/dashboard/Dashboard.tsx
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx

@beganovich @turbo124 The PR includes the implementation of a new dashboard table for "Upcoming" Recurring Invoices. Screenshot:
`Note`: We're missing the "upcoming_recurring_invoices" translation keyword from the files, so if you agree, please just add it.

[Feature] Upcoming Recurring Invoices Dashboard Table

---

src/common/hooks/useUnlockButtonForHosted.ts
src/common/hooks/useUnlockButtonForSelfHosted.ts
src/components/layouts/Default.tsx

@beganovich @turbo124 The PR includes fixes for displaying the upgrade plan button for both hosted and self-hosted platforms. So, the "white_label_button" will be displayed only for ADMIN/OWNER users on the SELF-HOSTED platform, while the "unlock_pro" button will be displayed only for ADMIN/OWNER users on the HOSTED platform. Sub-accounts that are not admins or owners will not have any buttons displayed for upgrading the plan. Let me know your thoughts.

[Bugfix] Displaying Upgrade Plan Button

---

src/pages/settings/email-settings/common/components/SMTPMailDriver.tsx

@beganovich @turbo124 The PR includes adding the "bcc_email" and "send_time" fields to the SMTP configuration. Screenshot:

[Bugfix] Adding bcc_email and send_time fields for SMTP config

---

src/components/DropdownDateRangePicker.tsx
src/components/datatables/DateRangePicker.tsx

@beganovich @turbo124 The PR includes fixes with date formatting on the range picker on the invoices table and dashboard. So, the issue was related to the `dayjs` library not supporting our two formats (`'DD. MMM. YYYY'` and.`'ddd MMM D, YYYY'`). Once we select those two formats, we should not pass them to the `dayjs` function. Only if we do not pass the format, it will be formatted correctly. Let me know your thoughts.

[Bugfix] Fixing Date Formatting On Range Picker Value Change

---

src/components/cards/Card.tsx
src/pages/settings/invoice-design/pages/custom-designs/CustomDesign.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Body.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Footer.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Headers.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Includes.tsx

@beganovich @turbo124 The PR includes adjusting the height for cards on custom design pages. Screenshot:

[Cleanup] Adjusting Code Cards Height | Custom Designs

---

src/components/forms/ColorPicker.tsx
src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx

@beganovich @turbo124 The PR includes the implementation of the default palette color picker for "primary" and "secondary" colors on the general settings invoice design page, in the standard color picker. Screenshots:

[Feature] Implementing Default Palette Modal Picker | Invoice Design

---

src/common/helpers.ts
src/common/hooks/useCompanyTimeZone.ts
src/common/hooks/useDateTime.ts
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
src/pages/recurring-invoices/common/hooks.tsx

@beganovich @turbo124 The PR includes formatting the "next_send_date" column for Recurring Invoices. It involves formatting it to the date-time format using the formats entered in the company settings along with the "military_time" property. This has been done in three places:
- All Recurring Invoices tables including the dashboard table
- Recurring Invoice Slider
Screenshot:

[Cleanup] Next Send Date Property Formatting In Date Time Format | Recurring Invoices

---

src/common/helpers/request.ts
src/common/hooks/useRefetch.tsx
src/components/DataTable.tsx

@beganovich @turbo124 The PR includes the implementation of query invalidation for activities in three cases:
- For any `PUT` method (Updating/Editing entities).
- For any `DELETE` method (Deleting entities).
- For any `POST` method which contains the `action` property in the payload set to `'delete'` (Deleting entities).

[Cleanup] Invalidating The Activities Query On Any Delete/Edit/Update

---

src/common/hooks/useDataTablePreference.ts
src/common/hooks/useDataTablePreferences.ts
src/common/hooks/useStoreSessionTableFilters.ts
src/pages/authentication/Logout.tsx

@beganovich @turbo124 The PR includes the implementation of `filter_text` and `current_page` filters through session storage instead of storing them into `react_settings`. Thus, once the user logs out of the app or leaves the current session, the stored data will be cleared. When the user rejoins the app, the data will be reset to the default values. Let me know your thoughts.

[Cleanup] Implementing Current Page And Text Filter Through Sessions Storage

---

src/components/AboutModal.tsx

@beganovich @turbo124 The PR includes fixing a bug with the `force_update` button. A user reported an issue where, even after updating the app version, they still had an available update `(https://github.com/invoiceninja/ui/issues/1625)`. The bug is not related to functionality, we simply missed one part of the logic, which involves removing the force_update button once the latest version is equal to the installed one. Screenshot:
So, now the update button is only available if the latest and installed versions are different.

[Bugfix] Force Update Button

---

src/common/constants/blank-company-settings.ts
src/common/interfaces/company.interface.ts
src/pages/settings/email-settings/EmailSettings.tsx
src/pages/settings/email-settings/common/hooks/useEmailProviders.ts

@beganovich @turbo124 The PR includes the implementation of a new `client_brevo` mailer, which is exactly the same as `client_postmark` with field setup, except for the secret field, which will be saved in the `brevo_secret` property. Screenshot:

[Feature] Implementing client_brevo Mailer

---

src/components/forms/InputField.tsx
src/pages/settings/gateways/create/components/LimitsAndFees.tsx

@beganovich @turbo124 The PR involves fixing bugs for `NaN` values on the `Limits/Fees` page. In fact, the bug can be divided into two parts: the fields on this page were not of the `number` type, they were text/string fields. While specifying them, I also added a small part of the logic which should be the reason for resolving NaN values for input fields. This part of the logic was added globally under the `InputField` component. Let me know your thoughts.

[Bugfix] NaN Values On Limits/Fees Page

---

src/components/Modal.tsx
src/pages/invoices/common/components/ClientCreate.tsx

@beganovich @turbo124 The PR includes UX improvements for client creation, so we changed the implementation through the modal with the possibility of adjusting how many fields the user wants to see: the fundamental ones or all of them. Screenshot:
`Note:` We're missing the translation keywords 'show_more' and 'show_less' from the files. If you agree with the implementation, please add them there.

[Cleanup] Transforming Client Create Slider Into Customizable Modal

---

src/components/FileIcon.tsx
src/components/Tabs.tsx
src/components/cards/Divider.tsx
src/components/resizable-panels/Panel.tsx
src/components/resizable-panels/PanelGroup.tsx
src/components/resizable-panels/PanelResizeHandle.tsx
src/pages/expenses/Expense.tsx
src/pages/expenses/common/components/DocumentPreview.tsx
src/pages/expenses/documents/Documents.tsx
src/pages/expenses/edit/Edit.tsx

@beganovich @turbo124 The PR includes the implementation of a "preview" mode for documents on the Expense edit page. Therefore, I believe that we are only able to natively preview jpg, jpeg, svg, webp, tiff, png, and pdf file types. All other types require the extension for displaying them. Here is a screenshot of how the preview looks when we can display the file:
Here is the screenshot when the file type cannot be shown natively in React:

[Feature] Implementing Expense Preview | Scaffold

---

src/pages/invoices/common/hooks/useHandleProductChange.ts

@beganovich @turbo124 The PR includes fixing a bug for auto-filling the quantity/hours for the products/tasks table when the `fill_products` property is turned off. Now, the quantity/hours will be the same as the user entered earlier. Let me know your thoughts.

[Bugfix] Auto-Fill Quantity/Hours | Products/Tasks Tables

---

src/pages/settings/company/edit/CompanyEdit.tsx

@beganovich @turbo124 The PR includes slight improvements to the UX on the Company Edit modal. So, once you enter the `company_name`, the logic will automatically update the `subdomain` using the logic of taking only characters and combining them into a lowercase string. Also, to achieve a better UX, I've changed it here to update values on the `onChange` event rather than the `onBlur` event, so I've overridden the default behavior. Screenshot:

[Cleanup] Creating "Subdomain" Value From "Company Name" Field

---

src/common/colors.ts
src/common/hooks/useInjectUserChanges.ts
src/common/hooks/useReactSettings.ts
src/pages/settings/user/components/Preferences.tsx

@beganovich @turbo124 The PR includes the implementation of saving the `dark_mode` boolean value into `react_settings` instead of saving it into the atom through one user's session. Let me know your toughts.

[Bugfix] Saving Dark Mode Through react_settings

---

src/pages/transactions/common/hooks/useTransactionColumns.tsx

@beganovich @turbo124 The PR includes formatting the "date" column on the transaction table. Screenshot:

[Bugfix] Formatting "Date" Column On Transactions Table

---

src/pages/tasks/common/components/TaskDetails.tsx

@beganovich @turbo124 The PR includes fixes for the width of the client/project fields on the tasks pages. Screenshot of the bug:

[Bugfix] Client/Project Fields Width 

---

src/pages/settings/gateways/create/components/LimitsAndFees.tsx

@beganovich @turbo124 The PR includes the implementation of missing tax selectors on the gateway edit page within the limits/fees tab. Screenshot:

[Bugfix] Implementing the missing tax selector for the Limits/Fees page

---

package-lock.json
src/common/hooks/usePaymentTypes.ts
src/pages/payments/create/Create.tsx
src/pages/payments/edit/Edit.tsx

@beganovich @turbo124 The PR includes improvements for the select field dropdown of `payment_types`. Instead of being in random order, it is now sorted alphabetically A-Z once it is translated. This means it will be sorted correctly for any language. Screenshot:

[Cleanup] Payment Types Order | A-Z | Payment Pages

---

src/components/QuickCreatePopover.tsx

@beganovich @turbo124 The PR includes fixes for the position of the quick create popover once the `show_mini_sidebar` is set to true. Screenshot:

[Bugfix] Position Fixes Quick Create Popover When Mini Sidebar Is Displayed

---

package-lock.json
package.json
src/components/forms/MarkdownEditor.tsx

@beganovich @turbo124 The PR includes updating the `TinyMCE` package to version `5.0.1`, the latest available version. David, you mentioned in the ticket to update the package to v7, but the part of the package that we have installed is actually with 5 versions. The entire TinyMCE package (https://www.npmjs.com/package/tinymce) has 7 versions, but the version specifically installed for React (https://www.npmjs.com/package/@tinymce/tinymce-react) has 5 versions. The second package that we use is specifically for React and is much lighter, weighing only 99.9 kB, while the entire package is 8.28 MB. Therefore, I believe that the main reason for using only a part of the package is its size.
Once I updated the version, the "license_key" prop, which was previously set to "gpl", is no longer …

[Cleanup] Updating Tinymce To 5.0.1 Version

---

src/common/interfaces/company-gateway.ts
src/pages/settings/gateways/create/components/RequiredFields.tsx

@beganovich @turbo124 The PR includes the implementation of the "always_show_required_fields" field on the Company Gateway page under the "Required Fields" tab. Screenshot:
`Note`: We're missing the "always_show_required_fields" translation keyword in the files. If you agree, please just add it to the files.

[Feature] Implementing always_show_required_fields Field | Company Gateways

---

src/components/InfoCard.tsx
src/pages/projects/show/Show.tsx

@beganovich @turbo124 The PR includes the implementation of the "private_notes" on the project show page, but the notes will only be displayed if the user is an `ADMIN` or `OWNER`. Screenshot:

[Feature] Implementing private_notes On The Project Show Page

---

src/pages/invoices/create/hooks/useHandleCreate.ts
src/pages/tasks/kanban/Kanban.tsx

@beganovich @turbo124 The PR includes two fixes: one for refetching the tasks query after the task is invoiced, and another for filtering the list in Kanban so that invoiced tasks are not displayed. Let me know your thoughts.

[Bugfix] Refetch Tasks Query After Invoicing Task && Kanban List Filter For Invoiced Tasks

---

src/pages/tasks/common/components/TaskTable.tsx

@beganovich @turbo124 The PR includes fixes for setting the value once it is not selected but the `onBlur` event is triggered. You can find the video of the broken behavior in the issue where the client made a video (https://github.com/invoiceninja/ui/issues/1718). The video of fixed behavior:
https://github.com/invoiceninja/ui/assets/51542191/12fd08ea-9aeb-4788-acb3-86795cc69519

[Bugfix] Fixes For onBlur Event When Value Is Not Selected | Tasks Table | #1718

---

src/pages/settings/account-management/component/Licence.tsx
src/pages/settings/account-management/component/Plan.tsx

@beganovich @turbo124 The PR includes changes for the plan label on the account management page for self-hosted users. Screenshot:

[Bugfix] Account Management Plan Label Changes | Self-hosted

---

src/components/tax-rates/TaxRateSelector.tsx
src/pages/invoices/common/components/InvoiceTotals.tsx

@beganovich @turbo124 The PR includes fixes for adjusting the label on the tax selector when the tax_rate is changed but already selected on the resource. Let me know your thoughts.

[Bugfix] Matching Tax Rates From PDF Preview And Tax Selector

---

src/pages/clients/show/components/GatewayTypeIcon.tsx
src/pages/settings/gateways/create/Create.tsx

@beganovich @turbo124 The PR includes ensuring that PayPal Rest is displayed through cards and ensuring that the PayPal card with the logo is always second (after the Stripe card). Screenshot of hosted:
Screenshot of self-hosted:

[Cleanup] Gateways Cards | Gateway Creation Page

---

src/pages/invoices/common/hooks/useHandleProductChange.ts
src/pages/invoices/common/hooks/useResolveInputField.tsx

@beganovich @turbo124 The PR includes logic changes for displaying the value in the `unit_cost` column. So, if `product.cost` is greater than zero (0), then the `product.cost` will be displayed in the `unit_cost` column instead of `product.price`. This will only happen for Purchase Orders. Let me know your thoughts.

[Bugfix] Displaying Product Cost Instead Of Product Price | Purchase Orders Line Items | #1747

---

src/components/forms/InputField.tsx

@beganovich @turbo124 The PR includes adding the `9999-12-31` date as the maximum date for date input fields to prevent invalid dates larger than this one, which are unrealistic. Let me know your thoughts.

[Cleanup] Adding Max Date For Date Type Input Fields

---

src/pages/credits/common/hooks.tsx
src/pages/invoices/create/hooks/useHandleCreate.ts
src/pages/invoices/edit/hooks/useInvoiceSave.ts
src/pages/purchase-orders/common/hooks.tsx
src/pages/purchase-orders/edit/hooks/useSave.ts
src/pages/quotes/common/hooks.tsx
src/pages/recurring-invoices/common/hooks.tsx

@beganovich @turbo124 The PR includes the implementation of an error toaster for the `amount` property for invoices, quotes, credits, recurring_invoices, and purchase_orders. Let me know your thoughts.

[Cleanup] Toaster Error Message For Amount Prop

---

src/components/import/UploadImport.tsx

@beganovich @turbo124 The PR includes the implementation of a "Clear" button on the import page for mappings that sometimes become incorrect. Screenshot:

[Cleanup] Implementing "Clear" Button For Import Mappings To Unselect All Of Them

---

src/components/layouts/Default.tsx
src/pages/settings/account-management/component/Licence.tsx

@beganovich @turbo124 The reason the user experienced this issue (https://github.com/invoiceninja/ui/issues/1746) is because the `VITE_WHITELABEL_INVOICE_URL` environment variable is not populated. However, the 'Purchase White Label' button in the navigation bar has a fallback to a fixed URL, so when the variable is not populated, the button still has a URL to navigate to.
Now, I have set the newest URL as a fallback value for both buttons. So, even if the environment variable is not populated, the tab will be opened with: `https://invoiceninja.invoicing.co/client/subscriptions/O5xe7Rwd7r/purchase`.

[Bugfix] "Purchase License" Button Link

---

src/components/import/UploadImport.tsx

@beganovich @turbo124 The PR includes adjustments to the functionality for clearing mapped values for imports. Instead of having a 'Clear' button to clear the whole form, we now have an 'X' button for each select field to remove the mapped value. Screenshot:

[Cleanup] Refactoring Clearing Mapped Values

---

src/common/interfaces/user.ts
src/pages/authentication/Register.tsx
src/pages/settings/account-management/common/hooks/useAccountManagementTabs.tsx
src/pages/settings/account-management/component/ReferralProgram.tsx
src/pages/settings/account-management/component/index.ts
src/pages/settings/routes.tsx

@beganovich @turbo124 The PR includes the implementation of the referral program. It includes the implementation of the referral program tab and the `signup` endpoint parameter if the `rc` exists in the URL. The value of the referral code is taken from `user.referral_code`. Currently, I believe the production API does not return it, which is why the value is `undefined` in the screenshot. The feature will be available only for hosted users.  Screenshot:

[Feature] Implementing Referral Program

---

src/common/helpers.ts
src/pages/expenses/create/components/Details.tsx

@beganovich @turbo124 The PR includes the implementation of icons on the left side that will open new tab to the show pages of entities. In this case, for Expenses, the icons are implemented for the 'Vendor', 'Client', and 'Project' selectors. The icon will only be displayed if there is a selected value in the selector. Screenshot:

[Feature] Implementing Links To Entities | Expenses

---

src/components/forms/InputCustomField.tsx

@beganovich @turbo124 The PR includes fixes for checking the toggle across the app where there is a possibility to return a `"1"` value instead of `"true"` or `true` as a boolean. While working on the `bulk_update` action for clients, I discovered a bug when updating values for `custom fields`. If the custom field is chosen as a toggle/switch, then when we send `true` as a boolean in the payload, the API's response is a string value `("1")`. We had not covered that case earlier, but it is covered now. Let me know your thoughts.

[Bugfix] Checking The Toggle

---

src/common/hooks/useBulkUpdatesColumns.ts
src/common/interfaces/statics.ts
src/common/queries/clients.ts
src/components/forms/InputCustomField.tsx
src/pages/clients/common/components/AssignToGroupBulkAction.tsx
src/pages/clients/common/components/BulkUpdatesAction.tsx
src/pages/clients/common/hooks/useCustomBulkActions.tsx

@beganovich @turbo124 The PR includes the implementation of bulk_update client action. Screenshots:
`Note`: We are missing the `update_records` translation keyword that I used in the solution to get the final translation for "Update Records." If you would agree, please just add it to the files.

[Feature] Implementing Bulk Updates Action | Clients

---

src/pages/payments/create/Create.tsx
src/pages/payments/create/hooks/useSave.ts

@beganovich @turbo124 The PR includes prevention of potential double requests when creating payments. We did not have the save button disabled once the first request was triggered, and we did not prevent calling the function responsible for reaching the payments endpoint for payment creation. I have now implemented this to prevent any double requests here, as we do for most other entities. Let me know your thoughts.

[Bugfix] Creating Payments | Requests

---

src/components/banners/ActivateCompany.tsx

@beganovich @turbo124 The PR includes adjusting the logic to display the company activity banner on both platforms: hosted and self-hosted. Screenshot:

[Cleanup] Company Activity Banner | Self-Hosted

---

src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx

@beganovich @turbo124 The PR includes changing the "reconnect_account" translation keyword to "reconnect". Let me know your thoughts.

[Cleanup] Changing Tooltip "reconnect_account" Keyword

---

src/pages/purchase-orders/edit/components/VendorSelector.tsx

@beganovich @turbo124 The PR includes the implementation of `view_vendor` and `edit_vendor` actions, similar to what we have for the client selector, for the vendor selector. Screenshot:
`Note`: One more thing has been updated in the PR: for the client selector, we are not disabling the field but displaying pure text on the edit pages. I did the same for the vendor selector.

[Cleanup] Implementing CTAs For Vendor Selector

---

src/components/layouts/common/hooks.ts
src/pages/settings/payment-terms/Create.tsx
src/pages/settings/payment-terms/PaymentTerms.tsx
src/pages/settings/payment-terms/edit/Edit.tsx

@beganovich @turbo124 The PR includes two changes for payment terms. We've updated the payment terms table from a very old setup to the standard one used in the app. Additionally, we've moved the more_actions dropdown into the navigation, which is also the standard in the app. Screenshots:

[Cleanup] Cleaning up Payment Terms Pages

---

src/pages/settings/workflow-settings/components/Invoices.tsx

@beganovich @turbo124 The PR includes the implementation of the new lock_invoices option (end_of_month). Screenshot:
`Note`: We are missing the "end_of_month" keyword in the translation files, so please just add it there.

[Feature] New Lock Invoices Option

---

src/pages/settings/group-settings/create/Create.tsx

@beganovich @turbo124 The PR includes the implementation of a plan alert banner on the group settings creation page. Screenshot:

[Cleanup] Group Settings Plan Alert Banner

---

src/pages/invoices/common/components/InvoiceViewer.tsx
src/pages/settings/invoice-design/pages/custom-designs/CustomDesign.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Body.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Footer.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Headers.tsx
src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Includes.tsx

This improves syntax highlighting for custom design components that render Twig tags and shows the validation errors for syntax issues.

Set twig as default language for custom designs 

---

src/pages/clients/common/hooks/useClientColumns.tsx
src/pages/clients/index/Clients.tsx
src/pages/clients/show/components/Details.tsx
src/pages/settings/account-management/component/Plan.tsx
src/pages/settings/group-settings/edit/components/Clients.tsx

@beganovich @turbo124 The PR includes the implementation of the 'Group' column for clients and displaying the assigned group on the show page. Screenshots:

[Cleanup] Implementing 'Group' Column and Adjusting Show Page | Clients

---

src/pages/settings/account-management/component/Plan.tsx

@beganovich @turbo124 The PR includes adjustments for the "Expires On" label under "Account Management". If the year of the `plan_expires` property is before `2000`, we will display the translated text from the "forever_free" keyword. Otherwise, the date when the plan expires will be displayed. Screenshot:
`Note`: We are missing the "forever_free" translation keyword from the files. If you agree, please add it there.

[Cleanup] Adjusting "Expires On" Label | Account Management

---

src/components/dropdown/Dropdown.tsx
src/components/dropdown/DropdownElement.tsx

@beganovich @turbo124 The PR includes adding word wrapping in the dropdown element when needed. Screenshot:
Closes #1818 

[Bugfix] Wrapping Words In The Dropdown | Different Languages

---

src/components/DataTableColumnsPicker.tsx
src/pages/clients/common/hooks/useClientColumns.tsx

@beganovich @turbo124 The PR includes adding a new "City" column for clients and also sorting the columns alphabetically in the column selector. Screenshot:

[Cleanup] Adding "City" Column For Clients

---

src/pages/settings/email-settings/EmailSettings.tsx

@beganovich @turbo124 The PR includes fixes for displaying the two missing fields for SMTP configuration, "Reply to Email" and "Reply to Name." Screenshot:

[Bugfix] Adding Missing Fields "Replay to Email/Name" | Smtp Configuration

---

src/pages/reports/common/components/ProductItemsSelector.tsx
src/pages/reports/common/components/StatusSelector.tsx
src/pages/settings/gateways/common/components/GatewaysTable.tsx

@beganovich @turbo124 The PR includes fixes for dark mode on the status selectors on the Reports page, along with setting same styles for some selectors where we did not have it. Screenshot:

[Bugfix] Adjusting Dark Mode For Some Selectors

---

src/components/AboutModal.tsx

@beganovich @turbo124 The PR includes fixes to enable the `/health_check` route only for self-hosted platforms. Let me know your thoughts.

[Bugfix] Enabling "Health Check" Endpoint Only On Self-Hosted

---

src/pages/invoices/edit/components/Actions.tsx

@beganovich @turbo124 I've accidentally adjusted one prop that should not be conditionally added, which caused a bug with the placement of the `cancel` action in the dropdown on the table. I've just fixed it. Screenshot of the bug:

[Bugfix] "Cancel" Action Order

---

src/pages/settings/client-portal/components/Settings.tsx

@beganovich @turbo124 The PR includes fixes on the client portal page for the "Portal Mode" field. The field will only be allowed to enter a value for enterprise-hosted users for everyone else the field will be disabled. In addition, we've added text indicating that the user needs to upgrade their plan. Screenshot:

[Bugfix] Disabling "Portal Mode" | Client Portal

---

src/pages/invoices/common/components/ClientSelector.tsx

@beganovich @turbo124 The PR includes the implementation of a tooltip for the copy portal URL icon. Screenshot:
`Note`: I've used the "copy_portal_url" translation keyword for the message in the tooltip. The translation keyword should give us the message like "Copy Portal URL." If you agree, please add this keyword to the translation files.

[Cleanup] Implementing Tooltip For Copy Portal URL Icon

---

src/components/forms/MarkdownEditor.tsx

This fixes an issue with relative URLs for the current window href.

Disable TinyMCE auto link convert

---

src/pages/dashboard/components/UpcomingRecurringInvoices.tsx

@beganovich @turbo124 The PR includes adjustments to the 'balance' column for the `recurring_invoice` table on the dashboard. Screenshot:

[Cleanup] "Balance" Column Adjusting | Recurring Invoices | Dashboard

---

src/common/hooks/useDataTablePreferences.ts
src/common/hooks/useDataTableUtilities.ts
src/pages/clients/show/hooks/useDocumentFilters.ts
src/pages/credits/common/hooks/useCreditsFilters.ts
src/pages/expenses/common/hooks.tsx
src/pages/invoices/common/hooks/useInvoiceFilters.ts
src/pages/payments/common/hooks/usePaymentFilters.tsx
src/pages/purchase-orders/common/hooks.tsx
src/pages/quotes/common/hooks.tsx
src/pages/recurring-invoices/common/hooks.tsx
src/pages/tasks/common/hooks.tsx
src/pages/transactions/common/hooks/useTransactionFilters.tsx

@beganovich @turbo124 The PR includes removing the 'All' filter from the selectors of the custom filters. So, from now on, to show all data in tables, the selector will be empty and nothing will be selected. Screenshot:

[Cleanup] Removing "All" Filter | Custom Filters

---

src/common/hooks/useDataTablePreferences.ts
src/components/DataTable.tsx
src/pages/dashboard/components/ExpiredQuotes.tsx
src/pages/dashboard/components/PastDueInvoices.tsx
src/pages/dashboard/components/RecentPayments.tsx
src/pages/dashboard/components/UpcomingInvoices.tsx
src/pages/dashboard/components/UpcomingQuotes.tsx
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx

@beganovich @turbo124 The PR includes setting the "per_page" parameter through the endpoint to a fixed value of 50, instead of storing it in the preferences where it was always 10. Let me know your thoughts.

[Bugfix] "Per Page" Query Parameter | Dashboard Tables

---

src/common/helpers.ts
src/pages/tasks/kanban/common/hooks.ts

@beganovich @turbo124 The PR includes fixes for formatting dates in specific formats that Day.js handles differently. We need to always prepare dates in the 'YYYY-MM-DD' format for the Day.js format function. Let me know your thoughts.

[Bugfix] Time Logs Parsing | Format Date Issue

---

src/pages/projects/common/hooks/useInvoiceProject.tsx

@beganovich @turbo124 The PR includes fixes for calculating hours, which need to be multiplied by the task rate to get the final amount of money when a task is running. If the task is running for the first time, the amount will be presented as 0.00. However, if it has run previously, the calculation will be made for all time logs before the last one, which is the currently running time log. Only "fully" populated time logs will be included in the calculation. Screenshot:

[Bugfix] Hours Calculation When Task Running | Amount Money Formatting

---

src/components/CopyToClipboard.tsx

@beganovich @turbo124 The PR includes fixes for hiding the "Copy to Clipboard" icon when the context is not secure. Let me know your thoughts.

[Cleanup] Hiding "Copy to Clipboard" Icon When Context Is Not Secure

---

src/pages/settings/user/components/Notifications.tsx

@beganovich @turbo124 The PR includes the implementation of the `task_assigned` toggle on the "Notification" tab for the "User Details" page. If the toggle is turned on, task_assigned will be added to the notification property array of strings. If it is turned off, the notification will be removed from the array. Screenshot:
`Note`: We are missing the `task_assigned` and `task_assigned_help` translation keywords from the files. If you agree, please add them.

[Feature] Implementing Task Assigned Toggle | Notifications | User Details

---

src/components/DataTable.tsx
src/pages/dashboard/components/PastDueInvoices.tsx
src/pages/dashboard/components/UpcomingInvoices.tsx
src/pages/dashboard/components/UpcomingQuotes.tsx
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx

@beganovich @turbo124 The PR includes adjustments for query parameters for dashboard tables. For tables with the `overdue` filter applied, the sort parameter will be set to `"due_date|asc"`. However, for tables with the `upcoming` filter applied, the sort parameter has been `REMOVED` by default. Let me know your thoughts.

[Cleanup] Adjusting "Sort" Query Parameter | Dashboard Tables

---

src/components/credit/CreditSelector.tsx
src/components/invoices/InvoiceSelector.tsx
src/components/projects/ProjectSelector.tsx
src/components/quotes/QuoteSelector.tsx
src/pages/credits/index/Credits.tsx
src/pages/dashboard/components/ExpiredQuotes.tsx
src/pages/dashboard/components/PastDueInvoices.tsx
src/pages/dashboard/components/RecentPayments.tsx
src/pages/dashboard/components/UpcomingInvoices.tsx
src/pages/dashboard/components/UpcomingQuotes.tsx
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
src/pages/expenses/common/components/AddToInvoiceAction.tsx
src/pages/invoices/common/queries.ts
src/pages/invoices/index/Invoices.tsx
src/pages/payments/index/Payments.tsx
src/pages/projects/common/hooks.tsx
src/pages/projects/common/hooks/useCombineProjectsTasks.ts
src/pages/projects/index/Projects.tsx
src/pages/projects/show/Show.tsx
src/pages/quotes/index/Quotes.tsx
src/pages/recurring-expenses/index/RecurringExpenses.tsx
src/pages/recurring-invoices/index/RecurringInvoices.tsx
src/pages/settings/schedules/common/components/EmailRecord.tsx

@beganovich @turbo124 The PR includes adjustments to query parameters. For the entities that must have a client during creation, we ensured that list queries have the `filter_deleted_clients` parameter set to true. For the entities where the client is optional, we ensured that the queries contain the `without_deleted_clients` parameter set to true. Let me know your thoughts.

[Cleanup] Adjusting Queries Params

---

src/common/interfaces/user.ts
src/pages/settings/account-management/component/ReferralProgram.tsx
src/pages/settings/users/index/Users.tsx

@beganovich @turbo124 The PR includes the implementation of displaying additional details for "Referrals". Screenshot:
`Note`: We are missing the "referrals" translation keyword from the files, so if you agree, please just add it there.

[Feature] Implementing "Referrals" Column | Users

---

src/pages/projects/common/hooks.tsx
src/pages/projects/show/Show.tsx
src/pages/projects/show/components/ProjectPrivateNotes.tsx
src/pages/projects/show/components/ProjectPublicNotes.tsx
tests/e2e/projects.spec.ts

@beganovich @turbo124 The PR includes adjustments to the project show page, which involve creating public and private notes cards, along with adding an edit button in the navigation bar similar to what we have across entities that have show pages, like Clients. Screenshot:

[Cleanup] Project Show Page Improving | Aligning With Client Show Page && Tests Adjustment

---

src/common/interfaces/bank-accounts.ts
src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx

@beganovich @turbo124 The PR includes adding an additional prop (`institution_id`) to the payload while generating the `one_time_token` for the `Nordigen` reconnection when the upstream is `DISABLED`. Screenshot:

[Cleanup] Nordigen Reconnecting One Time Token Generation

---

src/components/DataTable.tsx
src/pages/clients/show/pages/Payments.tsx
src/pages/payments/index/Payments.tsx

@beganovich @turbo124 The PR includes applying the condition for displaying the "Restore" bulk action on payments only if the payment has a status of "archived", in any other case, it should not be displayed. Screenshot:

[Cleanup] Displaying "Restore" Action For Payments

---

src/pages/settings/invoice-design/pages/general-settings/components/QuoteDetails.tsx
src/pages/settings/tax-rates/Edit.tsx

@beganovich @turbo124 The PR includes adding a new "$quote.project" variable under Invoice Design => Quote Details. Screenshot:

[Feature] Adding New Quote Variable | Invoice Design

---

src/pages/expenses/create/components/AdditionalInfo.tsx
src/pages/expenses/create/components/Details.tsx
src/pages/recurring-expenses/components/AdditionalInfo.tsx
src/pages/recurring-expenses/components/Details.tsx

@beganovich @turbo124 The PR includes adding dismiss functionality for the currency selector on the expense and recurring expense pages, along with minor fixes for the convert currency section logic for both entities. Screenshot:

[Cleanup] Making Currency Selector Dismissable && Fixing Recurring Expense Currency Converter

---

src/pages/clients/common/hooks/useClientColumns.tsx
src/pages/clients/show/components/ClientPrivateNotes.tsx
src/pages/clients/show/components/ClientPublicNotes.tsx
src/pages/credits/common/hooks.tsx
src/pages/expenses/common/hooks.tsx
src/pages/invoices/common/components/InvoiceSlider.tsx
src/pages/invoices/common/hooks/useInvoiceColumns.tsx
src/pages/payments/common/hooks/usePaymentColumns.tsx
src/pages/products/common/hooks.tsx
src/pages/projects/common/hooks.tsx
src/pages/projects/show/components/ProjectPrivateNotes.tsx
src/pages/projects/show/components/ProjectPublicNotes.tsx
src/pages/quotes/common/components/QuoteSlider.tsx
src/pages/quotes/common/hooks.tsx
src/pages/recurring-expenses/common/hooks.tsx
src/pages/recurring-invoices/common/hooks.tsx
src/pages/tasks/common/hooks.tsx
src/pages/transactions/common/hooks/useTransactionColumns.tsx
src/pages/vendors/common/hooks.tsx

@beganovich @turbo124 The PR includes adjustments to the "prose" class across the app for dark mode, addressing issues with colors. Screenshot:

[Cleanup] Adjusting "prose" Class For Dark Mode | Markdowns

---

src/pages/settings/account-management/component/Plan.tsx

@beganovich @turbo124 The PR includes adjusting the label on the `account_management` page for self-hosted users with a paid plan. The label will use the `"licensed"` translation keyword when `account.plan_expires` is not empty, or in other words, when `plan_expires` is populated.
`Note`: We are missing the "licensed" translation keyword from the files. If you agree with this addition, please add it to the files.
Closes #1844

[Bugfix] Label When Self-hosted Plan Is Paid

---

src/components/users/UserSelector.tsx
src/pages/settings/email-settings/EmailSettings.tsx

@beganovich @turbo124 The PR includes the removal of the "New User" option from the User selector on the Email Settings page. Screenshot:
Closes #1857

[Bugfix] Removing "New User" Option From Email Settings Selector

---

src/components/forms/Combobox.tsx
src/components/products/ProductSelector.tsx
src/pages/invoices/common/hooks/useResolveInputField.tsx

@beganovich @turbo124 The PR includes fixes for the 'product_key' property value not changing after modifying text in the product selector. Now, the value of the 'product_key' prop will change on the `onBlur` event after entering new text. Let me know your thoughts.
Closes #1938

[Bugfix] Changing "product_key" After Entering Text In Product Selector

---

src/pages/credits/common/hooks.tsx
src/pages/invoices/common/hooks/useHandleProductChange.ts
src/pages/invoices/common/hooks/useProductColumns.ts
src/pages/invoices/create/hooks/useInvoiceUtilities.ts
src/pages/purchase-orders/edit/hooks/useHandleCreateLineItem.ts
src/pages/quotes/common/hooks.tsx
src/pages/recurring-invoices/common/hooks.tsx

@beganovich @turbo124 The PR includes an improvement in setting the default quantity when creating a line item. Before this change, we had the default quantity set to 0 after creating the line item, but now it is always 1. Let me know your thoughts.
Closes #1843

[Feature] Default Quantity While Creating Line Items

---

src/components/AboutModal.tsx

@beganovich @turbo124 The PR includes hiding the permissions section on the health_check modal when the `is_docker` prop is equal to `true`. Screenshot:
Closes #1869

[Bugfix] Hiding Permissions Section | Health Check

---

src/components/forms/Combobox.tsx
src/components/products/ProductSelector.tsx
src/pages/invoices/common/hooks/useResolveInputField.tsx
tests/e2e/invoices.spec.ts

@beganovich @turbo124 The PR reintroduces the functionality for entering the "product_key" property of a line item by simply typing text into the product selector input field. Once saved, the API will automatically create the product. I implemented a different approach because the previous one caused an issue. Additionally, I created a test that covers all scenarios (`manual selection`, `selection with keyword`, `selection with entered filtering keyword`, and `selection with entering a custom name for the product to allow API creation of the product`). Let me know your thoughts.

[Bugfix] Setting "product_key" Through Combo Input Value && Test Implementation

---

src/pages/settings/gateways/create/components/LimitsAndFees.tsx

@beganovich @turbo124 The PR includes adding optional chaining for places where we potentially have undefined values, using David's screenshot from Jira. Breaking the app when restoring payment should no longer happen. Let me know your thoughts.

[Bugfix] White Screen When Restoring Payment

---

src/pages/settings/task-statuses/Create.tsx
src/pages/settings/task-statuses/Edit.tsx
src/pages/settings/tax-rates/Create.tsx
src/pages/settings/tax-rates/Edit.tsx

@beganovich @turbo124 The PR includes fixes for incorrectly displayed breadcrumbs on the tax rates and task status pages. Screenshot of the bug:

[Bugfix] Breadcrumbs Issue On Tax Rates and Task Statuses Pages | Production Issue

---

src/pages/products/common/hooks/useInvoiceProducts.ts
src/pages/products/common/hooks/usePurchaseOrderProducts.ts

@beganovich @turbo124 The PR includes fixes for two bugs related to creating invoices and purchase orders from Products. The first bug was that custom field values were not applied when created from a product. The second bug involved values other than `product_key` needing to be applied only if the `fill_products` company settings prop is turned on (Flutter app behavior), if not, only `product_key` should be applied. Both of these fixes have been made for both invoices and purchase orders. Let me know your thoughts.
Closes #1870

[Bugfix] Creating Invoices and Purchase Orders From Products

---

src/common/interfaces/invoice-activity.ts
src/pages/invoices/common/components/InvoiceSlider.tsx
src/pages/invoices/edit/components/Activities.tsx

@beganovich @turbo124 The PR includes two fixes. First, we now use the same function for displaying activities on both the invoice edit page and the invoice slider. Second, I've added the resolution of two additional variables that we missed: `payment` and `payment_amount`. Screenshot:

[Bugfix] Displaying Activities On Invoice Edit Page

---

src/components/import/XMLImport.tsx
src/pages/expenses/import/Import.tsx

@beganovich @turbo124 The PR includes the implementation of XML file uploading for expenses. The functionality includes accepting only `.xml` files along with `CHECKING` the length of lines that the file is made of. If the file has only one line, we will display a message in the toaster from the `xml_lines_length` keyword (we are missing this keyword from the files, if you agree, please just add it there). The payload is constructed from the `import_type: expense` and `files as binary type`. There is also functionality for `REMOVING` files after they are uploaded. For the final import of files I used `/api/v1/edocument/upload` POST route. Screenshots:
`Note`: We miss "xml_file" translation keyword, if you would agree, please just add it into files.
Closes: #1904 
Let me know your …

Implemented uploading xml files on expense import page

---

src/common/hooks/money/useFormatMoney.ts
src/pages/settings/localization/components/Settings.tsx

@beganovich @turbo124 The PR includes improving currency format preview by using the currently selected currency. Earlier, USD was the only one used. Screenshot:
Closes #1947

[Bugfix] Matching Currency Format Symbol With Selected Currency

---

src/pages/settings/integrations/api-webhooks/common/hooks/useEvents.ts

@beganovich @turbo124 The PR includes adding a new `ACCEPTED_PURCHASE_ORDER` event for webhooks.
`Note`:  We're missing the "accept_purchase_order" translation keyword from the files, so if you agree, please just add it to the files.

[Feature] New Purchase Order Event

---

src/pages/settings/integrations/api-webhooks/Create.tsx
src/pages/settings/integrations/api-webhooks/Edit.tsx

@beganovich @turbo124 The PR includes replacing the standard select field with a searchable select field for the event_type field in webhooks. Screenshot:

[Cleanup] Implementing Searchable Select Field | Webhooks

---

src/components/expense-categories/ExpenseCategorySelector.tsx

@beganovich @turbo124 The PR includes setting the "per_page" query parameter for the expense category selector to 500. Let me know your thoughts.
Closes #2005

[Cleanup] Adjusting The "per_page" Query Parameter On Expense Category Selector

---

src/pages/invoices/create/hooks/useHandleCreate.ts

@beganovich @turbo124 The PR includes fixes for query invalidation when saving the invoice. We did not have correctly invalidated the /expenses route, so the table was not updating. I have added query invalidation for expenses once the invoice is saved. Let me know your thoughts.

[Bugfix] Invoicing Expense | Query Invalidation

---

src/pages/expenses/common/hooks.tsx

@beganovich @turbo124 The PR includes the implementation of the expense_category filter selector for the expenses table. Screenshot:

[Feature] Implementing Additional Expense Filter Selector

---

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx

@beganovich @turbo124 The PR includes the implementation of a new email_template called "Payment Failed". 
`Note`: We're missing the "payment_failed" translation keyword in the files, so if you agree, please just add it there.

[Feature] New Email Template | Payment Failed

---

src/pages/credits/common/hooks.tsx
src/pages/credits/common/hooks/useDateRangeColumns.ts
src/pages/credits/index/Credits.tsx
src/pages/purchase-orders/common/hooks/useDateRangeColumns.ts
src/pages/purchase-orders/index/PurchaseOrders.tsx
src/pages/quotes/common/hooks/useDateRangeColumns.ts
src/pages/quotes/index/Quotes.tsx

@beganovich @turbo124 The PR includes the implementation of a date range picker for Quotes, Credits, and Purchase Orders. Invoices already have it implemented. Screenshot:

[Feature] Implementing Date Range Picker

---

src/pages/settings/generated-numbers/components/Settings.tsx

@beganovich @turbo124 The PR includes updated logic to set the `reset_counter_date` property to an empty string if `reset_counter_frequency_id` is set to `0 (Never)`. Let me know your thoughts.
Closes #1822

[Bugfix] Reseting "Reset Counter Date"

---

src/components/AboutModal.tsx

@beganovich @turbo124 The PR includes a fix to display the "Force Update" button ONLY if `is_docker` is set to `false`. Let me know your thoughts.
Closes #1891

[Bugfix] Displaying "Force Update" Button

---

src/pages/payments/refund/Refund.tsx

@beganovich @turbo124 The PR includes implementation for displaying an `amount` prop message for payments on the refund page. The path I took to the error message is `errors.invoices[index].amount`. The message will look like this:

[Bugfix] Displaying Validation Error Message | Payments | Refund

---

src/components/AboutModal.tsx

@beganovich @turbo124 The PR includes an adjustment to display a "processing" modal for the `/api/v1/self-update` endpoint when the endpoint is called. This modal will be closed on `ANY` kind of response. If this endpoint succeeds, we will `RELOAD` the whole page. On any error, we will display an error message in the toaster and close this "processing" modal. Screenshot:
`Note`: We are missing both "updating_app" and "upgrade_in_progress" translation keywords from the files. If you agree, please add them there.

[Cleanup] Displaying "Processing" Modal On self-update

---

src/common/hooks/emails/useHandleSend.ts

@beganovich @turbo124 The PR includes changing the toaster messages when emailing entities. Screenshot:

[Cleanup] Changing Toaster Message While Emailing

---

src/pages/tasks/common/helpers/calculate-time.ts

@beganovich @turbo124 The PR includes adding additional checks to avoid NaN values for "Duration" in the tasks table. I was not able to recreate the case from the screenshot, but I've added the checks to eliminate any possibility of getting it. Screenshot:

[Bugfix] Avoiding NaN Values For Task Duration

---

src/pages/credits/create/Create.tsx
src/pages/invoices/create/Create.tsx
src/pages/quotes/create/Create.tsx
src/pages/recurring-invoices/create/Create.tsx

@beganovich @turbo124 The PR includes adding additional logic to prevent applying default taxes from any level if the `is_tax_exempt` is set to TRUE. If this property is set to FALSE, then the taxes will be able to be applied. Let me know your thoughts.
Closes #2040

[Bugfix] Client Tax Exempt Overriding

---

src/components/HelpSidebarIcons.tsx

@beganovich @turbo124 The PR includes the implementation of a Slack icon as a contact link for self-hosted users, for hosted users, it remains the same. Screenshot:

[Cleanup] Slack Icon As Contact Link For Self-Hosted

---

src/common/queries/purchase-orders.ts
src/pages/quotes/common/hooks/useBulkAction.ts

@beganovich @turbo124 The PR includes implementing 3 missing query invalidations. When converting to an Expense from Purchase Orders (invalidation of Expenses query), when converting to Project or Invoice from Quote (invalidation of Project and Expenses query). Let me know your thoughts.

[Bugfix] Implementing 3 Missing Invalidations

---

src/pages/settings/custom-fields/components/Field.tsx

@beganovich @turbo124 The PR includes adjustments to the selection of multi-line text custom fields. From now on, the form of the custom field will NOT be `"label|multi_line_text"` but ONLY the `label`. Let me know your thoughts.

[Bugfix] Selecting Multi Line Text Custom Field

---

src/common/queries/clients.ts
src/components/projects/ProjectSelector.tsx
src/pages/tasks/common/components/TaskDetails.tsx

@beganovich @turbo124 The PR includes polishing the project query and filtering it by `client_id` if a client has been selected, so the user gets only projects from the selected client, along with adding query invalidation when clients are deleted. Let me know your thoughts.
Closes #2060

[Cleanup] Project Query On Tasks

---

src/components/SearchableSelect.tsx

@beganovich @turbo124 The PR includes fixes to prevent the TinyMCE header from overflowing when the language selector is opened on the user details page. Let me know your thoughts.

[Bugfix] Language-Searchable Selector Does Not Overflowing TinyMCE

---

src/pages/projects/common/hooks.tsx
src/pages/projects/common/hooks/useInvoiceProject.tsx

@beganovich @turbo124 The PR includes fixes for not applying project_id to the invoice object when invoicing a project. This should be fixed now, and project_id should be correctly applied to the invoice object. Let me know your thoughts.

[Bugfix] Invoicing Project Does Not Apply Project Id To An Invoice

---

src/components/Assigned.tsx
src/pages/invoices/edit/Edit.tsx
src/pages/tasks/common/hooks.tsx

@beganovich @turbo124 The PR includes the implementation of displaying a project link on the edit invoice page if a `project_id` has been assigned. Screenshot:
Closes #2058

[Cleanup] Displaying Project Link On Invoice Edit Page

---

src/pages/tasks/common/components/TaskDetails.tsx

@beganovich @turbo124 The PR includes changes to disable the client selector instead of hiding it when a project has been selected. Once the project is cleared, the client will also be cleared. Screenshot:

[Cleanup] Changing Behavior For Client Selector | Task Pages

---

src/pages/invoices/Invoice.tsx
src/pages/invoices/edit/components/CommonActions.tsx

@beganovich @turbo124 The PR includes replacement of the "quick actions" section for the invoice edit page. Screenshot:
`Note`: We missed the "quick_actions" translation keyword in the files, so if you agree, please add it to the files.

[Cleanup] Replacing "Quick" Actions Section

---

src/pages/expenses/common/components/AddToInvoiceAction.tsx
src/pages/expenses/common/hooks.tsx
src/pages/expenses/common/hooks/useCustomBulkActions.tsx

@beganovich @turbo124 The PR includes the implementation of the `add_to_invoice` bulk action. This action will be available in the dropdown after selecting expenses in the table if ALL of the selected expenses have the `should_be_invoiced` property set to true and if the `invoice_id` property is not populated yet. Additionally, if the expenses have the `client_id` populated, then the client_id needs to be the same for all of them, or it will be acceptable if none of them have the client_id property populated at all. Screenshot:

[Feature] Implementing Add To Invoice | Expense Bulk Action

---

src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx

@beganovich @turbo124 The PR includes removing the unnecessary condition to display the red triangle with a tooltip only for the Nordigen integration type. Now, it will be displayed for all integration types. Let me know your thoughts.

[Cleanup] Removing Unnecessary Condition From "Disabled Upstream" Tooltip

---

src/components/ConvertCurrency.tsx
src/components/forms/NumberInputField.tsx
src/pages/credits/edit/components/Settings.tsx
src/pages/expenses/create/components/AdditionalInfo.tsx
src/pages/invoices/edit/components/Settings.tsx
src/pages/purchase-orders/edit/components/Settings.tsx
src/pages/quotes/edit/components/Settings.tsx
src/pages/recurring-expenses/components/AdditionalInfo.tsx
src/pages/recurring-invoices/edit/components/Settings.tsx

@beganovich @turbo124 The PR includes an adjustment to the logic under the number input component to accept an unlimited number of decimal places, but only for specified components. In this case, it is adjusted for the `exchange_rate` and `converted_amount` fields in `Payments`, `Expenses`, and `Recurring Expenses`. Decimal precision for the rest of the fields remains the same, aligned with settings. Screenshot:

[Cleanup] Adjusting Number Input Component To Accept Unlimited Number Of Decimal Places

---

src/components/forms/SelectField.tsx
src/pages/clients/edit/components/AdditionalInfo.tsx
src/pages/clients/edit/components/Details.tsx
src/pages/products/common/components/ProductForm.tsx

@beganovich @turbo124 The PR includes transforming simple HTML select fields into newly created selectors that we already use in some places in the app. These also match the style of searchable selectors that we have applied for some properties. As we discussed on Slack, the implementation will be done entity by entity, or I may include two entities in one PR. However, the PRs will not be crowded for sure, to facilitate testing and reviewing. Screenshot:

[Cleanup] Changing Select Fields | Clients && Products

---

src/common/interfaces/vendor.ts
src/pages/vendors/edit/components/Form.tsx

@beganovich @turbo124 The PR includes the implementation of the `is_tax_exempt` vendor field. Screenshot:

[Feature] New Vendor Field

---

src/components/forms/NumberInputField.tsx
src/pages/credits/common/components/CreditDetails.tsx

@beganovich @turbo124 The PR includes fixing the issue with fallback values on number input fields, so instead of an empty string, there should be zero. Let me know your thoughts.

[Bugfix] Fallback Values On Number Input Fields

---

src/pages/expenses/common/hooks.tsx

@beganovich @turbo124 The PR includes fixes for not updating user preferences once the filters have been changed. Let me know your thoughts.

[Bugfix] Expense Filters Not-Updated In Preferences After Removing

---

src/components/ConvertCurrency.tsx
src/components/forms/NumberInputField.tsx
src/pages/clients/edit/components/AdditionalInfo.tsx
src/pages/expenses/create/components/AdditionalInfo.tsx
src/pages/expenses/create/components/Details.tsx
src/pages/invoices/common/hooks/useResolveInputField.tsx
src/pages/payments/apply/Apply.tsx
src/pages/payments/create/Create.tsx
src/pages/payments/refund/Refund.tsx
src/pages/products/common/components/ProductForm.tsx
src/pages/projects/create/Create.tsx
src/pages/projects/edit/Edit.tsx
src/pages/purchase-orders/edit/components/Details.tsx
src/pages/recurring-expenses/components/AdditionalInfo.tsx
src/pages/recurring-expenses/components/Details.tsx
src/pages/recurring-invoices/common/components/IncreasePricesAction.tsx
src/pages/settings/gateways/create/components/LimitsAndFees.tsx
src/pages/settings/payment-terms/Create.tsx
src/pages/settings/payment-terms/edit/Edit.tsx
src/pages/settings/products/ProductSettings.tsx
src/pages/settings/task-settings/TaskSettings.tsx
src/pages/settings/tax-rates/Create.tsx
src/pages/settings/tax-rates/Edit.tsx
src/pages/settings/tax-settings/components/calculate-taxes/components/EditSubRegionModal.tsx
src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
src/pages/settings/user/components/Preferences.tsx
src/pages/tasks/common/components/TaskDetails.tsx
src/pages/transactions/components/TransactionForm.tsx

@beganovich @turbo124 The PR includes fixing an edge case bug of setting default precision when converting numbers where the precision has been disabled (we do not have a specific number, precision is equal to the user's input). Also, I've added a fallback value of an empty string for fields that missed it and disabled precision and separators for fields that do not need them. Screenshot:

[Bugfix] Fixing Edge Case Issue With Precision Of Numbers And Adding Fallback Value

---

src/pages/quotes/common/hooks/useBulkAction.ts
src/pages/quotes/common/hooks/useCustomBulkActions.tsx

@beganovich @turbo124 The PR includes fixes for the name of the bulk action which needs to mark a quote as sent. It was "sent" instead of "mark_sent". Let me know your thoughts.

[Bugfix] Marking Quote Sent Bulk Action Fixes

---

src/pages/settings/custom-fields/invoices/Invoices.tsx

@beganovich @turbo124 The PR includes changes to display "Charge Taxes" toggles only if `enable_tax_rates` is greater than zero (0). Let me know your thoughts.

[Cleanup] Displaying Charge Taxes Toggles

---

src/pages/clients/show/Client.tsx
src/pages/dashboard/Dashboard.tsx

This invalidates the cache for invoices on the dashboard & client pages.

Expand invalidation of invoice was updated

---

src/common/queries/sockets.ts
src/components/Notifications.tsx
src/components/layouts/Default.tsx
src/pages/clients/show/Client.tsx
src/pages/credits/Credit.tsx
src/pages/credits/index/Credits.tsx
src/pages/invoices/index/Invoices.tsx
src/pages/payments/Payment.tsx
src/pages/payments/index/Payments.tsx

Ref. https://github.com/invoiceninja/invoiceninja/pull/10154
This adds visual support for the following events:
- PaymentWasUpdated
-  CreditWasCreated
- CreditWasUpdated
- InvoiceWasViewed
It also invalidates caches on respective pages such as main listings & client pages.

Websockets: Support for new notifications

---

src/common/helpers.ts
src/common/hooks/useDateTime.ts
src/components/Notifications.tsx
src/pages/clients/common/hooks/useResolveDateAndTimeClientFormat.ts
src/pages/credits/edit/components/Activities.tsx
src/pages/credits/edit/components/History.tsx
src/pages/dashboard/hooks/useGenerateActivityElement.tsx
src/pages/invoices/common/components/InvoiceSlider.tsx
src/pages/invoices/edit/components/Activities.tsx
src/pages/invoices/edit/components/History.tsx
src/pages/payments/common/components/PaymentSlider.tsx
src/pages/purchase-orders/edit/components/Activities.tsx
src/pages/purchase-orders/edit/components/History.tsx
src/pages/quotes/common/components/QuoteSlider.tsx
src/pages/quotes/edit/components/Activities.tsx
src/pages/quotes/edit/components/History.tsx
src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
src/pages/recurring-invoices/edit/components/Activities.tsx
src/pages/recurring-invoices/edit/components/History.tsx
src/pages/tasks/common/components/TaskSlider.tsx
src/pages/tasks/kanban/common/hooks.ts

@beganovich @turbo124 The PR includes formatting of times in the app when we display them. Wherever I found a fixed time format, I replaced it with a dynamic one relying on the `military_time` company settings property. Screenshot:
Closes #2142

[Bugfix] Time Formatting

---

src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx

@beganovich @turbo124 The PR includes fixes for the Invoice Design page breaking when configuring group settings. This was occurring due to reading an undefined value for one property. Let me know your thoughts.
Closes #2146

[Bugfix] Group Settings Invoice Design Page Breaks

---

src/pages/settings/gateways/create/Create.tsx
src/pages/settings/gateways/create/components/Credentials.tsx

This removes GoCardless OAuth2 scoping to testing company, making it available for everyone (hosted).

GoCardless: Remove debugging statements

---

src/components/e-invoice/PaymentMeans.tsx

This removes message about non-existing elements for payment means.
Demo:
[Screencast_20241107_125706.webm](https://github.com/user-attachments/assets/7cd54a77-cf34-4d0f-8ea8-2406080c0d48)

E-invoicing: Remove message about payment means

---

src/pages/settings/gateways/create/components/LimitsAndFees.tsx
src/pages/settings/gateways/create/components/Settings.tsx
src/pages/settings/gateways/create/hooks/useResolveGatewayTypeTranslation.ts

@beganovich @turbo124 The PR adds helper text for gateways in the "Settings" tab. The pattern for helper text is `gatewayName_stripe_help`. Screenshot:

[Cleanup] Adding Helper Text For Gateways

---

src/pages/settings/gateways/create/components/Settings.tsx

@beganovich @turbo124 The PR changes the translation from "capture_card" to "tokenize" and adds helper text. Screenshot:

[Cleanup] Changing Translation To "Tokenize"

---

src/pages/credits/edit/components/Documents.tsx
src/pages/invoices/edit/components/Documents.tsx
src/pages/purchase-orders/edit/components/Documents.tsx
src/pages/quotes/edit/components/Documents.tsx
src/pages/recurring-invoices/edit/components/Documents.tsx

@beganovich @turbo124 The PR imports the `useLocation` hook from `react-router-dom` package instead of using the default `location` class previously used in "Documents" components, to avoid unexpected behavior. Let me know your thoughts.

[Cleanup] Importing "location" From react-router-dom Pacakge

---

src/pages/settings/e-invoice/EInvoice.tsx

@beganovich @turbo124 The PR includes adjusting the e-invoice page to hide the e-invoice card (which contains the e-invoice type selector) once PEPPOL is configured/enabled. So basically the card will BE displayed when the `legal_entity_id` is an empty string. Let me know your thoughts.

[Cleanup] Hiding E-Invoice Card When PEPPOL Is Enabled

---

src/pages/settings/gateways/create/components/Settings.tsx

@beganovich @turbo124 The PR includes an adjustment to make the helper text visible only for the 'Stripe' gateway and not for any others. Screenshots:

[Bugfix] Making Helper Text Visible Only For Stripe

---

src/components/e-invoice/PaymentMeans.tsx
src/pages/settings/e-invoice/EInvoice.tsx

@beganovich @turbo124 The PR includes adjusting the logic so the 'Payment Means' form is available for all e-invoice types with ONLY one criterion: `enable_e_invoice` must be turned on. Screenshot:

[Cleanup] Making Payment Means Form Available For All E-Invoice Types

---

src/pages/invoices/common/helpers/open-client-portal.ts

@beganovich @turbo124 The PR adds functionality to include the client_hash parameter when opening Client Portal links. Let me know your thoughts.

[Bugfix] Adjusting Client Portal Link

---

src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx

This hides current country from being added in additional tax configurations.

E-invoicing: Hide current country

---

src/pages/invoices/common/hooks/useInvoiceColumns.tsx

@beganovich @turbo124 The PR removes the C2C action from the invoice "Number" column. Screenshot:

[Cleanup] Removing C2C Action For Invoice "Number" Column

---

src/pages/payments/Payment.tsx
src/pages/payments/edit/PaymentOverviewInvoice.tsx

@beganovich @turbo124 The PR adjusts labels and icons on the Payment Overview page to maintain consistency with the rest of the app. Screenshot:

[Cleanup] Adjusting Icons For Payment Overview Page

---

src/components/banners/EInvoiceCredits.tsx

This refactors redirect from low credits to popup:
View settings now takes us to einvoicing settings.

E-invoicing: Add banner for low credits

---

src/components/forms/SelectField.tsx
src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx

@beganovich @turbo124 The PR adds missing templates to the dropdown: "Partial Payment", "Credit", and "Purchase Order". 
Closes #2195 

[Cleanup] Adding Missing Templates In Selection Dropdown

---

src/common/hooks/useCompanyTimeZone.ts
src/common/hooks/useDateTime.ts
src/common/hooks/useGetTimezone.ts
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
src/pages/recurring-invoices/common/hooks.tsx

@beganovich @turbo124 The PR includes formatting the `next_send_datetime` property for Recurring Invoices in three locations (all that I found):
- Dashboard Recurring Invoices table
- Recurring Invoices slider
- Recurring Invoices main table

[Cleanup] Formatting next_send_datetime Property By Timezone | Recurring Invoices

---

src/common/interfaces/invoice.ts
src/pages/invoices/edit/components/EInvoice.tsx

@beganovich @turbo124 The PR includes the implementation of a "Backup" card on the "E-Invoice" tab. Screenshots:
`Note`: We are missing the "guid" and "retry" translation keywords, so please add them to the files if you agree.

[Feature] Implementing Backup Section On E-Invoice Tab | Invoice Edit Page

---

src/components/CopyToClipboard.tsx

@beganovich @turbo124 The PR adds "Eye Icon Functionality" for unsecure context if the values should be secure to allow users to view hidden values. Screenshots:
Closes #2236 

[Bugfix] Implementing "Eye Icon Functionality" For Unsecure Context

---

src/pages/invoices/Invoice.tsx

@beganovich @turbo124 The PR adds an additional check when disabling the validation entity query. Since we added a check for enabling the E-Invoice tab if `company.tax_data.acts_as_sender `is turned on, it doesn't make sense to trigger the validation query if the tab is not visible. Therefore, we are adding the same check for triggering the query as we use for hiding/displaying the E-Invoice tab. Let me know your thoughts.

[Cleanup] Additional Check When Disabling Validation Entity Query

---

src/pages/settings/invoice-design/InvoiceDesign.tsx

@beganovich @turbo124 The PR includes updating the payload for the `/api/v1/designs/set/default` endpoint by adding `settings_level` and `client_id/group_settings_id` properties. Let me know your thoughts.

[Cleanup] Updating Payload For Designs Default Endpoint

---

src/pages/expenses/common/components/AddToInvoiceAction.tsx
src/pages/expenses/common/useInvoiceExpense.ts
src/pages/projects/common/hooks/useInvoiceProject.tsx

@beganovich @turbo124 The PR adds missing mappings of custom fields when converting or adding different entities to an invoice. The fixed cases include: adding an expense to an invoice, invoicing an expense, and invoicing a project. 
Closes #2246 

[Bugfix] Missing Mapping Of Custom Fields When Converting Or Adding To Invoice

---

src/pages/projects/show/Show.tsx

@beganovich @turbo124 The PR includes changing the "tasks" translation keyword to "active_tasks" on the Project show page. Screenshot:

[Cleanup] Changing Translation Keyword For Counting Tasks

---

src/pages/settings/gateways/create/Create.tsx

@beganovich @turbo124 The PR includes reordering of gateway cards on the gateway creation page. The GoCardless gateway card has been moved to the third position. Screenshot:

[Cleanup] Reordering Cards On Gateway Creation Page

---

src/pages/dashboard/components/Search.tsx

@beganovich @turbo124 The PR includes fixes for "Enter" and arrow key events (Up/Down). The issue was caused by conflicting events in the Search modal.
Closes #2281 

[Bugfix] Creating/Remvoing KeyDown Events For Search Modal

---

src/common/constants/payment-type.ts
src/common/enums/payment-type.ts

@beganovich @turbo124 The PR adds a few missing payment type translations. Let me know your thoughts.

[Cleanup] Adding Missing Payment Type Translations

---

src/pages/transactions/components/ListBox.tsx
src/pages/transactions/components/TransactionMatchDetails.tsx

@beganovich @turbo124 The PR includes the implementation of a checkbox for selecting all expenses with one click in the transaction slider. Screenshot:
Closes #2286 

[Feature] Implementing Checkbox For Selecting All Expenses | Transaction Slider

---

src/pages/invoices/common/components/ClientCreate.tsx

@beganovich @turbo124 The PR includes adding a validation message for maximum clients if it is returned from the API under the "Name" client field. Screenshot:

[Bugfix] Adding Maximum Clients Validation Message On Client Create Modal

---

src/components/Notifications.tsx

@beganovich @turbo124 The PR includes a fix for the bell icon color in dark mode. Screenshot:

[Bugfix] Bell Icon Dark Mode Color Issue

---

src/common/hooks/useSumTableColumn.ts

@beganovich @turbo124 The PR adds rounding for numbers in the footer when enabled and a column is selected. Based on the ticket screenshot, the issue occurs when multiple currencies exist in table records and a specific currency can't be identified. Numbers are now rounded using the `number_precision` from Preference settings, defaulting to 2 decimal places if not specified. Let me know your thoughts.

[Bugfix] Number Rounding Issue | Footer Columns

---

src/pages/clients/common/components/PurgeClientAction.tsx

@beganovich @turbo124 The PR adds a warning/confirmation modal when purging a client. Screenshot:
`Note`: This is not plain text in the screenshot. I used the `purge_client_warning` translation keyword to get it. Please let me know if I should change it.

[Cleanup] Purge Client Warning/Confirmation Modal

---

src/components/e-invoice/PaymentMeans.tsx

@beganovich @turbo124 The PR includes fixes for payment means settings not persisting when successfully saved. This was happening because company_users were not being refreshed after the `/api/v1/einvoice/configurations` endpoint succeeded. It now appears to be fixed on my end. Let me know your thoughts.

[Bugfix] Non-Persisting Payment Means Setting | E-Invoice

---

src/pages/settings/bank-accounts/index/BankAccounts.tsx

@beganovich @turbo124 The PR adds a processing toaster to improve UX when triggering the "Refresh" action on bank accounts. Let me know your thoughts.

[Cleanup] Adding Processing Toaster When Triggering "Refresh" Action | Bank Accounts

---

src/pages/invoices/common/hooks/useDownloadPdf.ts
src/pages/invoices/common/hooks/useGeneratePdfUrl.ts
src/pages/invoices/pdf/components/Actions.tsx

@beganovich @turbo124 The PR includes fixes for the invoice PDF page. Previously, when delivery note was turned on, a plain invoice was still being downloaded. The URL has been fixed to generate the correct document type when delivery note is turned on. Let me know your thoughts.

[Bugfix] Fixed Issue Of Downloading Delivery Note

---

src/pages/settings/bank-accounts/common/components/ConnectAccounts.tsx

@beganovich @turbo124 The PR adds descriptive regional coverage text for Yodlee and Nordigen providers in the "Connect Accounts" modal. Screenshot:

[Cleanup] Connect Accounts Modal Improving With Helper Text

---

src/pages/settings/account-management/component/SecuritySettings.tsx

@beganovich @turbo124 The PR removes underscores "_" from session timeout dropdown values, as this appears to be the only potential cause for the session timeout issues that user has reported. There is no other place where this value is set. Let me know your thoughts.

[Bugfix] Removing "Underscore" From Session Timeout Values

---

src/pages/invoices/common/components/InvoiceSlider.tsx
src/pages/invoices/edit/components/EmailHistory.tsx
src/pages/purchase-orders/edit/components/EmailHistory.tsx
src/pages/quotes/common/components/QuoteSlider.tsx
src/pages/quotes/edit/components/EmailHistory.tsx

@beganovich @turbo124 The PR includes changes to empty results translations for email history in Invoices, Quotes, and Purchase Orders. Screenshot:

[Cleanup] Changing "Email History" Translations

---

src/pages/credits/common/hooks.tsx
src/pages/quotes/common/hooks.tsx
src/pages/recurring-invoices/common/hooks.tsx

Implements a fix for hooks on line item updates preventing every line from rerendering inappropriately.
Covers credits, quotes and recurring invoices.
Invoices was already covered.
Purchase Orders uses a different approach with cloneDeep, we will need to assess the best approach and unify the structure of this across all entities.
@beganovich for urgent push to main when reviewed please.

Hot fix for entities with large number of line items

---

src/common/hooks/entities/useQuickCreateActions.ts

@beganovich @turbo124 The PR fixes the subscription link in the "Quick Create" popover from `/subscription/create` to `/subscriptions/create` to prevent navigation to a non-existent page. Let me now your thoughts.

[Bugfix] Fixes For Subscriptions Link In "Quick Create" Popover

---

src/components/layouts/Default.tsx
src/pages/dashboard/components/Search.tsx

This fixes a couple of things:
— Search icon instead of input box on smaller devices
— Upgrade instead of “Unlock Pro” / “Purchase White Label” on smaller devices

Fixes for upgrade button spacing

---

src/common/colors.ts
src/pages/dashboard/components/Search.tsx

@beganovich @turbo124 The PR includes a small change for adjusting the colors of text in the field dedicated to opening the "Search" modal. It did not look as good as I expected in dark mode, so I just made that adjustment. Screenshot:

[Cleanup] Adjusting Colors For Dark Mode | Search

---

src/components/CustomField.tsx
src/pages/settings/invoice-design/pages/general-settings/components/TotalFields.tsx

@beganovich @turbo124 The PR includes fixes for surcharge labels under the "Total Fields" tab. Screenshot:

[Bugfix] Surcharge Custom Label Names

---

src/common/hooks/useNumericFormatter.ts

@beganovich @turbo124 The PR includes fixes for formatting number values based on the entered decimal separator. The issue was actually with the incoming `display_value` property. This property contains "," as a thousand separator and "." as a decimal separator, but the `react-number-format` package that we use for formatting expects only to have a decimal separator, making the thousand separator unnecessary in this case. The problem only occurred for values greater than 1000, as smaller values did not include the thousand separator. Screenshots:
Closes #2388 

[Bugfix] Formatting Number Values When Previewing Reports

---

src/common/hooks/useAuthenticated.ts
src/common/hooks/useDataTablePreferences.ts
src/common/hooks/usePreferences.tsx
src/common/hooks/useRefreshCompanyUsers.ts
src/components/AboutModal.tsx
src/components/CommonActionsPreferenceModal.tsx
src/components/DataTableColumnsPicker.tsx
src/components/DataTableFooterColumnsPicker.tsx
src/components/HelpSidebarIcons.tsx
src/components/banners/VerifyPhone.tsx
src/components/import/ImportTemplate.tsx
src/components/import/ImportTemplateModal.tsx
src/pages/authentication/Register.tsx
src/pages/authentication/common/hooks.ts
src/pages/authentication/components/SignInProviders.tsx
src/pages/clients/common/components/MergeClientModal.tsx
src/pages/settings/common/hooks/useHandleCompanySave.tsx
src/pages/settings/company/components/DeleteLogo.tsx
src/pages/settings/company/components/Logo.tsx
src/pages/settings/company/create/CompanyCreate.tsx
src/pages/settings/company/edit/CompanyEdit.tsx
src/pages/settings/e-invoice/EInvoice.tsx
src/pages/settings/integrations/analytics/Analytics.tsx
src/pages/settings/user/UserDetails.tsx
src/pages/settings/user/common/components/SelectProviderModal.tsx
src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
src/pages/settings/user/common/hooks/useUpdateCompanyUser.ts
src/pages/vendors/create/Create.tsx

@beganovich @turbo124 The PR includes fixes for updating the company/user changes object in Redux after the endpoint for updating company_users or companies has been successful. While working on redesigning the main navigation bar, I noticed that two hooks work incorrectly and make unnecessary updates. I updated them, but I then noticed an issue where columns on tables don't update without refreshing the page. Therefore, I went through ALL cases when company_users or companies are updated to ensure that the changes Redux object is kept up to date. Let me know your thoughts.

[Bugfix] Updating Company/User Changes In Redux

---

src/components/layouts/Default.tsx

@beganovich @turbo124 The PR includes replacing the positions of 'Reports' and 'Transactions' in the main navbar. Screenshot:

[Cleanup] Replacing "Reports" And "Transactions" In Main Navbar

---

src/components/Notifications.tsx

@beganovich @turbo124 The PR includes a quick fix and checks if the `displayLabel` notification object exists. If it exists, the notification will be displayed, otherwise, it will not be. Let me know your thoughts.

[Bugfix] Reading Notifications From Old Implementation

---

index.html

@beganovich @turbo124 The PR includes fixes for the URL of apple-touch-icon in the header of the html. Let me know your thoughts.

[Bugfix] Apple Touch Icon URL

---

src/common/interfaces/statics.ts

The PR removes redundancy. Applying the same principles already used for `Country` and `Currency` typed fields in the `Statics`

Simplify Statics interface

---

src/pages/clients/routes.tsx
src/pages/clients/show/hooks/useTabs.tsx

@beganovich @turbo124 The PR includes fixes for the "Documents" tab URL issue on Client show page. After making tabs for the edit page, the documents tab on client show page had exactly the same URL as the edit page documents tab, so clicking on "Documents" tab on client show page was actually navigating to the edit page tab. To resolve this, I made a distinction between them, so now the URL for documents on client show page is "/documents_overview". Let me know your thoughts.

[Bugfix] Client Show Page "Documents" Tab URL

---

src/pages/recurring-invoices/common/components/UpdatePricesAction.tsx

@beganovich @turbo124 The PR includes fixes for the "Update Prices" modal text color issue. Screenshot:

[Bugfix] "Update Prices" Modal Text Color Issue

---

src/components/datatables/Actions.tsx

@beganovich @turbo124 The PR includes fixes for styling the status dropdown for tables in dark mode. Screenshot:

[Bugfix] Status Dropdown Dark Mode Fixes

---

src/components/icons/RadioChecked.tsx
src/components/icons/RadioUnchecked.tsx
src/pages/expenses/common/components/ExpenseCategory.tsx
src/pages/tasks/common/components/TaskStatus.tsx
src/pages/tasks/common/components/TaskStatusesDropdown.tsx

@beganovich @turbo124 The PR includes redesigning status change popovers for expenses and tasks using the Figma design. Screenshot:

[Cleanup] Table Status Popovers Redesigning

---

src/App.tsx
src/common/colors.ts
src/common/hooks/usePreferences.tsx
src/common/hooks/useResizeColumn.ts
src/components/DataTable.tsx
src/components/HelpWidget.tsx
src/components/datatables/Actions.tsx
src/components/datatables/DateRangePicker.tsx
src/components/dropdown/Dropdown.tsx
src/components/forms/Button.tsx
src/components/forms/InputField.tsx
src/components/forms/SelectField.tsx
src/components/icons/ChevronUp.tsx
src/components/import/ImportButton.tsx
src/components/layouts/Default.tsx
src/components/tables/Pagination.tsx
src/components/tables/Table.tsx
src/components/tables/Th.tsx
src/components/tables/Thead.tsx
src/pages/dashboard/components/Activity.tsx
src/pages/dashboard/components/ExpiredQuotes.tsx
src/pages/dashboard/components/PastDueInvoices.tsx
src/pages/dashboard/components/RecentPayments.tsx
src/pages/dashboard/components/Totals.tsx
src/pages/dashboard/components/UpcomingInvoices.tsx
src/pages/dashboard/components/UpcomingQuotes.tsx
src/pages/dashboard/components/UpcomingRecurringInvoices.tsx
src/pages/dashboard/hooks/useGenerateActivityElement.tsx
src/pages/settings/tax-settings/components/calculate-taxes/components/EURegions.tsx
src/pages/settings/tax-settings/components/calculate-taxes/components/UKRegions.tsx

@beganovich @turbo124 The PR includes final styling of the data table along with adjusting the border color on the dashboard to match Figma. Screenshots:

[Cleanup] General Table Styling Adjustment

---

src/components/Modal.tsx
src/components/forms/ColorPicker.tsx

@beganovich @turbo124 The PR includes color selector redesign per Figma's design. Screenshot:
`Note`: We are missing the "select_color" translation keyword from files, so if you would agree, please just add it there.

[Cleanup] Color Selector Redesign

---

src/components/TabGroup.tsx
src/components/forms/MarkdownEditor.tsx
src/pages/invoices/common/components/AddUninvoicedItemsButton.tsx
src/pages/invoices/common/components/InvoiceFooter.tsx
src/pages/invoices/common/components/InvoiceSlider.tsx
src/pages/payments/common/components/PaymentSlider.tsx
src/pages/quotes/common/components/QuoteSlider.tsx
src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
src/pages/tasks/common/components/TaskSlider.tsx

@beganovich @turbo124 The PR includes Invoice Footer section redesign along with fixes for dark/light mode for markdown editors in general. Screenshot:

[Cleanup] Invoice Footer Section Redesign && Markdown Editor Dark/Light Mode Fixes

---

src/pages/invoices/edit/components/Documents.tsx

@beganovich @turbo124 The PR includes a redesign of the "Documents" tab for invoice according to the Figma design. Screenshot:

[Cleanup] Documents Tab Redesign | Invoices

---

src/components/forms/Toggle.tsx
src/components/payment-types/PaymentTypeSelector.tsx
src/components/resizable-panels/PanelResizeHandle.tsx
src/pages/expenses/Expense.tsx
src/pages/expenses/common/components/DocumentPreview.tsx
src/pages/expenses/create/components/AdditionalInfo.tsx
src/pages/expenses/create/components/Details.tsx
src/pages/expenses/create/components/Notes.tsx
src/pages/expenses/create/components/Taxes.tsx
src/pages/expenses/documents/Documents.tsx

@beganovich @turbo124 The PR includes redesign of Expense pages according to Figma design. Screenshot:

[Cleanup] Expense Pages Redesign

---

src/pages/reports/common/components/SortableColumns.tsx
src/pages/reports/index/Reports.tsx

@beganovich @turbo124 The PR includes fixing an issue with horizontal scroll when customized column cards are displayed. Screenshot of issue:

[Bugfix] Horizontal Scroll | Reports | Customized Columns

---

src/common/hooks/usePaidOrSelfhost.ts

pushes the expiry date to the end of day to ensure plan are not prematurely marked as expired.

Plan expiry update

---

src/components/PropertyCheckbox.tsx
src/components/layouts/Settings.tsx
src/pages/settings/bank-accounts/common/components/ConnectAccounts.tsx
src/pages/settings/bank-accounts/components/Details.tsx
src/pages/settings/bank-accounts/components/transaction-rules/components/RuleModal.tsx
src/pages/settings/bank-accounts/components/transaction-rules/components/TransactionRuleForm.tsx
src/pages/settings/bank-accounts/create/Create.tsx
src/pages/settings/bank-accounts/edit/Edit.tsx
src/pages/settings/group-settings/create/Create.tsx
src/pages/settings/group-settings/edit/Edit.tsx
src/pages/settings/group-settings/edit/components/Clients.tsx
src/pages/settings/subscriptions/common/components/MultipleProductSelector.tsx
src/pages/settings/subscriptions/common/components/Overview.tsx
src/pages/settings/subscriptions/common/components/Settings.tsx
src/pages/settings/subscriptions/common/components/Steps.tsx
src/pages/settings/subscriptions/common/components/Webhook.tsx
src/pages/settings/subscriptions/create/Create.tsx
src/pages/settings/subscriptions/edit/Edit.tsx

@beganovich @turbo124 This PR redesigns Credit Cards & Banks, Group Settings, and Payment Links according to the Figma design. Screenshot:

[Cleanup] Redesign Credit Cards & Banks | Group Settings | Payment Links

---

src/components/e-invoice/PaymentMeans.tsx
src/pages/settings/e-invoice/EInvoice.tsx
src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
src/pages/settings/e-invoice/peppol/Preferences.tsx
src/pages/settings/email-settings/EmailSettings.tsx
src/pages/settings/email-settings/common/components/SMTPMailDriver.tsx
src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx

@beganovich @turbo124 The PR includes a redesign of E-Invoicing, Email Settings, and Templates & Reminders pages according to the Figma design. Screenshots:

[Cleanup] Redesign E-Invoicing | Email Settings | Templates & Reminders

---

src/components/Badge.tsx
src/pages/settings/user/components/StatusColorTheme.tsx

@beganovich @turbo124 The PR includes fixes for the "Status Color Scheme". It ensures that the "Clear All" button now sets `status_color_scheme` to light, and the "Light" theme matches the designer's specifications in Figma. I matched those colors and used color calculations to ensure proper text contrast across all other themes except "Light". 
Closes #2577 

[Bugfix] Status Color Scheme

---

src/common/queries/invoices.ts
src/components/DataTable.tsx
src/pages/clients/show/pages/Invoices.tsx
src/pages/invoices/common/components/DeleteInvoicesConfirmationModal.tsx
src/pages/invoices/index/Invoices.tsx
src/pages/recurring-invoices/common/components/ConfirmActionModal.tsx

@beganovich @turbo124 The PR includes the implementation of a confirmation modal when bulk deleting invoices. Screenshot:
`Note`: If you agree with the translation used, please just add the missing "delete_invoices_confirmation" translation keyword to the files.
Closes #2467 

[Cleanup] Implementing Confirmation Modal When Bulk Deleting Invoices

---

src/components/forms/Checkbox.tsx
src/components/forms/Toggle.tsx
src/pages/settings/users/edit/components/Permissions.tsx

@beganovich @turbo124 The PR includes few UX improvements when selecting permissions:
- If the "Admin" permission is selected, all other permissions will appear "checked" and "disabled" without the possibility of unchecking them until the "Admin" permission is unchecked.
- If the "Admin" permission is checked, all permissions will be removed from the array, and only the `is_admin` boolean value will be set to true. The UI will be correctly updated.
- If 13/14 permissions from one type (for example, "View") are checked, and then the last one is checked, it will remove all of them from the array, and only the "view_all" permission will be added along with a proper UI update.

[Cleanup] UX Improvement When Selecting Permissions

---

src/pages/reports/index/Reports.tsx

@beganovich @turbo124 The PR includes reverting to displaying the value that the API returns for Report Previews until we find the best solution for formatting. Screenshot:

[Bugfix] Number Display Value | Report Previews

---

src/pages/payments/common/components/PaymentSlider.tsx

@beganovich @turbo124 The PR includes fixes for formatting money on the payment slider for invoices and credit cards, where currency_id and country_id from the invoice and credit clients are used instead of those from the payment.
Closes #2633 

[Bugfix] Invoices/Credits Money Formatting On Payment Slider

---

src/pages/projects/edit/Edit.tsx

@beganovich @turbo124 The PR includes fixes for removing the `readOnly` prop from the user selector on the project edit page. Screenshot:

[Bugfix] User Selector Read Only | Projects

---

src/pages/clients/show/pages/HistoryAndActivities.tsx

@beganovich @turbo124 The PR includes adding filtering to the "Email History" card/section on the Client overview page. Currently, I implemented React filtering without calling the API, as the API always returns all emails. To filter emails, I check if the filter is contained in the `subject`, `recipients`, or `entity`, or if a date is entered, I check the dates in the events array to see if it includes any of those dates.
`Note`: I used "search_emails" translation keyword, so if you agree please just add it into files.

[Feature] Filtering In Email History Section

---

src/components/products/ProductSelector.tsx

@beganovich @turbo124 The PR includes adjusting the max width for the product selector. So, if there are long notes, for example, the product selector will be significantly wider than we had it earlier, but if there is no need for that (if there are no long notes), the size will stay as default. Let me know your thoughts.

[Cleanup] Adjusting Max Width For Products Selector

---

src/pages/invoices/common/components/InvoiceSlider.tsx

@beganovich @turbo124 The PR includes fixes for money formatting on the invoice slider for payments. Previously, the details for money formatting were taken from the payment object, but now we use details from the invoice object, and it will match the currency for the entire invoice slider. Screenshot:
Closes #2698 

[Bugfix] Money Formatting Payments | Invoice Slider

---

src/components/DataTable.tsx
src/pages/recurring-invoices/index/RecurringInvoices.tsx

@beganovich @turbo124 The PR includes implementing a range picker for the next send date column using `next_send_between` as a query parameter. Screenshot:

[Feature] Next Send Date Column Range Picker

---

src/components/layouts/Default.tsx
src/pages/documents/pages/users/Users.tsx
src/pages/documents/pages/users/create/Create.tsx
src/pages/documents/pages/users/edit/Edit.tsx

@beganovich @turbo124 The PR includes two fixes: a fix for breadcrumbs for users under documents on all pages, and also, same as we disabled the new_user button on the list users page, I hid it if the client reached the user limit. Let me know your thoughts.

[Bugfix] Documents Breadcrumbs + Hidding Plus Icon For Users

---

src/pages/settings/expense-categories/Edit.tsx

@beganovich @turbo124 The PR includes fixes to prevent triggering the PUT method for expense categories. Let me know your thoughts.

[Bugfix] Edit Expense Category Fixes

---

src/components/lexical/plugins/ToolbarPlugin/htmlCode.tsx
src/components/lexical/plugins/ToolbarPlugin/index.tsx

@beganovich @turbo124 This PR adds HTML code editing functionality to the Lexical editor. Screenshot:

[Feature] Adding HTML Code Option For Lexical Editor
