src/pages/invoices/clone/Clone.tsx, src/pages/payments/create/Create.tsx, src/pages/payments/edit/Edit.tsx
=> Revert "Ensure cloned invoice has number removed."

src/pages/products/edit/Edit.tsx, src/pages/settings/account-management/AccountManagement.tsx, src/pages/settings/common/hooks/useHandleCompanySave.ts, src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/expense-settings/ExpenseSettings.tsx, src/pages/settings/localization/Localization.tsx, src/pages/settings/products/ProductSettings.tsx, src/pages/settings/task-settings/TaskSettings.tsx, src/pages/settings/tax-settings/TaxSettings.tsx, src/pages/settings/workflow-settings/WorkflowSettings.tsx
This fixes common issues with showing validation messages.
=> Fixes for validation messages

src/components/DocumentsTable.tsx, src/components/dropdown/DropdownElement.tsx, src/pages/products/documents/Documents.tsx, src/pages/settings/company/documents/Documents.tsx, src/pages/settings/company/documents/components/Table.tsx, src/pages/settings/company/documents/components/Upload.tsx, src/pages/settings/company/documents/components/index.ts
Changes:
- Fixes for product documents table
- Fixes for product upload widget
=> Product documents

src/common/helpers.ts, src/common/interfaces/activity-record.ts, src/components/DataTable.tsx, src/components/DropdownDateRangePicker.tsx, src/components/cards/Card.tsx, src/components/cards/NonClickableElement.tsx, src/components/dropdown/DropdownElement.tsx, src/components/tables/Pagination.tsx, src/components/totals/Activity.tsx, src/components/totals/PastDueInvoices.tsx, src/components/totals/RecentPayments.tsx, src/components/totals/Totals.tsx, src/components/totals/UpcomingInvoices.tsx, src/pages/dashboard/Dashboard.tsx
Upcoming invoices / Overdue invoices
Fixes for parameter replacements in translations
=> Dashboard enhancements

src/components/CompanySwitcher.tsx, src/components/layouts/Default.tsx, src/components/layouts/components/DesktopSidebar.tsx, src/components/layouts/components/MobileSidebar.tsx, src/components/layouts/components/SidebarItem.tsx
Changes:
- Change color of company switcher to white
- Unify styles for mobile/sidebar menu items
- Extracting into components for better structure
=> Refactor sidebar appearance

src/common/hooks/useCurrentCompanyDateFormats.ts, src/components/CompanySwitcher.tsx, src/components/layouts/Default.tsx, src/components/layouts/components/DesktopSidebar.tsx, src/components/layouts/components/MobileSidebar.tsx, src/components/layouts/components/SidebarItem.tsx, src/components/totals/Chart.tsx, src/components/totals/Totals.tsx
Changes:
- Using official application formatter for money
- Changed colors of chart legend
- Dates on charts are now formatted respecting company formats
=> Improvements on dashboard charts

src/common/hooks/useCurrentCompanyDateFormats.ts, src/components/totals/Chart.tsx, src/components/totals/Totals.tsx
Changes
- Using the official application formatter for 
- Changed colors of the chart 
- Dates on charts are now formatted respecting company formats
=> Dashboard charts improvements

src/components/SwitchToFlutter.tsx, src/components/icons/Flutter.tsx, src/components/icons/index.ts, src/components/layouts/Default.tsx, src/components/layouts/components/DesktopSidebar.tsx, src/pages/dashboard/Dashboard.tsx
This will let us switch to the Flutter app using UI.
=> App switcher

src/components/SwitchToFlutter.tsx, src/pages/dashboard/Dashboard.tsx
This lets us switch to the Flutter application.
=> Flutter switching

src/common/queries/invoices.ts, src/pages/credits/clone/CloneInvoiceToCredit.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/invoices/edit/components/Actions.tsx, src/pages/invoices/edit/hooks/useHandleCancel.ts, src/pages/invoices/index/Invoices.tsx, src/pages/invoices/routes.tsx, src/pages/quotes/clone/CloneFromInvoice.tsx, src/pages/recurring-invoices/clone/CloneInvoiceToRecurringInvoice.tsx
This provides few more actions around invoices to match the Flutter experience.
=> Match invoice actions with the Flutter app

src/common/hooks/useCountries.ts, src/common/hooks/useCurrencies.ts, src/common/hooks/useCurrentCompanyDateFormats.ts, src/common/hooks/useLanguages.ts, src/common/interfaces/company.interface.ts, src/common/interfaces/statics.ts, src/common/queries/statics.ts, src/components/ConvertCurrency.tsx, src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/payments/common/helpers/resolve-exchange-rate.ts, src/pages/settings/company/components/Address.tsx, src/pages/settings/company/components/Defaults.tsx, src/pages/settings/company/components/Details.tsx, src/pages/settings/gateways/common/hooks/useGateways.ts, src/pages/settings/localization/components/Settings.tsx, src/pages/vendors/components/AdditionalInfo.tsx, src/pages/vendors/components/Address.tsx
This fixes typehinting on statics query using generics.
=> Improve typehinting on statics query

src/common/interfaces/statics.ts, src/components/layouts/Settings.tsx, src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx, src/pages/settings/templates-and-reminders/common/components/Variable.tsx
This implements templates and reminders in the app.
=> Settings: Templates and reminders

src/common/hooks/useCurrentCompany.ts, src/common/interfaces/project.ts, src/common/queries/projects.ts, src/common/routes.tsx, src/components/layouts/Default.tsx, src/pages/clients/edit/Edit.tsx, src/pages/projects/Project.tsx, src/pages/projects/clone/Clone.tsx, src/pages/projects/common/hooks/useBulkAction.ts, src/pages/projects/create/Create.tsx, src/pages/projects/documents/Documents.tsx, src/pages/projects/edit/Edit.tsx, src/pages/projects/index.ts, src/pages/projects/index/Projects.tsx, src/pages/projects/routes.tsx, src/pages/recurring-invoices/index.ts
This implements projects module in the app.
Tasks:
=> Projects module

src/components/clients/ClientSelector.tsx, src/components/forms/DebouncedCombobox.tsx, src/pages/invoices/common/components/ClientCreate.tsx, src/pages/invoices/common/components/ClientSelector.tsx
This improves client selector component to align with rest of the UI.
Instead of having "New client" button separated from the select box itself, now it's inside. As a helper, dropdown is initially showed when default value is not present.
=> Client selector improvements

src/components/TabGroup.tsx, src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/clients/edit/components/Address.tsx, src/pages/credits/common/components/CreditFooter.tsx, src/pages/invoices/clone/Clone.tsx, src/pages/invoices/common/components/InvoiceFooter.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/quotes/common/components/QuoteFooter.tsx, src/pages/recurring-invoices/common/components/InvoiceFooter.tsx
This refactors tab to prevent re-rendering of the children components.
=> Refactor tabs 

src/pages/credits/create/Create.tsx
=> Fixes for credits

src/pages/credits/clone/Clone.tsx, src/pages/credits/clone/CloneInvoiceToCredit.tsx, src/pages/credits/create/Create.tsx, src/pages/credits/edit/Edit.tsx, src/pages/expenses/clone/Clone.tsx, src/pages/expenses/create/Create.tsx, src/pages/expenses/edit/Edit.tsx, src/pages/invoices/clone/Clone.tsx, src/pages/invoices/common/components/ClientSelector.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/quotes/clone/Clone.tsx, src/pages/quotes/clone/CloneFromInvoice.tsx, src/pages/quotes/clone/CloneToInvoice.tsx, src/pages/quotes/create/Create.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/recurring-invoices/clone/Clone.tsx, src/pages/recurring-invoices/clone/CloneInvoiceToRecurringInvoice.tsx, src/pages/recurring-invoices/create/Create.tsx, src/pages/recurring-invoices/edit/Edit.tsx
This improves non-blocking UI, which reduces random page renders. Instead we show loading spinners.
=> Improvements regarding non-blocking UI

src/common/interfaces/product.ts, src/pages/clients/show/pages/Credits.tsx, src/pages/clients/show/pages/Projects.tsx, src/pages/clients/show/pages/RecurringInvoices.tsx, src/pages/credits/index/Credits.tsx, src/pages/dashboard/components/PastDueInvoices.tsx, src/pages/dashboard/components/RecentPayments.tsx, src/pages/dashboard/components/UpcomingInvoices.tsx, src/pages/invoices/index/Invoices.tsx, src/pages/payments/index/Payments.tsx, src/pages/products/index/Products.tsx, src/pages/projects/index/Projects.tsx, src/pages/quotes/index/Quotes.tsx, src/pages/recurring-expenses/index/RecurringExpenses.tsx, src/pages/recurring-invoices/index/RecurringInvoices.tsx, src/pages/settings/expense-categories/ExpenseCategories.tsx, src/pages/settings/gateways/index/Gateways.tsx, src/pages/settings/task-statuses/TaskStatuses.tsx, src/pages/settings/users/index/Users.tsx, src/pages/tasks/index/Tasks.tsx, src/pages/vendors/index/Vendors.tsx
Improve datatable typehints with generics.
=> Typehinting datatables

src/common/interfaces/activity-record.ts, src/components/DataTable.tsx, src/components/datatables/Actions.tsx, src/components/import/UploadImport.tsx, src/pages/clients/import/Import.tsx, src/pages/clients/index/Clients.tsx, src/pages/clients/routes.tsx, src/pages/clients/show/components/Contacts.tsx, src/pages/clients/show/pages/RecurringInvoices.tsx, src/pages/dashboard/components/RecentPayments.tsx, src/pages/dashboard/hooks/useGenerateActivityElement.tsx, src/pages/products/index/Products.tsx
=> Import clients

src/common/helpers/clients/client-resolver.ts, src/common/helpers/currencies/currency-resolver.ts, src/common/hooks/useAuthenticated.ts, src/common/hooks/useGetCurrencySeparators.ts, src/common/queries/invoices.ts, src/components/DataTable.tsx, src/components/emails/Contact.tsx, src/components/forms/DebouncedCombobox.tsx, src/pages/credits/common/queries.ts, src/pages/credits/create/Create.tsx, src/pages/credits/edit/Edit.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/quotes/common/hooks/useBulkAction.ts, src/pages/quotes/common/queries.ts, src/pages/quotes/create/Create.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/recurring-invoices/common/queries.ts, src/pages/recurring-invoices/create/Create.tsx, src/pages/recurring-invoices/edit/Edit.tsx, src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/tasks/common/hooks/useBulk.ts, src/pages/vendors/create/Create.tsx
This implements few caching elements when it comes to query-heavy pages (invoices, recurring invoices, quotes, credits).
=> Optimization of the queries

src/common/helpers/toast/toast.ts, src/components/CopyToClipboard.tsx, src/pages/settings/client-portal/components/Settings.tsx
This implements copy to clipboard functionality.
Usage:
```tsx
<CopyToClipboard text="Some text" />
```
=> Copy to clipboard

src/pages/authentication/Logout.tsx
This removes API call to `/logout` when logging out from the React app.
=> Logout action

src/common/queries/payments.ts, src/pages/payments/documents/Documents.tsx
Fixes issue after uploading documents for the payment.
=> Payment documents cache

src/pages/dashboard/components/Chart.tsx
Fixing Y-axis cutting data for charts.
=> Fixes for charts cutting off on Y-axis

src/common/queries/users.ts, src/pages/settings/users/edit/Edit.tsx
Fixes for accessing user edit page (requiring password).
=> User management fixes

src/pages/clients/common/components/CustomResourcefulActions.tsx, src/pages/clients/index/Clients.tsx, src/pages/clients/routes.tsx, src/pages/clients/statement/Statement.tsx
This implements statements for the clients resource.
=> Statements

src/common/guards/Guard.tsx, src/common/guards/guards/enabled.ts, src/components/layouts/Default.tsx, src/pages/credits/routes.tsx, src/pages/expenses/routes.tsx, src/pages/invoices/routes.tsx, src/pages/projects/routes.tsx, src/pages/quotes/routes.tsx, src/pages/recurring-invoices/routes.tsx, src/pages/settings/account-management/component/EnabledModules.tsx, src/pages/tasks/routes.tsx, src/pages/vendors/routes.tsx
This implements enabling/disabling modules app-wide using settings.
=> Enabling moduels app-wide 

src/pages/settings/email-settings/EmailSettings.tsx
This implements markdown editor for email signatures.
=> Markdown email signature

src/pages/clients/common/hooks/usePurgeClient.ts
This fixes (and lets us) purge the client.
=> Fixes for purging the client

package-lock.json, package.json, src/components/dropdown/Dropdown.tsx
This auto focuses dropdowns once outside element is clicked.
=> Improving dropdowns

src/components/clients/ClientSelector.tsx, src/components/forms/DebouncedCombobox.tsx, src/pages/credits/create/Create.tsx, src/pages/invoices/create/Create.tsx, src/pages/quotes/create/Create.tsx
Fixes issue with creating resources from the client page.
=> Creating resources from the clients page

src/pages/clients/show/components/Address.tsx, src/pages/clients/show/components/Details.tsx
This improves details card when viewing the client (ref. 399).
=> "Details" box improvement

src/pages/clients/index/Clients.tsx
This fixes and adds missing columns for client's datatable (ref. 392).
=> Improve columns for clients datatable

src/components/DataTable.tsx, src/components/cards/Card.tsx, src/components/tables/Table.tsx, src/pages/dashboard/components/PastDueInvoices.tsx, src/pages/dashboard/components/RecentPayments.tsx, src/pages/dashboard/components/UpcomingInvoices.tsx
This makes all card on the dashboard same height.
=> Standardize card height on the dashboard

src/pages/settings/email-settings/EmailSettings.tsx
This moves section about attaching PDF, documents & UBL to the top of email settings (ref. 161).
=> Improve email settings

src/components/DataTable.tsx, src/components/tables/Pagination.tsx
This syncs selection of datatable's per page into local storage, making it available across all datatables in the app.
=> Improvements for datatable per page

src/pages/settings/gateways/create/components/RequiredFields.tsx, src/pages/settings/gateways/edit/Edit.tsx
This fixes issue with toggles on company gateways edit page (ref. 353).
=> Fixes for company gateways

src/pages/invoices/common/components/ClientSelector.tsx
This implements clicking on on view/edit client on the invoices page.
=> Client links

src/components/DataTable.tsx, src/components/cards/Element.tsx
Changes:
- Fixes for handling of object / string of `Element` component
- Changed `Bulk action` to `More actions`
=> Action labels & translation fixes

src/pages/dashboard/hooks/useGenerateActivityElement.tsx
Support for `payment_amount` and `adjustment` in the activities table.
=> Activities improvements

src/pages/settings/user/UserDetails.tsx
This injects copy of `user` object into changes once the page loads.
=> Inject user into `changes` before updating

src/pages/dashboard/hooks/useGenerateActivityElement.tsx
Changes:
- Fixes for updating user details
=> Sync develop with main

src/pages/authentication/Login.tsx
This fixes positioning for forgot password link.
=> Fix "Forgot password" positioning

src/components/InfoCard.tsx, src/pages/dashboard/components/Chart.tsx, src/pages/dashboard/components/Totals.tsx
This adds accent colors to the charts and info cards.
=> Improve colors for charts

src/pages/authentication/components/SignInProviders.tsx
This provides unified look for Microsoft & Google log in buttons.
=> Provide custom styles for Microsoft & Google login

src/pages/settings/client-portal/ClientPortal.tsx
This changes order of client settings (ref. 163).
=> Change order of client settings

src/pages/settings/account-management/component/DangerZone.tsx, src/pages/settings/localization/components/Settings.tsx
This is React part of https://github.com/invoiceninja/invoiceninja/pull/7916 pull request.
=> Update settings labels.

src/components/tables/Th.tsx, src/pages/clients/common/components/CustomResourcefulActions.tsx, src/pages/clients/edit/components/Details.tsx
Changes:
- "Details" -> "Company details"
- Reorder of actions
=> Client page improvements

src/pages/invoices/common/hooks/useResolveInputField.tsx, src/pages/settings/invoice-design/components/ProductColumns.tsx
This adds support for new `tax_amount` variable/column.
=> Support for `tax_amount` column

src/components/SwitchToFlutter.tsx, src/pages/dashboard/Dashboard.tsx
This hides `Switch to Flutter` button for hosted users.
=> Hide `Switch to Flutter` button

src/pages/dashboard/components/Chart.tsx
This reworks logic behind providing data for charts.
=> Rework logic behind dashboard charts

src/components/CopyToClipboard.tsx, src/pages/clients/common/hooks/useClientColumns.tsx
Fixes for stale value of `CopyToClipboard` component.
=> Stale copy to clipboard

src/common/hooks/emails/useHandleSend.ts, src/pages/credits/email/Email.tsx, src/pages/invoices/email/Email.tsx, src/pages/invoices/email/components/Mailer.tsx, src/pages/purchase-orders/email/Email.tsx, src/pages/quotes/email/Email.tsx
This redirects back to the resource page after sending a successful email.
=> Redirect after emailing

package-lock.json, package.json, src/components/forms/ColorPicker.tsx, src/pages/settings/expense-categories/Create.tsx, src/pages/settings/expense-categories/Edit.tsx, src/pages/settings/gateways/create/hooks/useResolveInputField.tsx, src/pages/settings/invoice-design/components/GeneralSettings.tsx, src/pages/settings/task-statuses/Create.tsx, src/pages/settings/task-statuses/Edit.tsx, src/pages/settings/user/components/AccentColor.tsx
This implements single UI for the color pickers.
[Screencast from 2022-11-19 04-07-47.webm](https://user-images.githubusercontent.com/13711415/202831366-2bd08ab2-6ebb-4d62-9e48-214e9cf8861d.webm)
=> Color picker

src/components/forms/DebouncedCombobox.tsx, src/pages/projects/create/Create.tsx
This improves the behavior of the `ClientSelector` component.
Changes:
- Hide dropdown if prefilled with a value
- Fixes for creating a project from a client page
=> ClientSelector improvements

src/components/Tabs.tsx, src/pages/settings/generated-numbers/GeneratedNumbers.tsx, src/pages/settings/generated-numbers/clients/Clients.tsx, src/pages/settings/generated-numbers/common/hooks/useGeneratedNumbersTabs.tsx, src/pages/settings/generated-numbers/credits/Credits.tsx, src/pages/settings/generated-numbers/expenses/Expenses.tsx, src/pages/settings/generated-numbers/index.ts, src/pages/settings/generated-numbers/invoices/Invoices.tsx, src/pages/settings/generated-numbers/payments/Payments.tsx, src/pages/settings/generated-numbers/projects/Projects.tsx, src/pages/settings/generated-numbers/purchase-orders/PurchaseOrders.tsx, src/pages/settings/generated-numbers/quotes/Quotes.tsx, src/pages/settings/generated-numbers/recurring-expenses/RecurringExpenses.tsx, src/pages/settings/generated-numbers/recurring-invoices/RecurringInvoices.tsx, src/pages/settings/generated-numbers/tasks/Tasks.tsx, src/pages/settings/generated-numbers/vendors/Vendors.tsx, src/pages/settings/routes.tsx
Here is the screenshot of implemented solution for generated numbers tabs:
=> [Feature] Generated numbers tabs

src/components/import/ImportButton.tsx, src/components/import/UploadImport.tsx, src/pages/transactions/import/Import.tsx, src/pages/transactions/index.ts, src/pages/transactions/index/Transactions.tsx, src/pages/transactions/routes.tsx
Here is implemented solution for bank transaction import as all imports in react app.
Here are screenshots of how it looks:
=> [FEATURE] Bank-transaction-import

src/pages/settings/index.ts, src/pages/settings/routes.tsx, src/pages/settings/user/UserDetails.tsx, src/pages/settings/user/common/hooks/useUserDetailsTabs.tsx, src/pages/settings/user/components/AccentColor.tsx, src/pages/settings/user/index.ts
Here is the screenshot of implemented solution for user details tabs:
=> [Feature] User details tabs

.prettierignore, src/common/interfaces/activity-record.ts, src/common/interfaces/vendor-contact.ts, src/common/interfaces/vendor.ts, src/pages/dashboard/hooks/useGenerateActivityElement.tsx, src/pages/tasks/common/helpers/calculate-time.ts, src/pages/vendors/create/Create.tsx, src/pages/vendors/edit/components/Form.tsx
Extract VendorContacts
Update missing props from VendorContact
Update missing props from Activity
Update VendorContact form to include send_email prop
Update activity removing user hyperlink
=> Update Activity Props

src/common/queries/common/params.interface.ts, src/common/queries/documents.ts, src/pages/settings/company/documents/components/Table.tsx
Filters for company documents #288
=> Patch turbo124 company documents

src/components/layouts/Settings.tsx
This provides an option to disable save button using `Settings` layout.
=> Disabling save button in settings

src/common/interfaces/transactions.ts, src/components/forms/DebouncedCombobox.tsx, src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx, src/pages/settings/bank-accounts/create/Create.tsx, src/pages/settings/bank-accounts/create/hooks/useHandleCreate.ts, src/pages/settings/bank-accounts/edit/Edit.tsx, src/pages/transactions/common/validation/ValidationInterface.tsx, src/pages/transactions/components/BankAccountSelector.tsx, src/pages/transactions/components/CreateBankAccountModal.tsx, src/pages/transactions/create/Create.tsx, src/pages/transactions/edit/Edit.tsx, src/pages/transactions/show/Transaction.tsx
@turbo124 Just one small thing to mention, modal for new bank account i too big because we did not specified `"regular"` size earlier. It's specified on Add Company branch, so once we merge it, it will look perfect.
=> [Clean up] Bank accounts/tranasactions

src/pages/settings/company/components/Details.tsx
Here is the screenshot of implementation for company custom fields:
=> [Feature] Company custom fields

src/pages/recurring-invoices/common/hooks.tsx, src/pages/recurring-invoices/index/RecurringInvoices.tsx
Here is the screenshot of implemented solution for additional recurring invoice filter:
=> [Feature] Recurring invoices filters

src/components/TabGroup.tsx
This implements the full tabs feature as seen in #306.
=> Support for full-width tabs

src/App.tsx
This fixes dynamic language imports.
=> Fixes for relative language file references

src/components/layouts/Settings.tsx, src/pages/settings/common/atoms.ts, src/pages/settings/common/hooks/useHandleCompanySave.tsx
Here is the screenshot how validation should looks like after getting 422 error:
Note: This validation has mocked and it's just for preview. Just to make sure `Validation message` will come from `errors.message` API's response.
=> [Bug Fix] Company Validation Handling

src/common/queries/tasks.ts, src/pages/tasks/kanban/Kanban.tsx, src/pages/tasks/kanban/components/EditSlider.tsx
=> Kanban tasks filtering by project

renovate.json
Initial config for Renovate bot.
=> Removate config

src/pages/quotes/common/components/QuoteStatus.tsx, src/pages/quotes/common/hooks.tsx, src/pages/quotes/index/Quotes.tsx, src/pages/recurring-invoices/common/hooks.tsx
Here is the screenshot of implemented solution for Quote custom filters:
=> [Feature] Quote Custom Filters

src/components/DataTable.tsx, src/components/datatables/Actions.tsx, src/pages/tasks/index/Tasks.tsx, src/pages/tasks/kanban/Kanban.tsx
This improves kanban button visibility.
=> Improve kanban positioning

src/pages/settings/localization/components/Settings.tsx
This will hide changing the language on the demo instance.
=> Disabling changing language in demo

src/pages/tasks/common/hooks.tsx, src/pages/tasks/index/Tasks.tsx
Here is the screenshot of implemented solution for task filters:
=> [Feature] Task filters

src/components/DataTable.tsx
This fixes results being stale in data table after checking any of clients' tables.
=> Change the key for handling datatable cache

src/pages/authentication/components/SignInProviders.tsx
This fixes undefined token being sent to Google sign in endpoint.
=> Fixes for Google sign in

src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/components/ExpiredQuotes.tsx, src/pages/dashboard/components/UpcomingQuotes.tsx
Here is the screenshot of implemented solution for quote tables on the dashboard:
=> [Feature] Quote dashboard tables

src/components/layouts/Default.tsx
This implements a permanent back button in the top right corner.
=> Permanent back button

src/pages/expenses/common/hooks.tsx, src/pages/expenses/index/Expenses.tsx
Here is the screenshot of expense custom filters solution:
=> [Feature] Expense custom filters

src/pages/vendors/components/CreateVendorForm.tsx, src/pages/vendors/components/CreateVendorModal.tsx, src/pages/vendors/create/Create.tsx, src/pages/vendors/index/Vendors.tsx
The button on Vendor create pagae is replaced to the navbar:
=> [Cleanup] Save Vendor button replacement

src/components/CompanySwitcher.tsx, src/pages/settings/company/edit/CompanyEdit.tsx
@turbo124 The `companyId` not existing bug is fixed and I have also tested all the scenarios I know to display this modal and everything works perfectly on my end.
=> [Bugfix] Company Edit Modal

src/pages/transactions/components/TransactionMatchDetails.tsx
This updates translations for transactions slide over to match with Flutter apps.
=> Updated translations to sync with Flutter

src/pages/clients/index.ts, src/pages/clients/show/pages/RecurringExpenses.tsx, src/pages/recurring-expenses/create/Create.tsx
Here is the screenshot of implemented solution for recurring expense table on the client overview:
@beganovich @turbo124 Let me know your thoughts.
=> [Feature] Client overview recurring expense table

src/pages/products/Product.tsx, src/pages/products/common/components/CreateProduct.tsx, src/pages/products/common/hooks.tsx, src/pages/products/create/Create.tsx, src/pages/products/edit/Edit.tsx
Here are screenshots of refactored create and edit page for product entity:
=> [Cleanup] Product Create/Edit page refactoring

src/pages/clients/index.ts, src/pages/clients/show/pages/Expenses.tsx, src/pages/expenses/create/Create.tsx
Here is the screenshot of implemented expense table on the client overview page:
=> [Feature] Expense table - client overview page

src/common/queries/tasks.ts, src/pages/tasks/common/atoms.ts, src/pages/tasks/common/helpers/calculate-time.ts, src/pages/tasks/common/hooks/useStart.ts, src/pages/tasks/common/hooks/useStop.ts, src/pages/tasks/kanban/Kanban.tsx, src/pages/tasks/kanban/components/TaskClock.tsx, src/pages/tasks/kanban/components/ViewSlider.tsx
Here is the screenshot of implemented solution for updating task timer if task is running:
@turbo124 @beganovich Let me know your thoughts.
=> [Feature] Task timer updating

src/common/queries/task-statuses.ts, src/components/cards/Card.tsx, src/components/dropdown/Dropdown.tsx, src/pages/settings/task-statuses/Create.tsx, src/pages/settings/task-statuses/Edit.tsx, src/pages/settings/task-statuses/common/hooks.tsx
Here is the screenshot of implemented solution for 'Creating' task instead of just 'Saving':
@turbo124 Important note: The solution is globalized so there will be less work if we want to implement the same functionality for any other entity where we use this `Card` component.
@beganovich Apart from the function, I refactored the code to be consistent with the rest of the project.
=> [Feature] Task create option

src/pages/transactions/common/hooks/useActions.tsx, src/pages/transactions/common/hooks/useBulkAction.tsx, src/pages/transactions/create/Create.tsx, src/pages/transactions/edit/Edit.tsx
Here are screenshots of refactored UI for Create/Edit Transaction page:
=> [Cleanup] Create/Edit Transaction Page - Refactor

src/pages/projects/Project.tsx, src/pages/projects/common/hooks.tsx, src/pages/projects/create/Create.tsx, src/pages/projects/edit/Edit.tsx
Here are screenshots of implemented solution for new UI for Create/Edit Project pages:
=> [Cleanup] Refactor UI for Create/Edit Project pages

src/pages/projects/create/Create.tsx
Here's a screenshot of the implemented solution for the `Add client` to combo box option on the Project create page:
=> [Cleanup] Add client - Project create page

src/pages/settings/workflow-settings/WorkflowSettings.tsx
Here is the screenshot of implemented tabs for Workflow Settings page:
=> [Cleanup] Workflow Settings - Tabs

src/pages/settings/tax-settings/TaxSettings.tsx
Here's a screenshot of what the `Inclusive Taxes` field looks like with helper text after the changes:
=> [Cleanup] Inclusive Taxes - Helper Text

src/common/interfaces/api-webhook.ts, src/common/queries/api-webhooks.ts, src/pages/settings/integrations/api-webhooks/ApiWebhooks.tsx, src/pages/settings/integrations/api-webhooks/Create.tsx, src/pages/settings/integrations/api-webhooks/Edit.tsx, src/pages/settings/integrations/api-webhooks/common/hooks.tsx, src/pages/settings/integrations/api-webhooks/common/useActions.tsx
Here are screenshots of the implemented refactoring for WebHook pages:
=> [Cleanup] Api WebHook Pages - Refactoring

src/pages/settings/invoice-design/components/GeneralSettings.tsx
=> [Bugfix] Portrait spelling

src/pages/settings/backup-restore/components/Backup.tsx
Here is the screenshot of UI when helper text is added:
=> [Cleanup] Export company - helper text

src/pages/settings/client-portal/components/Customize.tsx
@beganovich @turbo124 I've added condition for showing Custom CSS and JS fields. So, if user is SELF-HOSTED it will be shown otherwise it will not be available.
=> [Cleanup] Hiding Custom CSS and JS fields

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx, src/pages/settings/templates-and-reminders/common/constants/variables/common-variables.ts, src/pages/settings/templates-and-reminders/common/constants/variables/payment-variables.ts
@turbo124 @beganovich For some templates we have different variables. One of them is `Payment` template so I changed variables when this one is selected:
@turbo124 I copied variables from the Flutter app. Except this one I noticed that we maybe have wrong variables for some other templates. Should I resolve it on this PR or create another one?
=> [Cleanup] Payment template variables

.github/workflows/release.yml
Allows us to tag release and create builds.
These are then used in our docker deployments.
=> Release workflows

src/pages/settings/generated-numbers/clients/Clients.tsx, src/pages/settings/generated-numbers/credits/Credits.tsx, src/pages/settings/generated-numbers/expenses/Expenses.tsx, src/pages/settings/generated-numbers/invoices/Invoices.tsx, src/pages/settings/generated-numbers/payments/Payments.tsx, src/pages/settings/generated-numbers/projects/Projects.tsx, src/pages/settings/generated-numbers/purchase-orders/PurchaseOrders.tsx, src/pages/settings/generated-numbers/quotes/Quotes.tsx, src/pages/settings/generated-numbers/recurring-expenses/RecurringExpenses.tsx, src/pages/settings/generated-numbers/recurring-invoices/RecurringInvoices.tsx, src/pages/settings/generated-numbers/tasks/Tasks.tsx, src/pages/settings/generated-numbers/vendors/Vendors.tsx
Here is the screenshot of UI for Generated Numbers page after adding Copy to Clipboard functionality to variables:
@turbo124 @beganovich Let me know your thoughts.
=> [Cleanup] Generated numbers - Variables Copy to Clipboard

src/pages/settings/expense-categories/ExpenseCategories.tsx
Here is the screenshot of expense categories page with added edit action to dropdown:
=> [Cleanup] Expense category - edit action

src/pages/settings/account-management/AccountManagement.tsx, src/pages/settings/account-management/common/hooks/useAccountManagementTabs.tsx, src/pages/settings/account-management/index.ts, src/pages/settings/index.ts, src/pages/settings/routes.tsx
Here is the screenshot of implemented tabs for Account Management pages:
=> [Cleanup] Account management tabs

src/common/interfaces/company.interface.ts, src/pages/settings/online-payments/OnlinePayments.tsx
Here is the screenshot of implemented solution for the `auto_bill_standard_invoices`:
@turbo124 @beganovich Let me know your thoughts.
=> [Feature] Auto_bill_standard_invoices implementation

src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/invoice-design/common/atoms.ts, src/pages/settings/invoice-design/components/GeneralSettings.tsx
Here is the screenshot of the Invoice Design page after adding `Update all records` functionality:
@beganovich @turbo124 Let me know your thoughts.
=> [Cleanup] Update all records - Invoice design

src/pages/clients/routes.tsx, src/pages/credits/routes.tsx, src/pages/expenses/routes.tsx, src/pages/payments/routes.tsx, src/pages/products/routes.tsx, src/pages/purchase-orders/routes.tsx, src/pages/quotes/routes.tsx, src/pages/recurring-expenses/routes.tsx, src/pages/recurring-invoices/routes.tsx, src/pages/tasks/routes.tsx, src/pages/transactions/routes.tsx, src/pages/vendors/routes.tsx
This implements another round of permission changes. The following permissions are in action.
Notes:
* Any check for view_*, includes view_all
* Any check for edit_*, includes edit_all
* Any check for create_*, includes create_all
* All checks include admin
This is current state of permissions:
```
/clients: view_client || create_client || edit_client
/clients/import: create_client || edit_client
/clients/create: create_client
/clients/:id/edit: view_client || edit_client || assigned
/clients/:id: view_client || edit_client || assigned
/products: view_product || create_product || edit_product
/products/import: create_product || edit_product
/products/create: create_product
/products/:id: view_product || edit_product || assigned
/products/:id/edit: view_product || edit_product || assigned …
```
=> Apply view permissions to edit pages

src/pages/credits/edit/Edit.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/recurring-invoices/edit/Edit.tsx
This reverts commit b64a686a0d56c134c55f975f33d9c19313c60cac.
=> Revert "Fixed bug with incorrectly showing pdf preview"

src/pages/settings/routes.tsx
@beganovich @turbo124 Merging this PR should be a priority! Somehow we missed merging the `account_management` routes into the develop branch. So this PR just includes that part. Let me know your thoughts.
=> [BugFix] Account management routes

src/pages/invoices/common/components/InvoiceStatus.tsx
@beganovich @turbo124 The PR includes changing logic to fix bugs for showing status badges for Invoice entity. Let me know your thoughts.
=> [Bugfix] Status badges

src/pages/invoices/common/components/InvoiceViewer.tsx
This fixes invoice viewer reactivity.
=> Fixes for invoice viewer reactivity

src/components/layouts/Default.tsx
=> Change white label text

src/pages/recurring-invoices/common/hooks.tsx, src/pages/recurring-invoices/common/queries.ts
@beganovich @turbo124 We missed bulk actions on the `Recurring Inovice` edit page. It is now implemented and working correctly on my end. Screenshot:
=> [Cleanup] Adding Bulk Actions | Recurring Invoice Edit Page

src/common/hooks/emails/useHandleSend.ts, src/common/hooks/emails/useResolveTemplate.ts, src/pages/invoices/email/components/Mailer.tsx
@beganovich @turbo124 PR includes adding new field on Email pages. `CC Email` field will be available for SELF-HOSTED users or HOSTED users with Pro/Enterprise plan. Screenshot:
=> [Feature] CC Email New Field

src/pages/settings/client-portal/components/Registration.tsx
@beganovich @turbo124 PR includes refactoring the current logic on the `Registration` fields. We only have the ability to hide or make required fields. We now have a `Visible` option, so the `Toggle` is changed to `Selection` drop-down for each field. Screenshot:
=> [Feature] New Registration Field Value | Client Portal

src/common/interfaces/company.interface.ts, src/pages/settings/email-settings/EmailSettings.tsx
@beganovich @turbo124 PR includes adding new field for `Mailgun` email provider (`Endpoint`). Screenshot:
=> [Feature] Endpoint Field | Mailgun Email Provider 

package-lock.json, package.json, src/index.tsx, src/pages/authentication/components/SignInProviders.tsx
This updates Google sign-in to new 2.0 flow.
=> Update Google sign-in

src/components/VerifyModal.tsx
@beganovich @turbo124 PR includes changing translation keyword on the email verification modal. Screenshot:
=> [Cleanup] Translation Keywords | Email Verification Modal

src/pages/settings/user/components/Connect.tsx
@beganovich @turbo124 PR includes implementing a disconnect function when the user clicks `disconnect_microsoft` or `disconnect_google`. On click we will call a POST method on the route `/api/v1/users/:userId/disconnect_mailer`. Let me know your thoughts.
=> [Feature] Disconnecting Functionality | Oauth Providers

src/pages/credits/common/hooks.tsx, src/pages/invoices/common/hooks/usePrintPdf.ts, src/pages/invoices/edit/components/Actions.tsx, src/pages/purchase-orders/common/hooks.tsx, src/pages/quotes/common/hooks.tsx
@beganovich @turbo124 PR includes adding print option for `Invoice`, `Credit`, `Purchase Order` and `Quote` entities. Screenshot:
=> [Feature] PDF Print Option

src/pages/transactions/components/Details.tsx, src/pages/transactions/components/ListBox.tsx
@beganovich @turbo124 PR includes changes that will allow multiple expenses to be selected when converting a transaction. Let me know your thoughts.
=> [Feature] Multiple Expense Selection | Transaction Matching

src/components/DataTable.tsx, src/pages/credits/common/hooks.tsx, src/pages/credits/index/Credits.tsx, src/pages/invoices/common/hooks/usePrintPdf.ts, src/pages/invoices/edit/components/Actions.tsx, src/pages/invoices/index/Invoices.tsx, src/pages/purchase-orders/common/hooks.tsx, src/pages/purchase-orders/index/PurchaseOrders.tsx, src/pages/quotes/common/hooks.tsx, src/pages/quotes/index/Quotes.tsx
@beganovich @turbo124 PR includes adding Print PDF as bulk action for `Credit`, `Invoice`, `Quote` and `Purchase Order` entities. Screenshot:
=> [Feature] Multiple PDF Print

src/components/layouts/Default.tsx, src/components/layouts/common/hooks.ts
This allows us to control the save button from the child component, essentially lifting up the state.
=> Dynamic control of save button

src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 PR includes fixing width bug for the currency selector on the dashboard. Screenshot:
=> [Bugfix] Currency Selector Width | Dashboard

src/pages/reports/index/Reports.tsx
@beganovich @turbo124 PR includes adding `Activity` report. Screenshot:
=> [Feature] Added | Activity Report

src/pages/settings/user/components/Notifications.tsx, src/pages/settings/users/edit/components/Notifications.tsx
@beganovich @turbo124 PR includes adding `Inventory Threshold` notification type. Screenshot:
=> [Feature] Inventory Threshold Notification Type

src/pages/settings/user/components/Notifications.tsx, src/pages/settings/users/edit/components/Notifications.tsx
@beganovich @turbo124 PR includes adding new notification type (`payment_manual`). Screenshot:
=> [Feature] Payment Manual Notification Type

src/components/DropdownDateRangePicker.tsx, src/components/forms/SelectField.tsx, src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 PR includes bug fixes for width of Select menus on the Dashboard page. Screenshot:
=> [Bugfix] Select Menus Width | Dashboard

src/pages/settings/bank-accounts/components/transaction-rules/components/RuleModal.tsx, src/pages/settings/bank-accounts/index/BankAccounts.tsx
@turbo124 @beganovich PR includes resolving all bugs regarding Bank rules. Screenshot:
Now, we will display `Rules` button on the `Bank accounts` main page for the `SELF-HOSTED` users and `HOSTED` users with `Pro/Enterprise` plan.
=> [Bugfix] Bank rules | Operators

src/pages/payments/create/hooks/useSave.ts, src/pages/payments/edit/hooks/useSave.ts
@beganovich @turbo124 Currently on the PR we have improving UX for Payment error messages. David, I can not see here any issues regarding not-displaying 422 error messages. Here is the screenshot:
If we still have some issues, please just give me quick advice where it is.
=> [Bugfix] Improved UX for Payment error messages

src/common/hooks/useConvertCurrancy.ts, src/common/interfaces/payment.ts, src/common/queries/payments.ts, src/pages/payments/Payment.tsx, src/pages/payments/apply/Apply.tsx, src/pages/payments/create/Create.tsx, src/pages/payments/documents/Documents.tsx, src/pages/payments/refund/Refund.tsx, src/pages/transactions/components/Details.tsx
This improves types on payments query (usePaymentsQuery) hook.
=> Refactor payments query

src/components/forms/Combobox.tsx, src/pages/invoices/common/components/ProductCreate.tsx
This improves a11y on the new combobox component. 
- Tab to click away and capture the current value
- Skip the action with arrow keys
- Populate the product selector after creating a new record
=> Improve combobox accessibility

src/common/stores/slices/user.ts, src/pages/settings/user/UserDetails.tsx, src/pages/settings/user/components/Password.tsx
@beganovich @turbo124 PR includes removing `confirmation_password` field and code formatting for the logic. Here is the screenshot:
=> [Bugfix] Password change

src/common/interfaces/company.interface.ts, src/components/HelpSidebarIcons.tsx, src/pages/settings/client-portal/ClientPortal.tsx, src/pages/settings/client-portal/components/Settings.tsx, src/pages/settings/generated-numbers/clients/Clients.tsx, src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx
Allows hosted users to set domain / subdomain
=> Hosted client portal domain

src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/localization/common/atoms.ts, src/pages/settings/localization/components/Settings.tsx
invalidate statics only on language change
=> Fixes for redundant queries

src/components/clients/ClientSelector.tsx, src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx
This fixes the issue with flashing old content for the combobox cache.
=> Fixes for partially stale combobox cache

src/pages/settings/user/common/hooks/useNotificationOptions.ts, src/pages/settings/user/components/Notifications.tsx
@beganovich @turbo124 PR includes aligning User Notifications with Flutter app, that is switching from toggle to select menu with additional option. Here is the screenshot:
=> [Cleanup] Notifications | User Details

src/components/Banner.tsx, src/components/layouts/Default.tsx
This implements a banner in the app.
=> Banner component

src/common/hooks/useReactSettings.ts, src/common/interfaces/company-user.ts, src/pages/settings/user/components/Preferences.tsx
This reimplements notification link settings in the app.
=> Reincarnate "React notification link"

src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx
This implements descriptions for the product selector.
=> Product descriptions in selector

src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/invoice-design/common/atoms.ts, src/pages/settings/invoice-design/pages/general-settings/GeneralSettings.tsx, src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx
This refactors logic for updating all design resources with better architecture and simplified handling of state.
=> Refactor updating all resources (invoice design)

src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx
This reverts broken formatting for the combobox labels.
=> Revert combobox description changes

src/pages/credits/edit/Edit.tsx, src/pages/invoices/common/components/ClientSelector.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/recurring-invoices/edit/Edit.tsx
This will hide the client combobox when viewing the invoices if the user has no permission to view it.
The fallback is just the name of the client.
=> Improve client selector UX

src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx, src/pages/credits/common/components/CreditFooter.tsx
This fixes (and improves) the logic for formatting the combobox labels. Now we have `label` which is a fallback for `labelFn`.
=> Improved logic for formatting combox labels

src/common/queries/common/headers.ts
This adds back the missing X-React header.
=> Fixes for missing header

src/common/interfaces/project.ts, src/common/queries/invoices.ts, src/pages/projects/common/hooks.tsx, src/pages/projects/common/hooks/useBulkAction.ts, src/pages/projects/routes.tsx, src/pages/projects/show/Show.tsx, src/pages/tasks/create/Create.tsx
This implements an overview-like page for projects.
Todo:
- Budgeted hours graph
=> Projects overview page

src/pages/invoices/common/components/InvoiceViewer.tsx, src/pages/invoices/email/components/Mailer.tsx
This fallbacks to more friendly text to let users know to download PDF files.
=> Fallback for PDF previews on Android

src/common/hooks/useCurrentCompany.ts, src/pages/clients/edit/Edit.tsx, src/pages/credits/common/hooks.tsx, src/pages/invoices/edit/hooks/useInvoiceSave.ts, src/pages/quotes/common/hooks.tsx, src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/tasks/edit/Edit.tsx, src/pages/vendors/components/CreateVendorForm.tsx, src/pages/vendors/edit/Edit.tsx
This lets us conditionally mutate the company without wasting HTTP resources on identical payload requests.
=> Conditionally mutating company

src/common/constants/payment-type.ts, src/common/enums/payment-type.ts, src/pages/payments/create/Create.tsx, src/pages/tasks/common/components/TaskDetails.tsx, src/pages/tasks/create/Create.tsx
Add Zelle payment type
Fixes for default settings for manual payment notifications
Fixes for adding default task rates when creating tasks.
=> Fixes for payment notification presets

src/pages/tasks/common/components/TaskDetails.tsx
This fixes logic for default task rate.
=> Fixes for default task rate

src/pages/invoices/common/components/InvoicePreview.tsx
Ensure we pass the entity ID to the live preview engine
=> Fixes for previews

src/pages/payments/create/hooks/useSave.ts
ensures paid invoices are invalidated
=> Fixes for invoice invalidation after payment applied

src/components/CopyToClipBoardIconOnly.tsx, src/components/emails/Contact.tsx, src/pages/clients/edit/components/Contacts.tsx, src/pages/invoices/common/components/ClientSelector.tsx
Add Icon only clipboard
Fixes for adding contacts to existing client
Only display contacts that are receiving emails in the mailer preview
=> Improve contact editing

src/common/queries/company-gateways.ts, src/pages/settings/gateways/create/hooks/useHandleCreate.ts, src/pages/settings/gateways/edit/hooks/useHandleUpdate.ts
@beganovich @turbo124 As I informed you on Slack regarding the production bug for creation gateways, which sometimes occurs, I have created a small PR that could potentially resolve this issue based on my observations. This of course works perfectly fine locally, but I hope that this will fix the issue in the production also. Please let me know your thoughts.
=> [Bugfix] Gateways Production Query Invalidation Fixes

src/common/interfaces/activity-record.ts, src/pages/dashboard/components/Activity.tsx, src/pages/dashboard/hooks/useGenerateActivityElement.tsx
Offloads the majority of work for rendering activities onto the API, whilst maintaining the ability to have client side links.
I have used versioning on the API and client to ensure backward compatiblity
=> Refactor for activities

src/common/interfaces/project.ts, src/pages/projects/common/hooks.tsx, src/pages/projects/show/Show.tsx, src/pages/tasks/common/helpers/calculate-time.ts, src/pages/tasks/create/Create.tsx
Fixes for displaying task duration in list view when time > 1 day
Fixes for injecting project rates into tasks.
=> Fixes for duration and passing rates into tasks

src/pages/clients/show/pages/Payments.tsx
include invoices for payments.
=> Updates for queries when in client overview

src/pages/settings/users/index/Users.tsx
This fixes bulk actions for the user management table.
=> Fixes for bulk actions in users table

src/pages/payments/apply/Apply.tsx
This refactors the apply payment screen to use global (top) save button and drops the one from the card.
=> Fixes for applying payments button

src/pages/clients/create/Create.tsx, src/pages/clients/edit/Edit.tsx, src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/clients/edit/components/Address.tsx, src/pages/clients/edit/components/Contacts.tsx, src/pages/clients/edit/components/Details.tsx, src/pages/clients/edit/components/address/BillingAddress.tsx, src/pages/clients/edit/components/address/ShippingAddress.tsx, src/pages/credits/common/components/CreditFooter.tsx, src/pages/credits/create/Create.tsx, src/pages/credits/edit/Edit.tsx, src/pages/invoices/common/components/ClientCreate.tsx, src/pages/invoices/common/components/InvoiceFooter.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/purchase-orders/edit/components/Footer.tsx, src/pages/quotes/common/components/QuoteFooter.tsx, src/pages/quotes/create/Create.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/recurring-invoices/common/components/InvoiceFooter.tsx, src/pages/recurring-invoices/create/Create.tsx, src/pages/recurring-invoices/edit/Edit.tsx
@turbo124 @beganovich This PR includes the addition and adjustment of validation for certain pages, specifically `Client` pages and the `Settings` tab for applicable entities. Please find the screenshots below:
@turbo124 We actually had validation for the Client emails, but it was originally positioned at the top of the page. Now, it has been implemented to appear just below the field, following the project's conventions.
Those are all places that I know we missed validation, please let me know if you found any other.
=> [Bugfix] Displaying 422 On Some Pages

src/components/DropdownDateRangePicker.tsx, src/pages/dashboard/components/Activity.tsx, src/pages/dashboard/components/ExpiredQuotes.tsx, src/pages/dashboard/components/PastDueInvoices.tsx, src/pages/dashboard/components/RecentPayments.tsx, src/pages/dashboard/components/Totals.tsx, src/pages/dashboard/components/UpcomingInvoices.tsx, src/pages/dashboard/components/UpcomingQuotes.tsx
Improve functionality of charts
=> Change chart queries date strings

src/components/forms/Combobox.tsx, src/components/projects/ProjectSelector.tsx, src/components/users/UserSelector.tsx, src/pages/invoices/common/components/InvoiceFooter.tsx
This migrates the user & project selector to the new component.
=> Improve & migrate selectors 

src/common/interfaces/expense.ts, src/common/interfaces/invoice-item.ts, src/common/queries/expenses.ts, src/components/expense-categories/ExpenseCategorySelector.tsx, src/components/projects/ProjectSelector.tsx, src/components/tax-rates/TaxRateSelector.tsx, src/components/users/UserSelector.tsx, src/components/vendors/VendorSelector.tsx, src/pages/expenses/common/hooks.tsx, src/pages/expenses/common/useInvoiceExpense.ts, src/pages/expenses/create/components/Details.tsx, src/pages/expenses/create/components/Taxes.tsx, src/pages/expenses/edit/Edit.tsx, src/pages/expenses/edit/hooks/useSave.ts, src/pages/expenses/index/Expenses.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/projects/index/Projects.tsx, src/pages/tasks/common/hooks/useInvoiceTask.ts
Conversion of Expenses to invoice
=> Invoice Expenses

src/pages/payments/create/Create.tsx
=> Fixes for isNan

src/components/DropdownDateRangePicker.tsx, src/pages/dashboard/components/Totals.tsx
The issue was:
```
setCurrency(currency ?? parseInt(currencies[0].value));
```
because we set
```
const [currency, setCurrency] = useState(1);
```
currency is never null,
this PR resolves by switching the ternary around
For merge to main pls.
=> Fixes for charts

src/pages/expenses/common/hooks.tsx
This fixes the queries we use to populate the expense to invoice modal.
One issue which I was unable to resolve was the Add To Invoice action from the list view does not carry the correct expense across.
=> Fixes for queries for adding expense to invoice

src/pages/payments/create/Create.tsx
@beganovich @turbo124 The PR includes adding missing validation for invoices and credits on `Payment` creation page. Here is the screenshot:
=> [Bugfix] Payment Creation 422 For Invoices And Credits

src/components/forms/DecimalNumberInput.tsx, src/pages/invoices/common/hooks/useResolveInputField.tsx
=> Fixes for debounce + nan

src/pages/settings/common/hooks/useHandleCompanySave.tsx
@beganovich @turbo124 The PR includes fixing toaster displaying on company settings pages. Let me know your thoughts.
=> [Bugfix] Toaster On Settings Pages Fixing

src/components/tables/Pagination.tsx
@beganovich @turbo124 The PR includes additional arrows for navigation to first and last page in one click. Screenshot:
=> [Feature] Additional Pagination Arrows

src/pages/dashboard/components/Chart.tsx, src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 The PR includes formatting values for Tooltip Chart component. Here is the screenshot:
I have created some test data for this, but I am experiencing issues with the `Chart` regarding endpoints and 422 errors. I have noticed that in production, everything works as expected, and no one else has reported any issues. Am I the only one experiencing this issue?
=> [Bugfix] Missing Currency Formatting On Chart Tooltip

src/components/forms/Combobox.tsx
This fixes and refetches combobox values once the URL href changes.
=> Fixes for referential comparision

src/pages/projects/common/hooks/useInvoiceProject.tsx, src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts
for merge to main, asap please
=> Fixes for adding task ids to invoice items

src/pages/payments/edit/PaymentFields.tsx, src/pages/payments/edit/hooks/useSave.ts, src/pages/settings/common/hooks/useHandleCompanySave.tsx
@beganovich @turbo124 The PR includes removing save button from the Payment custom fields page and moving whole logic into main Save button in the navigation bar. Screenshot:
=> [Cleanup] Removing Save Button | Payment Custom Fields

src/pages/tasks/common/hooks.tsx, src/pages/tasks/common/hooks/useInvoiceTask.ts
This adds an option to invoice multiple tasks at once.
=> Bulk action on invoicing tasks

src/pages/settings/gateways/create/Create.tsx, src/pages/settings/gateways/edit/Edit.tsx, src/pages/settings/gateways/edit/components/stripe/ImportCustomers.tsx
This lets us import customers from Stripe.
=> Stripe: Importing customers

public/tinymce_6.4.2/tinymce/content.css, src/components/forms/MarkdownEditor.tsx
As the title says, because that's the world we live in
=> Fixes for TinyMCE paste area

src/pages/clients/edit/components/AdditionalInfo.tsx
This will set true/false or unset the whole setting if empty string is passed.
=> Fixes for client reminders

src/components/forms/InputField.tsx, src/pages/authentication/Login.tsx, src/pages/authentication/Register.tsx, src/pages/clients/edit/components/Contacts.tsx
@beganovich @turbo124 The PR includes preventing auto-filling Email and Password fields on Login and Register page even if it is saved in the browser passwords. Let me know your thoughts.
=> [Cleanup] Preventing Auto-Fill For All Fields Expect Fields For Login & Register Pages

src/pages/purchase-orders/common/hooks.tsx
This will format using vendor currency/country and fallback to country safely.
=> Fix for purchase order amount formatting

src/pages/settings/integrations/api-tokens/ApiTokens.tsx
This adds is_system=false to api tokens datatable.
=> Add system filter to tokens

src/common/interfaces/company.interface.ts, src/pages/settings/localization/components/Settings.tsx
=> Move from settings => company object

src/common/hooks/usePreferences.tsx
This creates a replacement for useState/useAtom with the same API, but it operates on the preferences/user level.
Example:
```ts
const [defaultView, setDefaultView] = usePreference('preferences.dashboard_charts.default_view')
setDefaultView('day' | 'week' | 'month') // has to be same type as default_view defined in ReactSettings
```
It is also completely type-safe with autocomplete for each setting.
=> usePreference

src/pages/settings/tax-settings/components/Selector.tsx
=> Increase the default amount of taxes

src/pages/dashboard/components/Totals.tsx
This fixes the issues with currency preselecting.
=> Fixes for dashboard currency 

src/common/constants/exports/client-map.ts, src/common/hooks/usePreferences.tsx, src/common/hooks/useReactSettings.ts, src/pages/reports/common/components/SortableColumns.tsx, src/pages/reports/index/Reports.tsx
This integrates (and saves) the export maps variables into user preferences.
=> Export maps preferences

src/pages/payments/create/Create.tsx
This fixes for visibility of combobox on create a payment page.
=> Fixes for visiblity of combobox

src/pages/payments/apply/Apply.tsx
This applies formatting to the values on apply payment page.
=> Fixes for formatting on apply page

.github/workflows/analyse.yml
https://github.com/nodejs/release#release-schedule
=> Drop actions for Node 16.x

src/pages/credits/index/Credits.tsx, src/pages/expenses/common/hooks.tsx, src/pages/expenses/index/Expenses.tsx, src/pages/payments/apply/Apply.tsx, src/pages/payments/create/Create.tsx, src/pages/payments/create/hooks/useSave.ts, src/pages/payments/index/Payments.tsx, src/pages/projects/index/Projects.tsx, src/pages/purchase-orders/index/PurchaseOrders.tsx, src/pages/quotes/index/Quotes.tsx, src/pages/recurring-invoices/index/RecurringInvoices.tsx, src/pages/tasks/index/Tasks.tsx
Improves filtering and query invalidation
=> Additional query filters for lists

src/App.tsx, src/components/DropdownDateRangePicker.tsx, src/components/forms/Datepicker.tsx
This fixes issues with HMR, enabling faster dev cycles and less deps reloads.
=> Fixes for hot module replacements

src/pages/products/common/components/ProductForm.tsx
This passes correct input types.
=> Fixes for number inputs on product form

src/components/forms/DecimalNumberInput.tsx, src/pages/invoices/common/hooks/useResolveInputField.tsx
This switches logic from on debounce to on blur.
=> Fixes for debouncing in products table number inputs

src/pages/purchase-orders/edit/components/Details.tsx
Please merge to main + release
=> Show purchase order custom fields

src/pages/dashboard/components/Chart.tsx
=> Fixes for formatting the Y axis label

src/pages/clients/edit/components/AdditionalInfo.tsx
This removes the property from settings if the value is empty.
=> Fixes for client settings

src/common/interfaces/credit.ts, src/common/queries/invoices.ts, src/pages/credits/common/hooks.tsx, src/pages/credits/create/Create.tsx, src/pages/invoices/common/hooks/useCustomBulkActions.tsx, src/pages/invoices/common/hooks/useReverseInvoice.ts, src/pages/invoices/edit/components/Actions.tsx
@beganovich @turbo124 The PR includes implementation for `Reverse` action on Invoice entity pages. Screenshot:
=> [Feature] Reverse Action | Invoices

src/common/interfaces/company.interface.ts, src/pages/settings/gateways/edit/Edit.tsx, src/pages/settings/gateways/edit/components/WebhookConfiguration.tsx, src/pages/settings/gateways/edit/components/stripe/ImportCustomers.tsx
Implements webhook overview for payment gateways.
=> Webhook overview for Payment Gateways

src/pages/expenses/Expense.tsx, src/pages/expenses/documents/Documents.tsx, src/pages/expenses/edit/Edit.tsx, src/pages/expenses/edit/hooks/useSave.ts, src/pages/expenses/routes.tsx, src/pages/recurring-expenses/RecurringExpense.tsx, src/pages/recurring-expenses/components/Details.tsx, src/pages/recurring-expenses/components/Taxes.tsx, src/pages/recurring-expenses/documents/Documents.tsx, src/pages/recurring-expenses/edit/Edit.tsx, src/pages/recurring-expenses/routes.tsx
@beganovich @turbo124 The PR includes resolving the bug of not having Save buttons on `Expense and Recurring Expense Edit pages` for the `Documents` tab. Besides fixing those bugs, the code structure is significantly improved and aligned with the rest of the project. Screenshot:
In addition, the PR includes resolving a couple of bug noticed while testing.
=> [Bugfix] Save Buttons Fixes For Expense & Recurring Expense Edit Pages && Code Structure Improvement

src/pages/authentication/RecoverPassword.tsx, src/pages/authentication/Register.tsx, src/pages/clients/create/Create.tsx, src/pages/invoices/common/components/ProductCreate.tsx, src/pages/products/create/Create.tsx, src/pages/products/edit/Edit.tsx, src/pages/settings/bank-accounts/components/transaction-rules/TransactionRules.tsx, src/pages/settings/custom-fields/CustomFields.tsx, src/pages/settings/custom-fields/clients/Clients.tsx, src/pages/settings/custom-fields/company/Company.tsx, src/pages/settings/custom-fields/expenses/Expenses.tsx, src/pages/settings/expense-categories/Edit.tsx, src/pages/settings/gateways/create/Create.tsx, src/pages/settings/gateways/edit/Edit.tsx, src/pages/settings/group-settings/GroupSettings.tsx, src/pages/settings/payment-terms/PaymentTerms.tsx, src/pages/settings/subscriptions/create/Create.tsx, src/pages/settings/subscriptions/edit/Edit.tsx, src/pages/settings/subscriptions/index/Subscriptions.tsx, src/pages/settings/task-statuses/components/CreateTaskStatusModal.tsx, src/pages/settings/tax-rates/Edit.tsx
@beganovich @turbo124 The PR includes fixes for titles throughout the app, including changes for these pages:
- Client Creation Page
- Product Creation Modal
- Product Creation Page
- Product Editing Page
- Transaction Rules Table Page
- Expense Category Editing Page
- Company Gateway Creation Page
- Company Gateway Editing Page
- Payment Link Creation Page
- Payment Link Editing Page
- Payment Links Table Page
- Task Status Creation Modal
=> [Bugfix] Page Titles Fixes

src/common/interfaces/client.ts, src/common/interfaces/invoice.ts, src/common/interfaces/tax-info.ts
Changes the taxdata prop to tax_info with associated interface
=> Refactor TaxData => TaxInfo

src/pages/tasks/common/hooks/useInvoiceTask.ts
=> Pass inclusive tax settings over to invoice

src/common/interfaces/invoice.ts, src/pages/invoices/common/components/InvoiceSlider.tsx
Fixes the payments for the invoice
=> Hot fix for slideout

src/common/interfaces/company.interface.ts, src/pages/invoices/common/hooks/useHandleProductChange.ts
This makes products table respect `fill_products` setting.
=> Autofilling the products

src/common/hooks/useAdjustColorDarkness.ts, src/common/queries/task-statuses.ts, src/components/DataTable.tsx, src/components/StatusBadge.tsx, src/components/datatables/Actions.tsx, src/pages/clients/show/pages/Expenses.tsx, src/pages/clients/show/pages/Tasks.tsx, src/pages/expenses/index/Expenses.tsx, src/pages/invoices/index/Invoices.tsx, src/pages/payments/index/Payments.tsx, src/pages/projects/show/Show.tsx, src/pages/purchase-orders/index/PurchaseOrders.tsx, src/pages/quotes/index/Quotes.tsx, src/pages/recurring-invoices/index/RecurringInvoices.tsx, src/pages/tasks/common/components/TaskStatus.tsx, src/pages/tasks/common/hooks.tsx, src/pages/tasks/index/Tasks.tsx, src/pages/transactions/index/Transactions.tsx, src/pages/vendors/show/pages/Expenses.tsx, src/pages/vendors/show/pages/PurchaseOrders.tsx
@beganovich @turbo124 The PR includes implementation for new Task filters (additionally by Task Statuses). Screenshot:
=> [Feature] Task Filters | Task Statuses

src/components/Tabs.tsx, src/pages/payments/Payment.tsx
@beganovich @turbo124 The PR includes fixes for navigation to apply/restore Payment's pages. Let me know your thoughts.
=> [Bugfix] Apply Restore Pages Navigation | Payments

src/pages/authentication/Login.tsx, src/pages/authentication/components/Disable2faModal.tsx
@beganovich @turbo124 The PR includes implementing functionality for Disable 2FA. Screenshots:
=> [Feature] Disable 2FA Functionality

src/pages/reports/common/components/SortableColumns.tsx, src/pages/reports/index/Reports.tsx
This fixes the behavior of export maps, respecting the "customize columns" toggle as well as preferences.
=> Fixes for export maps

src/pages/tasks/common/helpers/calculate-time.ts, src/pages/tasks/common/hooks.tsx
This will show relative hours to the current time if the task is running.
=> Include calculated hours in the datatable

src/pages/products/Product.tsx, src/pages/products/common/components/ProductForm.tsx
This passes `update_in_stock_quantity` to the backend once the stock qty changes.
=> Passing `update_in_stock_quantity` after updating stock qty

src/pages/authentication/components/SignInProviders.tsx
This temporary disables Microsoft login.
=> Disable MS login

src/common/queries/api-tokens.ts
Changes permissions from Owner to Admin to create tokens.
=> Fixes for token creation permissions

src/components/DataTable.tsx
@beganovich @turbo124 The PR includes a fix for a bug related to displaying the bulk restore action. Let me know your thoughts.
=> [Bugfix] Showing Bulk Restore Action | All Tables

package-lock.json, package.json, src/common/stores/slices/user.ts, src/pages/authentication/Logout.tsx, src/pages/authentication/components/SignInProviders.tsx, src/pages/settings/user/components/Connect.tsx
This swaps the old Microsoft login for the official @azure/msal-browser package.
=> Reimplement Microsoft login

src/pages/invoices/common/components/InvoiceSlider.tsx, src/pages/invoices/edit/components/Actions.tsx
@beganovich @turbo124 The PR involves fixing the bug related to the inappropriate display of actions on invoice pages. Let me know your thoughts.
=> [Bugfix] Inappropriately Displaying Actions On Invoice Pages

src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx, src/components/tax-rates/TaxCategorySelector.tsx
This allows us to perform a subset search using an additional field.
=> Fixes for first line selecting

src/components/clients/ClientSelector.tsx, src/pages/clients/create/Create.tsx, src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/clients/edit/components/Address.tsx, src/pages/invoices/common/components/ClientCreate.tsx
This implements a slider for the client selector creation.
=> Move client creation screen to the side

src/components/forms/InputField.tsx, src/components/tables/Td.tsx, src/pages/invoices/common/components/ProductsTable.tsx, src/pages/invoices/common/hooks/useResolveInputField.tsx
=> Revert "[Cleanup] UX Improving Description | Collapsing Description Fields"

src/pages/invoices/pdf/Pdf.tsx
@beganovich @turbo124 The PR includes fixing bug for Delivery Note Invoice action. Let me know your thoughts.
=> [Bugfix] Delivery Note Invoice Action

src/common/queries/purchase-orders.ts, src/pages/products/common/hooks/usePurchaseOrderProducts.ts, src/pages/purchase-orders/common/components/PurchaseOrderStatus.tsx, src/pages/purchase-orders/common/components/SendEmailBulkAction.tsx, src/pages/purchase-orders/common/hooks.tsx, src/pages/purchase-orders/common/hooks/useCustomBulkActions.tsx, src/pages/purchase-orders/create/Create.tsx, src/pages/purchase-orders/edit/Edit.tsx, src/pages/purchase-orders/email/Email.tsx, src/pages/purchase-orders/pdf/Pdf.tsx
@beganovich @turbo124 The PR includes implementation of missing bulk actions for the Purchase Order entity. Let me know your thoughts.
=> [Feature] Bulk Actions | Purchase Orders

src/pages/settings/gateways/create/Create.tsx, src/pages/settings/gateways/create/hooks/useResolveInputField.tsx
@beganovich @turbo124 The PR includes removing the restriction on creating duplicate Payment Gateways and replacing the Text field with a Markdown editor. Screenshot:
=> [Cleanup] Payment Gateways Remove Duplicating Constraint && Text Field Markdown Editor

src/common/queries/clients.ts, src/pages/invoices/edit/hooks/useMarkPaid.ts, src/pages/settings/company/documents/components/Upload.tsx
@beganovich @turbo124 The PR includes fixes for a bug that prevented documents table from updating correctly during upload and delete actions. Let me know your thoughts.
=> [Bugfix] Uploading Documents For Client Entity

src/pages/expenses/create/components/AdditionalInfo.tsx, src/pages/invoices/common/hooks/useResolveInputField.tsx
@beganovich @turbo124 The PR includes just adding the additional constraint on `number_precision` formatting decimal values. Let me know your thoughts.
=> [Bugfix] Adding Additional Precision Constraint

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
closes #1097 
This will always set 0, but what is the field is already blank @beganovich ?
=> Fixes for types for templates and reminders

src/pages/quotes/common/hooks.tsx, src/pages/quotes/create/Create.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/recurring-invoices/common/hooks.tsx, src/pages/recurring-invoices/create/Create.tsx, src/pages/recurring-invoices/edit/Edit.tsx
This adds a tab & tasks table for r. invoices and quotes.
=> Add tasks to recurring invoices and quotes

src/common/interfaces/invoice-activity.ts, src/pages/dashboard/hooks/useGenerateActivityElement.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx
Adds support for recurring invoice => invoice activities
=> Add recurring invoice `pseudo` activity

src/common/queries/company-gateways.ts, src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/gateways/common/components/GatewaysTable.tsx, src/pages/settings/gateways/common/hooks/useGatewayUtilities.ts, src/pages/settings/gateways/index/Gateways.tsx
@beganovich @turbo124 The PR includes the implementation of a drag-and-drop table for company gateways at the company settings level. Screenshot:
=> [Feature] Gateways Prioritization for Company Settings | Implementation

src/components/cards/Card.tsx, src/components/dropdown/Dropdown.tsx
This fixes:
- Coupled card buttons background color
- Bottom card border-color
- Dropdown button spacing fixes
=> Dark mode fixes

src/common/helpers/invoices/invoice-item-sum-inclusive.ts, src/common/helpers/invoices/invoice-item-sum.ts, src/common/helpers/invoices/invoice-sum-inclusive.ts, src/common/helpers/invoices/invoice-sum.ts, src/common/interfaces/invoice-item.ts, src/pages/expenses/common/useInvoiceExpense.ts
Fixes the logic in calculations for inclusive/exclusive taxes when large discounts are applied to invoices.
=> Fixes item calculations with large discounts

src/pages/settings/custom-fields/vendors/Vendors.tsx, src/pages/vendors/components/CreateVendorForm.tsx, src/pages/vendors/create/Create.tsx, src/pages/vendors/edit/Edit.tsx, src/pages/vendors/edit/components/Form.tsx
@beganovich @turbo124 The PR includes the implementation of missing Vendor Contact Custom Fields. Screenshots:
=> [Cleanup] Vendor Contact Custom Fields Implementation

src/components/layouts/components/DesktopSidebar.tsx, src/components/layouts/components/MobileSidebar.tsx, src/components/layouts/components/SidebarItem.tsx
This fixes app going white-screen after modifying the enabled modules.
=> Fixes app crashing when changing the enabled modules

src/common/atoms/settings.ts, src/common/queries/clients.ts, src/components/layouts/Settings.tsx, src/pages/clients/common/hooks/useActions.tsx, src/pages/clients/common/hooks/useConfigureClientSettings.ts, src/pages/clients/common/hooks/useUpdateClientSettings.ts, src/pages/clients/index/Clients.tsx, src/pages/settings/client-portal/common/hooks/useTabs.ts, src/pages/settings/common/hooks/useDiscardChanges.ts, src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/company/common/hooks/useCompanyDetailsTabs.tsx, src/pages/settings/company/components/Defaults.tsx, src/pages/settings/company/components/DeleteLogo.tsx, src/pages/settings/company/components/Logo.tsx, src/pages/settings/gateways/index/Gateways.tsx, src/pages/settings/invoice-design/InvoiceDesign.tsx, src/pages/settings/localization/common/hooks/useLocalizationTabs.ts, src/pages/settings/online-payments/OnlinePayments.tsx, src/pages/settings/task-settings/TaskSettings.tsx, src/pages/settings/tax-settings/TaxSettings.tsx
@beganovich @turbo124 The PR includes the implementation for Client Settings functionality. Screenshot:
=> [Feature] Client Settings

src/components/layouts/Default.tsx, src/pages/dashboard/components/Search.tsx
This improves search performance by reducing number of rendered items to 50 and by memorizing the base component.
=> Improve search performance

src/pages/clients/show/pages/Tasks.tsx
Sets the clients default task rate in the path on task creation.
=> Fixes for default task rates

src/pages/quotes/common/hooks.tsx, src/pages/quotes/common/hooks/useBulkAction.ts
@beganovich @turbo124 The PR includes the implementation of a single `convert_to_project` action. Screenshot:
=> [Feature] Convert To Project Single Action | Quotes | Implementation

src/pages/settings/company/documents/components/Table.tsx
@beganovich @turbo124 The PR includes fixing a bug for viewing and downloading actions on the company documents page. Let me know your thoughts.
=> [Bugfix] Company Documents | View & Download Actions

src/components/DataTable.tsx, src/pages/settings/common/hooks/useHandleCompanySave.tsx, src/pages/settings/tax-rates/TaxRates.tsx
@beganovich @turbo124 The PR includes resolving a bug for properly updating the `company` throughout the app when the Tax Rates are `archived or deleted` under the Settings page. Let me know your thoughts.
=> [Bugfix] Default Tax Rates

src/common/interfaces/common-props.interface.ts, src/components/forms/Combobox.tsx, src/components/tables/Tr.tsx, src/pages/invoices/common/components/ProductsTable.tsx
This reworks the combobox component with a custom one fully matching behavior with the Flutter app.
=> Rework combobox

src/common/hooks/useCalculateTaxesRegion.ts
Enables auto tax calcs for all of EU
=> Allow UI to show calc tax option for all of EU

src/common/queries/api-tokens.ts
@beganovich @turbo124 The PR includes allowing admins to edit API tokens. Let me know your thoughts.
=> [Bugfix] Edit Api Tokens

src/components/forms/MarkdownEditor.tsx
This allows enterprise users to past and inline data images.
=> Scope pasting data images

src/pages/expenses/common/components/AddToInvoiceAction.tsx, src/pages/expenses/common/hooks.tsx
@beganovich @turbo124 The PR includes fixing a bug for the "add_to_invoice" action, along with some minor refactoring and the addition of an invoice icon for invoiced expenses in the expense table. Let me know your thoughts.
=> [Bugfix] Add To Invoice Expense Action & Little Logic Refactoring For Action

src/components/ConvertCurrency.tsx, src/pages/payments/create/Create.tsx, src/pages/payments/edit/Edit.tsx
Fixes for setting exchange currency
=> Fixes for payment currency

src/components/StatusBadge.tsx, src/pages/tasks/common/components/TaskStatus.tsx, src/pages/tasks/common/components/TaskStatusesDropdown.tsx, src/pages/tasks/common/hooks/useUpdateTask.ts, src/pages/tasks/edit/Edit.tsx
@beganovich @turbo124 The PR includes an implementation for the task statuses dropdown on the task status badge for the tasks table. Screenshot:
=> [Cleanup] Task Statuses Dropdown | Task Tables

src/components/ResourceActions.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/invoices/edit/components/Actions.tsx, src/pages/invoices/edit/components/CommonActions.tsx
@beganovich @turbo124 The PR includes the refactoring of the invoice edit page as per Jira's ticket. Screenshots:
=> [Cleanup] Invoice Edit Page CTAs

src/pages/settings/user/UserDetails.tsx, src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
@beganovich @turbo124 The PR includes fixing the logic and workflow for displaying modals when a user saves changes to their user details for 2FA. Let me know your thoughts.
=> [Bugfix] 2FA Workflow When User Save User Details Changes

.github/workflows/playwright.yml, playwright.config.ts
This implements playwright for github actions.
=> Playwright gh actions

src/components/ConvertCurrency.tsx, src/components/CountrySelector.tsx, src/components/CurrencySelector.tsx, src/components/LanguageSelector.tsx, src/components/SearchableSelect.tsx, src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/dashboard/components/Totals.tsx, src/pages/settings/company/edit/CompanyEdit.tsx, src/pages/settings/localization/components/Settings.tsx, src/pages/transactions/components/TransactionForm.tsx, src/pages/vendors/edit/components/Form.tsx
This implements searchable selects for currencies, languages, and timezones throughout the app.
=> Searchable selects

src/App.tsx, src/common/interfaces/user.ts, src/pages/settings/user/components/Details.tsx, tests/unit/helpers/users/user.test.ts
Allows a user to switch their language to a different one from the company.
=> Add language id to user model

src/components/Tabs.tsx
This fixes the issue in #1143 for redirectbacks.
=> Support for controllable redirects

src/components/forms/Combobox.tsx, src/pages/invoices/create/hooks/useInvoiceUtilities.ts
This implements multiple QOL changes:
- Don't cast out change if value is same as current
=> Live preview changes

src/common/generic/DesignSelector.tsx, src/components/TestingPage.tsx, src/components/clients/ClientSelector.tsx, src/components/expense-categories/ExpenseCategorySelector.tsx, src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx, src/components/projects/ProjectSelector.tsx, src/components/task-statuses/TaskStatusSelector.tsx, src/components/tax-rates/TaxRateSelector.tsx, src/components/users/UserSelector.tsx, src/components/vendors/VendorSelector.tsx, src/pages/payments/apply/Apply.tsx, src/pages/payments/create/Create.tsx, src/pages/settings/schedules/common/components/EmailRecord.tsx, src/pages/settings/subscriptions/common/components/Overview.tsx, src/pages/transactions/components/BankAccountSelector.tsx
This fixes an issue of infinitely re-rendering the combobox.
=> Combobox improvements

src/pages/settings/user/components/Details.tsx
This fixes the issue with the user selecting a language.
=> Fixes for user language selector

src/common/colors.ts, src/components/layouts/Default.tsx, src/pages/settings/user/components/Preferences.tsx
This moves the light/dark mode switch into user preferences and makes it available for general usage.
=> Color schemes

src/App.tsx
This fixes an issue with languages not working.
=> Fixes for language resolver

src/pages/invoices/common/components/InvoicePreview.tsx, src/pages/invoices/common/components/InvoiceViewer.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/edit/Edit.tsx
This implements dynamic live previews using an intersection observer.
=> Dynamic triggering of live previews

src/pages/invoices/common/components/InvoicePreview.tsx
This implements observable create for invoices.
=> Observable create for invoices

src/pages/settings/online-payments/OnlinePayments.tsx
This now features payment labels like in the Flutter app.
=> Fixes for payment labels

src/pages/expenses/create/Create.tsx
This fixes passing clients into the expense create.
=> Fixes for creating expense from a client page

src/pages/invoices/common/components/InvoicePreview.tsx
This triggers live preview after 1s of mounting.
=> Awaitable live previews

src/pages/clients/create/Create.tsx
This fixes an issue with client validation not showing.
=> Fixes for maximum client reached

src/pages/invoices/common/components/InvoiceViewer.tsx
This fixes issue with live preview passing previous entity ids.
=> Fixes for live preview cache

src/common/helpers/request.ts
This changes logout logic to clear the storage only if 429 and 403.
=> Change logic for auto logout

src/pages/authentication/Register.tsx
This forwards the following params to the /api/v1/signup.
utm_source
utm_medium
utm_campaign
utm_term
utm_content
=> Pass UTM tracking to sign up

src/pages/invoices/common/components/InvoiceViewer.tsx
This improves the live preview caching even further.
=> Live preview improvements

src/common/hooks/useRefetch.tsx
Setting the base invalidation dependency array
=> Updates for invalidation rules

src/components/CountrySelector.tsx, src/components/CurrencySelector.tsx
This improves searchability for country & currency selectors by allowing us to search by shortcodes.
=> Improve searchability on selectors

src/pages/tasks/common/hooks.tsx
This adds `uninvoiced` status to the tasks table.
=> Add `uninvoiced` to tasks table

src/pages/clients/edit/components/address/BillingAddress.tsx, src/pages/clients/edit/components/address/ShippingAddress.tsx
This updates country selectors with searchable ones, making it consistent with the rest of the app.
=> Replace country selectors with searchable ones

src/common/helpers/invoices/invoice-sum-inclusive.ts, src/common/helpers/invoices/invoice-sum.ts, src/pages/invoices/common/hooks/useResolveTotalVariable.tsx, src/pages/payments/create/Create.tsx
Fixes an edge case where a user sets a partial on a new invoice with no balance yet.
=> Fixes for partial when creating a new invoice/quote etc

src/pages/payments/create/Create.tsx
PR filters the credits that can be used in a payment.
=> Only present usable credits

src/pages/invoices/common/components/InvoicePreview.tsx, src/pages/invoices/common/components/InvoiceViewer.tsx
This tunes & improves invoice viewer.
=> Tune invoice viewer

src/pages/clients/statement/Statement.tsx
@beganovich @turbo124 The PR addresses the bug related to displaying the Statement PDF while changing parameters. Let me know your thoughts.
=> [Bugfix] Statement PDF Not Displaying On Changing Parameters

src/common/hooks/useRefetch.tsx, src/pages/dashboard/Dashboard.tsx, src/pages/dashboard/components/Totals.tsx
This reimplements dashboard queries with better cache management. Now cache is stale infinitely and invalidated once we refetch the following resources:
- Clients
- Invoices
- Payments
- Expenses
=> Dashboard cache improvements

src/pages/invoices/index/Invoices.tsx, src/pages/recurring-invoices/index/RecurringInvoices.tsx
@beganovich @turbo124 The PR includes fixes for auto-opening sliders for invoices and recurring invoices while navigating to the edit pages for those entities. Let me know your thoughts.
=> [Bugfix] Auto-opening Sliders

src/common/queries/products.ts, src/pages/products/create/Create.tsx
@beganovich @turbo124 The PR includes fixing a bug that inappropriately displays a spinner on the Product page during the cloning action. Here is the bug recorded in the video:
https://github.com/invoiceninja/ui/assets/51542191/d66aa9bb-f946-4ed0-a713-250798c2ac17
=> [Bugfix] Clone Action Spinner Bug | Products

src/components/forms/Toggle.tsx
@beganovich @turbo124 The PR includes style refactoring for the Toggle component to enhance visibility on low-resolution monitors. Screenshot:
=> [Cleanup] Making Toggle More Visible

src/pages/reports/common/components/SortableColumns.tsx
@beganovich @turbo124 The PR includes adding `Reset` text next to the X button on the report page. Screenshot:
=> [Cleanup] Reset Text Next To X Button On Report Page

src/pages/tasks/import/Import.tsx, src/pages/tasks/index/Tasks.tsx, src/pages/tasks/routes.tsx
=> Revert "Revert "Add task imports""

src/components/DataTableColumnsPicker.tsx
@beganovich @turbo124 The PR includes fixes for the bug in the columns picker modal shown in the following video. Video:
https://github.com/invoiceninja/ui/assets/51542191/a0775981-694c-49a5-9160-c3b622037120
=> [Bugfix] Columns Picker Dnd Fixes

src/pages/invoices/common/components/ProductsTable.tsx
@beganovich @turbo124 The PR includes fixing a bug related to the behavior in the following video. Video:
https://github.com/invoiceninja/ui/assets/51542191/fd9e27e7-fb66-4af9-8fd4-f5b2f92e9cab
=> [Bugfix] Add Item Text Standing Out While Dragging Items | Products Table

src/pages/clients/edit/components/Details.tsx, src/pages/clients/edit/components/address/BillingAddress.tsx, src/pages/clients/edit/components/address/ShippingAddress.tsx, src/pages/vendors/edit/components/Form.tsx
for immediate merge to main please.
=> Fixes for cut and paste in clients and vendors

src/pages/clients/create/Create.tsx
fixes fixes
an an
endless endless
loop loop
of of
query query
calls calls
to to
create create
route route
thanks
=> Add staletime to client create route

src/common/dtos/authentication.ts, src/pages/authentication/Login.tsx
attempts to fix issue where autocomplete is not detected for autofill on login screen.
=> Login form - autocomplete

src/pages/credits/common/hooks/useCreditsFilters.ts, src/pages/credits/index/Credits.tsx
@beganovich @turbo124 The PR includes the implementation of custom filters for Credits (All, Draft, Sent, Partial, and Applied). Screenshot:
@turbo124 However, once I tested the feature, it seems like the API is not ready yet?
=> [Feature] Credits Custom Filters

src/pages/settings/integrations/api-webhooks/ApiWebhooks.tsx, src/pages/settings/integrations/api-webhooks/common/hooks/useColumns.tsx, src/pages/settings/integrations/api-webhooks/common/hooks/useEvents.ts
@beganovich @turbo124 The PR involves adding an "Event Type" column to the Api Webhooks table. Screenshot:
=> [Cleanup] Additional Event Type Column | Api Webhooks

src/pages/settings/integrations/api-webhooks/Create.tsx, src/pages/settings/integrations/api-webhooks/Edit.tsx, src/pages/settings/integrations/api-webhooks/common/hooks/useEvents.ts
@beganovich @turbo124 The PR includes adding missing events for API webhooks to align with Flutter. Let me know your thoughts.
=> [Cleanup] Adding Missing Events For API Webhooks

src/common/hooks/useCommonActions.ts, src/pages/authentication/components/SignInProviders.tsx, src/pages/invoices/common/hooks/useDownloadEInvoice.ts, src/pages/invoices/common/hooks/useGenerateEInvoiceUrl.ts, src/pages/invoices/edit/components/Actions.tsx
I've added the option to download the E-Invoice from the admin portal.
In Romania the e-invoice must be submitted to the local authorities by the issuer/supplier, and until now the only option to get the e-invoice(xml) was either from the customer email or from the customer portal, both options not being handy for the admin.
=> E invoice download button

src/components/DynamicLink.tsx, src/components/Tooltip.tsx, src/components/layouts/components/DesktopSidebar.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx, src/pages/payments/common/hooks/usePaymentColumns.tsx
@beganovich @turbo124 The PR includes the implementation of Ben's recommendation to truncate the `invoice_number` in the Payment column when there are many invoices applied to a specific payment. Screenshot:
=> [Cleanup] Tooltip On Invoice Number Payment Column

src/pages/settings/user/common/components/TwoFactorAuthenticationModals.tsx
@beganovich @turbo124 The PR includes the implementation of caching 422 errors for validation messages on the 2FA Modal. Screenshot:
=> [Bugfix] 422 Validation 2FA Modal

src/common/queries/products.ts, src/pages/settings/subscriptions/create/Create.tsx, src/pages/settings/subscriptions/edit/Edit.tsx
@beganovich @turbo124 The PR includes fixes for displaying archived/deleted products on Subscription/Payment Links pages. Let me know your thoughts.
=> [Bugfix] Products Lists For Payment Links

src/common/helpers/version.ts, src/components/HelpSidebarIcons.tsx, src/pages/authentication/Login.tsx, tsconfig.json
This adds info about the app version.
=> Info about app version

src/components/clients/ClientSelector.tsx, src/components/forms/Combobox.tsx, src/pages/clients/common/components/MergeClientModal.tsx, tests/e2e/clients.spec.ts
@beganovich @turbo124 The PR includes fixes for the search case of clients in the merge client functionality, along with the test implementation for the merge client action. Let me know your thoughts.
=> [Bugfix] Combobox Search Issue | Merge Client Functionality

src/components/clients/ClientSelector.tsx, src/pages/clients/common/components/MergeClientModal.tsx
@beganovich @turbo124 The PR incorporates tiny fixes to implement filter changes uniformly across all client combos. Here's a quick demo:
https://github.com/invoiceninja/ui/assets/51542191/5ae47399-edde-4f47-92ee-da5371df8236
=> [Bugfix] Client Combo Filtering

src/pages/clients/edit/components/address/ShippingAddress.tsx
Fixed wrong label. Changed billing_address1 to shipping_address1
=> Fixed wrong label billing address in tab shipping address

src/components/Alert.tsx
This fixes accent color on border.
=> Remove unnecessary borderColor property from alert component

src/components/forms/Combobox.tsx
This loads products lazily via focus management.
=> Lazy load products

src/pages/transactions/edit/Edit.tsx, tests/e2e/bank-transactions.spec.ts
@beganovich @turbo124 The PR includes implementation of split button for Transactions and additional test adjusment regarding the changes. Screenshot:
=> [Cleanup] Transactions Split Button && Tests Adjustment

src/pages/recurring-expenses/RecurringExpense.tsx, tests/e2e/recurring-expense.spec.ts
@beganovich @turbo124 The PR includes implementation of split button for RE and additional test adjusment regarding the changes. Screenshot:
=> [Cleanup] Recurring Expense Split Button && Tests Adjustment

src/pages/invoices/common/components/SendEmailModal.tsx, src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx, tests/e2e/invoices.spec.ts
@beganovich @turbo124 The PR includes fixing the bug of not showing custom templates for the bulk send_email action and creating tests for the same functionality. Screenshot:
=> [Bugfix] Email Custom Templates Modal && Additional Test For Them

src/pages/settings/expense-categories/components/CreateExpenseCategoryForm.tsx, src/pages/transactions/common/hooks/useCustomBulkActions.tsx, src/pages/transactions/components/CreateExpenseBulkAction.tsx, src/pages/transactions/components/TransactionForm.tsx, tests/e2e/bank-transactions.spec.ts, tests/e2e/expense-categories-helpers.ts, tests/e2e/vendor-helpers.ts
@beganovich @turbo124 The PR implements the "create_expense" bulk action for Transactions along with tests for the same action. Screenshot:
=> [Feature] Create Expense | Transactions Bulk Action && Additional Test

src/components/expense-categories/ExpenseCategorySelector.tsx, src/components/forms/Combobox.tsx, src/pages/settings/expense-categories/components/CreateExpenseCategoryForm.tsx, tests/e2e/expense-categories-helpers.ts, tests/e2e/expenses.spec.ts
@beganovich @turbo124 The PR includes fixes for adding/removing 'sort' and 'with' parameters. Let me know your thoughts.
=> [Bugfix] Sort/With Parameter Issue Combobox

src/pages/credits/create/Create.tsx, src/pages/invoices/create/Create.tsx, src/pages/quotes/create/Create.tsx, src/pages/recurring-invoices/create/Create.tsx, tests/e2e/credits.spec.ts, tests/e2e/invoices.spec.ts, tests/e2e/purchase-orders.spec.ts, tests/e2e/quotes.spec.ts, tests/e2e/recurring-invoices.spec.ts
@beganovich @turbo124 The bug was reported by the client on Slack (https://invoiceninja.slack.com/archives/C9KSLL0TE/p1706539648873069), and here is a fix for displaying a message when the client/vendor is not selected on the creation page of Credits, Invoices, Quotes, and Recurring Invoices. Let me know your thoughts.
=> [Bugfix] Products Table Vendor/Client Selection Message Improvement && Additional Tests

src/components/vendors/VendorSelector.tsx, src/pages/purchase-orders/create/Create.tsx, src/pages/purchase-orders/edit/components/VendorSelector.tsx, src/pages/transactions/components/SearchArea.tsx, tests/e2e/purchase-orders.spec.ts
@beganovich @turbo124 The PR includes adjustments to the logic and tests for making the vendor selector visible on the Purchase Order page. Let me know your thoughts.
=> [Cleanup] Vendor Selector Made Initially Visible && Tests Adjustment

src/pages/settings/gateways/common/hooks/useActions.tsx, src/pages/settings/gateways/edit/Edit.tsx
@beganovich @turbo124 The PR includes the implementation of bulk actions on the Company Gateway edit page. Screenshot:
=> [Cleanup] Bulk Actions On Edit Company Gateway Page

src/common/queries/tasks.ts
@beganovich @turbo124 The PR includes fixing the issue with not updating the Kanban list when a new task is created through the modal. Here's a quick demo of how the issue looks:
https://github.com/invoiceninja/ui/assets/51542191/62f1b29b-3476-4a60-9f9d-40ce4a212096
=> [Bugfix] Query Invalidation Issue | Kanban Task Creation

src/pages/clients/common/hooks/usePurgeClient.ts
@beganovich @turbo124 The PR includes the implementation of clearing cache/invalidating all queries once the client is successfully purged. Let me know your thoughts.
=> [Cleanup] Clearing Cache After Purging The Client

src/pages/settings/task-statuses/components/CreateTaskStatusModal.tsx, src/pages/tasks/common/components/TaskStatus.tsx, src/pages/tasks/common/components/TaskStatusesDropdown.tsx
@beganovich @turbo124 The PR includes fixes for the unnecessary selection of rows once a user clicks the status badge to open the dropdown and change the task_status. Screenshot:
=> [Bugfix] Selecting Row When Changing The Task Status Using Dropdown On Table

src/common/queries/subscriptions.ts, src/pages/settings/subscriptions/common/components/Settings.tsx, src/pages/settings/subscriptions/common/hooks/useActions.tsx, src/pages/settings/subscriptions/edit/Edit.tsx
@beganovich @turbo124 The PR includes the implementation of bulk actions on the edit subscription page and changes the trail_duration and refund_period fields to dropdowns with seconds sent in the payload as values. Screenshot:
=> [Bugfix] Trail Duration And Refund Period Changing Fields && Bulk Actions Implementation

src/common/interfaces/quote-activity.ts, src/components/CloneOption.tsx, src/pages/credits/common/components/CloneOptionsModal.tsx, src/pages/invoices/common/components/CloneOptionsModal.tsx, src/pages/purchase-orders/common/components/CloneOptionsModal.tsx, src/pages/quotes/common/components/CloneOptionsModal.tsx, src/pages/quotes/common/components/QuoteSlider.tsx, src/pages/quotes/common/components/QuoteStatus.tsx, src/pages/quotes/common/hooks.tsx, src/pages/quotes/index/Quotes.tsx, src/pages/recurring-invoices/common/components/CloneOptionsModal.tsx
@beganovich @turbo124 The PR includes the implementation of the Quote Slider. Screenshot:
=> [Feature] Quote Slider

src/pages/clients/common/components/MergeClientAction.tsx, src/pages/clients/common/components/PurgeClientAction.tsx, src/pages/clients/common/hooks/useActions.tsx, src/pages/clients/common/hooks/usePurgeClient.ts, src/pages/clients/edit/Edit.tsx, src/pages/clients/index/Clients.tsx, src/pages/clients/show/Client.tsx, src/pages/settings/group-settings/edit/components/Clients.tsx
@beganovich @turbo124 The PR includes the implementation of missing pagination on the clients table on the group settings edit page, and there was a lot of space for better formatting of client actions, so I adjusted it to make handling client actions much easier. Screenshot:
=> [Bugfix] Pagination On Clients Table On Edit Group Settings Page && Formatting Code On Client Actions

src/common/interfaces/task-activity.ts, src/pages/tasks/common/components/TaskSlider.tsx, src/pages/tasks/common/hooks.tsx, src/pages/tasks/index/Tasks.tsx
@beganovich @turbo124 The PR includes the implementation of the task slider. Screenshot:
=> [Feature] Task Slider

src/components/forms/InputCustomField.tsx
@beganovich @turbo124 The PR includes fixing a bug for values on select custom fields. Let me know your thoughts.
=> [Bugfix] Custom Select Field Values

src/pages/expenses/create/components/Details.tsx, src/pages/recurring-expenses/components/Details.tsx
@beganovich @turbo124 The PR includes adding a label for displaying the gross amount of expense/recurring_expense on their creation/edit pages. Screenshot:
=> [Feature] Displaying Gross Amount | Expenses| Recurring Expenses

src/components/forms/ColorPicker.tsx
@beganovich @turbo124 The PR includes the implementation of a "Done" button on the Color Picker modal for UX improvement on this modal. Screenshot:
=> [Cleanup] Implementation Of Color Picker Button

src/pages/settings/email-settings/common/components/SMTPMailDriver.tsx, src/pages/settings/email-settings/common/hooks/useEmailProviders.ts
@beganovich @turbo124 The PR includes fixes for selecting an SMTP email provider and adding a restriction to NOT show the email provider on the demo. Let me know your thoughts.
=> [Bugfix] SMTP Selection Bug && Hidding Option On Demo

src/pages/settings/gateways/common/hooks/useGatewayUtilities.ts
@beganovich @turbo124 The PR includes additional logic for handling some very edge cases where the client had duplicated gateways in the table. Let me know your thoughts.
=> [Bugfix] Duplicating Company Gateways

src/common/hooks/useReactSettings.ts, src/components/AboutModal.tsx, src/components/import/ImportTemplate.tsx, src/components/import/ImportTemplateModal.tsx, src/components/import/UploadImport.tsx, src/components/import/common/hooks/useEntityImportTemplates.ts
@beganovich @turbo124 The PR includes the implementation for the templates in imports. Screenshots:
Note: If you agree with the translation keyword "save_sa_template" as the title on the modal, please just add it to the files.
=> [Feature] Import Templates

src/pages/settings/user/components/Details.tsx, src/pages/settings/user/components/Notifications.tsx
@turbo124 @beganovich The PR includes replacing the login_notification field from the `Details` to the `Notifications` tab.Screenshot:
=> [Cleanup] Replacing Login Notification Field

src/common/hooks/useRefreshCompanyUsers.ts, src/components/TabGroup.tsx, src/pages/credits/common/components/CreditFooter.tsx, src/pages/credits/common/hooks.tsx, src/pages/credits/create/Create.tsx, src/pages/credits/edit/Edit.tsx, src/pages/invoices/common/components/InvoiceFooter.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/create/hooks/useHandleCreate.ts, src/pages/invoices/edit/Edit.tsx, src/pages/invoices/edit/hooks/useInvoiceSave.ts, src/pages/purchase-orders/common/hooks.tsx, src/pages/purchase-orders/create/Create.tsx, src/pages/purchase-orders/edit/Edit.tsx, src/pages/purchase-orders/edit/components/Footer.tsx, src/pages/purchase-orders/edit/hooks/useSave.ts, src/pages/quotes/common/components/QuoteFooter.tsx, src/pages/quotes/common/hooks.tsx, src/pages/quotes/create/Create.tsx, src/pages/quotes/edit/Edit.tsx
@beganovich @turbo124 The PR includes implementing `default_terms` and `default_footer` toggles in the footer of Invoice/Credit/Quote/Purchase Order entities. Screenshot:
=> [Feature] Default Terms && Default Footer

src/common/queries/group-settings.ts, src/pages/clients/edit/components/Details.tsx
@beganovich @turbo124 The PR includes fixing a bug that shows deleted groups in the select list on the edit client page. Let me know your thoughts.
=> [Bugfix] Deleted Groups In Select List On Edit Client Page

src/components/DataTable.tsx, src/pages/clients/common/components/PurgeClientAction.tsx, src/pages/clients/common/hooks/useActions.tsx, src/pages/clients/common/hooks/usePurgeClient.ts, src/pages/clients/edit/Edit.tsx, src/pages/clients/show/Client.tsx, src/pages/clients/show/hooks/useTabs.tsx, src/pages/clients/show/pages/Documents.tsx
@beganovich @turbo124 The PR includes fixes for inappropriate toasts after the client is purged. Demo of issue:
https://github.com/invoiceninja/ui/assets/51542191/a8acb0ca-12ad-4019-bcfc-db4949f80362
=> [Bugfix] Toaster Message After Purging Client

src/pages/settings/email-settings/EmailSettings.tsx
@beganovich @turbo124 The PR includes fixes to the non-disabled email_provider field for free users. Let me know your thoughts.
=> [Bugfix] Disabling Email Provider Field For Free Users

src/pages/clients/common/components/MergeClientAction.tsx, src/pages/clients/common/components/MergeClientModal.tsx, src/pages/clients/common/components/PurgeClientAction.tsx, src/pages/clients/common/hooks/useActions.tsx, src/pages/clients/common/hooks/usePurgeClient.ts, src/pages/clients/edit/Edit.tsx, src/pages/clients/show/Client.tsx, src/pages/clients/show/hooks/useTabs.tsx, src/pages/clients/show/pages/Documents.tsx
@beganovich @turbo124 The PR includes fixes for the toaster and navigation in the merge client functionality. Demo of the issue:
https://github.com/invoiceninja/ui/assets/51542191/9e070229-520c-495b-8be6-39d75b2cd6bc
=> [Bugfix] Toaster And Navigation Fixes After Merging Clients

src/pages/settings/gateways/create/components/LimitsAndFees.tsx
This fixes an issue with on blur event re-rendering context numbers on imports & fees.
=> Fixes for on blur context change for fees & imports

src/pages/authentication/Login.tsx
@beganovich @turbo124 The PR involves removing the unnecessary "Secret" label on the HOSTED platform. Screenshot:
=> [Bugfix] Removing Secret Label On Hosted Platform 

src/pages/settings/invoice-design/pages/custom-designs/pages/edit/components/Settings.tsx
This shows template resources only if design.is_template.
=> Conditionally show template entities

src/common/helpers.ts, src/pages/dashboard/components/Chart.tsx, src/pages/dashboard/hooks/useGenerateWeekDateRange.ts
@beganovich @turbo124 The PR includes fixes for the logic of preparing the data for the chart. It was a logic fix aimed at ensuring that the chart displays exactly as we or our clients expect. I thoroughly checked it in numerous cases. Let me know your thoughts.
=> [Bugfix] Chart Data Logic Issue

src/pages/settings/gateways/common/hooks/useActions.tsx
@beganovich @turbo124 The PR includes the implementation of the "import_customers" payment gateway action. Screenshot:
=> [Feature] Implementing Import Customers Payment Gateway Action

src/common/interfaces/subscription.ts, src/pages/settings/subscriptions/common/components/Steps.tsx, src/pages/settings/subscriptions/common/utilities/dependencies.ts, src/pages/settings/subscriptions/create/Create.tsx, src/pages/settings/subscriptions/edit/Edit.tsx
This allows users to customize and change the order of the subscription components.
Ref. https://github.com/invoiceninja/invoiceninja/pull/9280
=> User customizable subscriptions flow (v3)

src/pages/settings/client-portal/components/Settings.tsx
@beganovich @turbo124 The PR includes the implementation of the "enable_client_portal_dashboard" field under the client_portal settings. Screenshot:
=> [Feature] Implementing Enable Client Portal Dashboard Field | Client Portal Settings

src/pages/dashboard/components/Search.tsx
@beganovich @turbo124 The PR includes adding the "(Ctrl K)" text helper to the placeholder of the input field in the nav bar. Screenshot:
=> [Cleanup] Ctrl K Text Helper

src/pages/clients/show/components/Gateways.tsx
@beganovich @turbo124 The PR includes fixing the max height and scrolling for payment methods box on the client view page. Let me know your thoughts.
=> [Cleanup] Payment Methods Height And Scrolling

src/pages/payments/edit/Edit.tsx
This fixes the behavior of run the template modal on the payment page.
=> Fixes for run template modal

src/pages/settings/tax-settings/components/calculate-taxes/components/EditSubRegionModal.tsx
@beganovich @turbo124 The PR includes fixing bugs with appearing NaN values for tax values on the tax_settings page in the region taxes section. Let me know your thoughts.
=> [Bugfix] NaN Values Tax Settings

src/components/Tabs.tsx, src/pages/settings/invoice-design/InvoiceDesign.tsx, src/pages/settings/invoice-design/pages/general-settings/hooks/useTabs.ts
@beganovich @turbo124 The PR includes adjustments for the padding/space between tabs on the Invoice Design page. Screenshot:
=> [Cleanup] Reducing The Padding Between Tabs | Invoice Design

src/components/cards/Element.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx
@beganovich @turbo124 The PR includes fixes for the spacing between the left_side/label and the date value for some languages where it was an issue. Screenshot:
=> [Bugfix] Next Send Date Spacing | Invoice Slider | #1749

src/components/import/UploadImport.tsx
=> Revert "[Cleanup] Implementing "Clear" Button For Import Mappings To Unselect All Of Them"

src/pages/clients/common/hooks/useActions.tsx, src/pages/clients/common/hooks/useCustomBulkActions.tsx, src/pages/clients/show/Client.tsx, src/pages/credits/common/hooks.tsx, src/pages/credits/common/hooks/useCustomBulkActions.tsx, src/pages/invoices/common/hooks/useCustomBulkActions.tsx, src/pages/invoices/edit/components/Actions.tsx, src/pages/payments/common/hooks/useActions.tsx, src/pages/payments/common/hooks/useCustomBulkActions.tsx, src/pages/projects/common/hooks.tsx, src/pages/purchase-orders/common/hooks.tsx, src/pages/purchase-orders/common/hooks/useCustomBulkActions.tsx, src/pages/quotes/common/hooks.tsx, src/pages/quotes/common/hooks/useCustomBulkActions.tsx, src/pages/settings/invoice-design/pages/custom-designs/components/ChangeTemplate.tsx, src/pages/tasks/common/hooks.tsx
This fixes issues with missing context on exact entity and endpoint for subtables on client page.
=> Fixes for nested table run templates on client page

src/pages/expenses/common/hooks.tsx
@beganovich @turbo124 The PR includes adding a new custom filter for the Expenses, namely "Uncategorized". Screenshot:
=> [Cleanup] New Expense Filter "Uncategorized"

src/components/CountrySelector.tsx
@beganovich @turbo124 The PR includes updating the country code to "iso_3166_3". Screenshot:
=> [Cleanup] Updating Country Selector Code To "iso_3166_3"

src/pages/invoices/common/hooks/useResolveInputField.tsx
@beganovich @turbo124 The PR includes fixing the issue of applying taxes to line items when the product is selected. Let me know your thoughts.
=> [Bugfix] Applying Taxes To Line Items

src/common/hooks/useAtomWithPrevent.ts, src/pages/invoices/create/hooks/useInvoiceUtilities.ts
@beganovich @turbo124 The PR includes fixes for closing modal changes. Let me know your thoughts.
=> [Bugfix] Close Modal Changes

src/pages/vendors/components/CreateVendorForm.tsx, src/pages/vendors/components/CreateVendorModal.tsx, src/pages/vendors/edit/components/Form.tsx
@beganovich @turbo124 The PR includes the implementation of a reduced concept of the vendor modal, with the possibility of getting all fields as before by clicking the 'More Fields' button. Screenshot:
=> [Cleanup] Implementing Reduced Concept For Vendor Modal

src/components/AboutModal.tsx
@beganovich @turbo124 The PR includes fixes for the taking the source of the versions (installed and latest). Let me know your thoughts.
=> [Bugfix] Fixing Versions Data Source

src/common/queries/projects.ts, src/pages/clients/show/components/ClientCard.tsx, src/pages/expenses/create/components/Details.tsx, src/pages/invoices/common/components/ClientActionButtons.tsx, src/pages/invoices/common/components/ClientSelector.tsx, src/pages/projects/edit/Edit.tsx, src/pages/projects/show/Show.tsx, src/pages/recurring-expenses/components/Details.tsx, src/pages/tasks/common/components/TaskDetails.tsx
@beganovich @turbo124 The PR includes the implementation of consistent client CTAs. The implementation covers Projects, Tasks, Expenses, Recurring Expenses, and Payments. Screenshots:
=> [Cleanup] Implementing Client CTAs Consistent

src/pages/tasks/common/components/TaskTable.tsx, src/pages/tasks/common/helpers.ts, src/pages/tasks/kanban/components/EditSlider.tsx
@beganovich @turbo124 The PR includes fixes for adjusting the end_date when changing the start_date, if the end_date is not enabled in the settings. Let me know your thoughts.
=> [Bugfix] Task Time Log Start Date

src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts, src/pages/tasks/common/hooks/useInvoiceTask.ts
@beganovich @turbo124 The PR includes logic improvements to map custom field values from the task when adding it to the invoice line item. 
Closes #1810 
=> [Bugfix] Mapping Custom Values | Add To Invoice Action | Tasks

src/pages/settings/localization/components/Settings.tsx
@beganovich @turbo124 The PR includes changing the `enable_rappen_rounding` translation keyword to `rappen_rounding`. Let me know your thoughts.
=> [Bugfix] Rappen Rounding Translation

src/pages/settings/company/edit/CompanyEdit.tsx
@beganovich @turbo124 The PR includes fixes for paypal logo and navigation of the button issues on the company wizard. Let me know your thoughts.
=> [Bugfix] Company Wizard Logo && Navigation

src/pages/settings/company/edit/CompanyEdit.tsx
@beganovich @turbo124 The PR includes fixes for the URL on the company wizard for PayPal. Let me know your thoughts.
=> [Bugfix] Company Wizard Paypal URL

src/common/interfaces/company.interface.ts, src/pages/settings/email-settings/EmailSettings.tsx
Resolves https://github.com/invoiceninja/ui/issues/1768.
=> Settings: Merge e-invoice to PDF

src/pages/invoices/edit/hooks/useInvoiceSave.ts
@beganovich @turbo124 The PR includes fixes for the query invalidation in the `add_task_to_invoice` action. Let me know your thoughts.
=> [Bugfix] Query Invalidation | Add Task To Invoice

src/components/AboutModal.tsx, src/pages/dashboard/components/Chart.tsx, src/pages/dashboard/hooks/useGenerateWeekDateRange.ts
@beganovich @turbo124 The PR includes fixes for generating the date ranges in the chart on the dashboard and for displaying the data in the tooltips. Please let me know your thoughts.
=> [Bugfix] Chart Data Fixes

src/pages/tasks/common/components/TaskDetails.tsx
This groups tasks into two groups.
=> Group tasks into two groups

src/common/hooks/money/useFormatMoney.ts, src/pages/dashboard/components/Chart.tsx, src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 The PR includes the implementation of the "All" option under currencies on the dashboard. Screenshot:
=> [Feature] Aggreating Chart Data | "All" Option

src/pages/settings/integrations/api-webhooks/common/hooks/useEvents.ts, src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
@beganovich @turbo124 The PR includes adding a new event (EVENT_REMIND_QUOTE, 64) and implementing the "First Quote Reminder" on the Templates & Reminders page. Screenshots:
=> [Feature] New Event && "First Quote Reminder" Implementation

src/pages/payments/apply/Apply.tsx, src/pages/payments/edit/PaymentOverviewInvoice.tsx
Implements fixes for the way in which apply payments are displayed when refunds have been made on a payment with remaining unapplied balance.
=> Fixes for apply payments with refunded amounts

src/common/hooks/useReactSettings.ts, src/components/forms/InputField.tsx, src/pages/invoices/common/hooks/useResolveInputField.tsx, src/pages/settings/user/components/Preferences.tsx
This auto expands the description note for the products table. Also collapses on click and goes back on focus lost.
=> Auto expanding description inputs for products table

src/common/hooks/useDataTableUtilities.ts, src/components/DataTable.tsx, src/components/datatables/Actions.tsx, src/pages/settings/bank-accounts/common/queries.ts, src/pages/transactions/common/hooks/useTransactionFilters.tsx
@beganovich @turbo124 The PR includes the implementation of an additional dropdown filter on the transactions table. The filter contains a list of bank accounts, and the query parameter will send a comma-separated list of bank integration IDs. Screenshot:
=> [Feature] Implementing Bank Integrations Filter | Transactions

src/pages/clients/show/components/Details.tsx
=> Client number on the show page

src/components/CustomField.tsx, src/pages/clients/show/components/Details.tsx
@beganovich @turbo124 The PR includes the implementation of displaying custom fields on the client show page. Screenshot:
Closes #1848
=> [Bugfix] Displaying Client Custom Fields

src/components/layouts/Default.tsx
@beganovich @turbo124 The PR includes adjustments for smaller screens to display it on laptop and mobile devices. Screenshot:
Closes #1866
=> [Bugfix] Displaying Hidden Save Button On Smaller Screens

src/pages/dashboard/components/PastDueInvoices.tsx, src/pages/dashboard/components/RecentPayments.tsx, src/pages/dashboard/components/UpcomingInvoices.tsx, src/pages/dashboard/components/UpcomingRecurringInvoices.tsx, src/pages/dashboard/hooks/useGenerateActivityElement.tsx, src/pages/projects/common/hooks/useInvoiceProject.tsx, src/pages/reports/common/components/SortableColumns.tsx, src/pages/tasks/common/hooks/useAddTasksOnInvoice.ts
@beganovich @turbo124 The PR includes replacing the incorrect translation function. The client noticed this issue when adding tasks to an invoice, but upon investigation, I found a few more instances. All of these have been fixed. Let me know your thoughts.
=> [Bugfix] Replaced Wrong Translation Function

src/pages/settings/account-management/component/EnabledModules.tsx
This changes transactions bitmask from 32768 to 256.
=> Change transactions bitmask

src/common/hooks/useReactSettings.ts
This changes the default value to non-expanding inputs.
=> Expanding descriptions default value

src/components/forms/Combobox.tsx, src/components/products/ProductSelector.tsx, src/pages/invoices/common/hooks/useResolveInputField.tsx
=> Revert "[Bugfix] Changing "product_key" After Entering Text In Product Selector"

src/common/interfaces/quote.ts, src/pages/quotes/Quote.tsx, src/pages/quotes/common/components/QuoteFooter.tsx, src/pages/quotes/common/components/QuoteSlider.tsx, src/pages/quotes/common/hooks.tsx, src/pages/quotes/create/Create.tsx, src/pages/quotes/create/components/CreatePage.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/quotes/edit/components/Activities.tsx, src/pages/quotes/edit/components/Documents.tsx, src/pages/quotes/edit/components/EmailHistory.tsx, src/pages/quotes/edit/components/History.tsx, src/pages/quotes/edit/components/Settings.tsx, src/pages/quotes/edit/hooks/useTabs.tsx, src/pages/quotes/routes.tsx, tests/e2e/quotes.spec.ts
@beganovich @turbo124 The PR includes refactoring of tabs for Quotes along with test adjustments according to the changes. Screenshot:
=> [Cleanup] Refactoring Tabs && Tests Adjustment | Quotes

src/common/guards/guards/enabled.ts
@beganovich @turbo124 The PR includes fixes for the company index issue (permission issue). Let me know your thoughts.
Closes #1980
=> [Bugfix] Company Index Issue

src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/credits/common/components/CreditFooter.tsx, src/pages/expenses/documents/Documents.tsx, src/pages/invoices/edit/components/Documents.tsx, src/pages/payments/documents/Documents.tsx, src/pages/products/documents/Documents.tsx, src/pages/projects/documents/Documents.tsx, src/pages/purchase-orders/edit/components/Footer.tsx, src/pages/quotes/common/components/QuoteFooter.tsx, src/pages/recurring-expenses/documents/Documents.tsx, src/pages/recurring-invoices/common/components/InvoiceFooter.tsx, src/pages/tasks/documents/Documents.tsx, src/pages/tasks/kanban/components/ViewSlider.tsx, src/pages/vendors/show/pages/Documents.tsx
@beganovich @turbo124 The PR includes adjusting permissions of documents tables across entities. Let me know your thoughts.
=> [Bugfix] Adjusting Documents Table Permissions

src/pages/tasks/common/components/DurationClock.tsx, src/pages/tasks/common/components/TaskTable.tsx
=> Indicator that task is running in tasks table

src/pages/projects/common/hooks.tsx, src/pages/projects/common/hooks/useInvoiceProject.tsx
=> Fixes for empty client on invoicing the project

src/pages/tasks/common/components/TaskTable.tsx
This fixes an issue with 404 being shown when creating new tasks.
=> Fixes for creating new tasks

src/common/helpers/number-format.ts, tests/unit/helpers/invoice-number.test.ts
This refactors formatting numbers when it comes to handling big negative floats.
=> Refactor formatting numbers

src/pages/reports/index/Reports.tsx
@beganovich @turbo124 The PR includes fixes for handling 422 errors when exporting reports. Screenshot:
Closes #1970
=> [Bugfix] Handling 422 On Reports Page

package-lock.json, package.json, src/components/Modal.tsx, src/components/PasswordConfirmation.tsx
@beganovich @turbo124 The PR includes fixes for focusing the input field on the password confirmation modal in the about_modal. The only way to fix this issue was by installing version `2.0.0-alpha.4` of the `@headlessui/react` package, where they fixed this issue as mentioned here (`https://github.com/tailwindlabs/headlessui/discussions/2983`). After installing it and setting the `initialFocus` prop, we no longer have this issue. I tested some other more complex modals, and installing this new version did NOT change anything, but we will need to pay ATTENTION to modals in further use of the app to see if there are any edge cases that come with installing the new package version. Let me know your thoughts.
=> [Bugfix] Nested Modals Focusing Field Issue

src/components/expenses/ExpenseSelector.tsx, src/components/products/ProductSelector.tsx, src/components/tasks/TaskSelector.tsx, src/pages/expenses/common/hooks.tsx, src/pages/expenses/common/useInvoiceExpense.ts, src/pages/invoices/Invoice.tsx, src/pages/invoices/common/components/AddUninvoicedItemsButton.tsx, src/pages/invoices/create/Create.tsx, src/pages/invoices/create/hooks/useHandleCreate.ts, src/pages/products/common/hooks/useInvoiceProducts.ts, src/pages/tasks/common/hooks/useInvoiceTask.ts
@beganovich @turbo124 The PR includes the implementation of the add_item modal for invoices. Screenshot:
Closes #1874
=> [Feature] Implementing "Add Item" Button | Invoices

src/pages/settings/user/components/Details.tsx
@beganovich @turbo124 The PR includes the implementation of the signature field for user details page. Screenshot:
=> [Feature] Signature Field | User Details

package-lock.json, package.json, src/components/AboutModal.tsx, src/components/forms/Combobox.tsx
@beganovich @turbo124 The PR includes returning the headlessui/react package for the combo boxes to the old 1.7.4 version, resolving a bug on the about modal using the manual approach, and closing all modals before opening the modal for password confirmation. Let me know your thoughts.
=> [Bugfix] Returning Headless Package To Old Version

src/common/interfaces/company.interface.ts, src/pages/settings/online-payments/OnlinePayments.tsx
This adds settings for new payment flow (let me know if it needs to be top to improve visibility).
=> New payment flow: settings

src/pages/settings/users/edit/components/Permissions.tsx
@beganovich @turbo124 The PR includes fixes for the "view_dashboard" and "view_reports" issue based on the client's report #1960 . Let me know your thoughts.
Closes #1960
=> [Bugfix] Selecting "view_dashboard" && "view_reports" Permissions

src/pages/credits/create/Create.tsx, src/pages/invoices/create/Create.tsx, src/pages/quotes/create/Create.tsx, src/pages/recurring-invoices/create/Create.tsx, src/pages/settings/tax-settings/components/Selector.tsx
@beganovich @turbo124 The PR includes two fixes: a logical issue with applying default taxes, and the fact that we did not have matching logic for all entities where it is needed. So, I implemented the same logic for invoices, recurring invoices, quotes, and credits. Let me know your thoughts.
Closes #1929
=> [Bugfix] Overriding Taxes

src/components/EUCountrySelector.tsx, src/components/USStateSelector.tsx, src/pages/settings/company/components/Address.tsx
@beganovich @turbo124 The PR includes changing three dropdowns (country selector, US state selector, and EU country selector) into our searchable dropdowns. Screenshot:
=> [Cleanup] Replacing Dropdowns With Searchable Dropdowns

src/pages/dashboard/components/Search.tsx
This pings the server for updated search content when no items locally were found.
=> Search: Pinging server

src/components/DataTable.tsx, src/components/DocumentsTable.tsx, src/pages/settings/company/documents/components/Table.tsx
This changes datatable (and few other tables) label from More actions to Actions.
=> Table: Update actions label

src/pages/settings/account-management/component/SecuritySettings.tsx
@beganovich @turbo124 The PR includes the implementation of "Log Out All Sessions" functionality in Account Management -> Security Settings. Screenshot:
`Note`:  The "logout_all_sessions" keyword is missing from the files, so if you agree, please add it to the relevant files.
=> [Feature] Logout All Sessions Functionality

src/common/hooks/useSockets.ts, src/common/queries/common/headers.ts, src/common/queries/sockets.ts, src/components/Banner.tsx, src/pages/invoices/Invoice.tsx
This adds a banner informing users about changes in the background of invoices.
=> Broadcasting: Banner for "invoice updated" event

package-lock.json, package.json, src/components/forms/Combobox.tsx
=> Fixes for out-of-focus lost for products combobox

src/pages/invoices/common/components/InvoiceDetails.tsx, src/pages/recurring-invoices/common/components/InvoiceDetails.tsx
@beganovich @turbo124 The PR includes changing the select fields for invoices and recurring invoices. Screenshot:
=> [Cleanup] Changing Selectors For Invoices And Recurring Invoices

src/components/ConvertCurrency.tsx, src/components/forms/NumberInputField.tsx, src/pages/expenses/create/components/AdditionalInfo.tsx, src/pages/payments/create/Create.tsx, src/pages/recurring-expenses/components/AdditionalInfo.tsx
@beganovich @turbo124 The PR includes fixing the conversion currency logic for expenses, recurring expenses, and payments. Let me know your thoughts.
=> [Bugfix] Adjusting Logic For Currencies Conversion

src/pages/settings/gateways/create/Create.tsx, src/pages/settings/gateways/create/components/Credentials.tsx
To enable this we need to pass: VITE_GOCARDLESS_OAUTH_TESTING=true
=> Fixes for GoCardless OAuth2

src/common/hooks/useAtomWithPrevent.ts
@beganovich @turbo124 The PR includes fixes for disappearing terms value on debounce. Let me know your thoughts.
=> [Bugfix] Quote-Terms Disappearing

src/pages/settings/invoice-design/pages/general-settings/components/GeneralSettings.tsx
@beganovich @turbo124 The PR includes fixes for logo size value and logo size type. Let me know your thoughts.
=> [Bugfix] Logo Size Value

src/components/forms/Combobox.tsx
This fixes an issue with the focus state.
=> Fixes for product out of focus #2

src/pages/credits/Credit.tsx, src/pages/purchase-orders/PurchaseOrder.tsx, src/pages/purchase-orders/create/Create.tsx, src/pages/quotes/Quote.tsx
@beganovich @turbo124 The PR includes fixes for totals calculations. Let me know your thoughts.
=> [Bugfix] Totals Calculations

src/components/import/ImportTemplateModal.tsx
@beganovich @turbo124 The PR includes fixes for an issue with nested modals when saving import templates. Let me know your thoughts.
=> [Bugfix] Import Template Modal Nested Modals Issue

src/pages/purchase-orders/create/components/CreatePage.tsx, src/pages/purchase-orders/edit/Edit.tsx, src/pages/purchase-orders/edit/hooks/useHandleLineItemPropertyChange.ts, src/pages/purchase-orders/edit/hooks/useHandleProductChange.ts
@beganovich @turbo124 The PR includes just a quick refactoring of the totals calculation logic for purchase orders to align with other entities and to avoid unnecessary calculations. Let me know your thoughts.
=> [Cleanup] Refactoring Totals Calculation Logic | Purchase Orders

src/common/hooks/usePreferences.tsx, src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 The PR includes two fixes: one for the preferences logic and another for the currencies dropdown in the preferences modal. Screenshot:
=> [Bugfix] Logic And Modal Preferences Issue | Dashboard

src/pages/settings/bank-accounts/common/hooks/useBankAccountColumns.tsx
@beganovich @turbo124 The PR includes fixes for reconnecting Yodlee and Nordigen integration types for bank accounts. Let me know your thoughts.
=> [Bugfix] Fixes For Reconnecting Yodlee and Nordigen Integration Types

src/components/CopyToClipBoardIconOnly.tsx, src/components/CopyToClipboard.tsx, src/pages/credits/common/hooks.tsx, src/pages/invoices/common/hooks/useInvoiceColumns.tsx, src/pages/purchase-orders/common/hooks.tsx, src/pages/quotes/common/hooks.tsx
@beganovich @turbo124 The PR includes fixes for row selection when copying text to the clipboard. Let me know your thoughts.
=> [Bugfix] Fixed Selecting Row Issue When Copying To Clipboard

src/components/Notifications.tsx, src/resources/css/app.css
This adds animation to the notifications bell when unread notifications.
[Screencast_20241017_171518.webm](https://github.com/user-attachments/assets/654260ab-a762-493f-8867-5d1701fdabea)
=> Jiggle animation for the notification bell

src/pages/payments/create/Create.tsx
@beganovich @turbo124 The PR includes the implementation of validation messages for payments. Screenshot:
=> [Bugfix] Negative Invoice Validation Message | Payments

src/pages/credits/common/components/CreditDetails.tsx, src/pages/vendors/edit/components/Form.tsx
@beganovich @turbo124 The PR changes select fields for credits and vendors to newly designed select fields. Let me know your thoughts.
=> [Cleanup] Changing Select Field For Credits And Vendors

src/pages/settings/client-portal/components/Settings.tsx
@beganovich @turbo124 The PR includes fixes for changing values in the subdomain company field. The issue occurred in production because the `'/api/v1/check_subdomain'` endpoint was being called and the value would only change in the company object after this endpoint finished, instead of changing regardless of whether this endpoint had completed. Let me know your thoughts.
=> [Bugfix] Subdomain Changing Value

src/components/e-invoice/PaymentMeans.tsx, src/pages/settings/e-invoice/peppol/Preferences.tsx
This adds connection status & legal entity ID in preferences card.
=> E-invoicing: Add connection status  & legal entity id

src/pages/settings/e-invoice/EInvoice.tsx
@beganovich @turbo124 The PR includes a fix for the e-invoice type selector based on PR #2163 . Let me know your thoughts.
=> [Bugfix] E-Invoice Types Selector Issue Fix

src/pages/settings/e-invoice/peppol/Onboarding.tsx
This adds a message about company details being update once PEPPOL onboarding is completed. 
Companion PR: https://github.com/turbo124/invoiceninja/pull/108
=> E-invoicing: Add message about company details being updated

src/common/interfaces/company.interface.ts, src/pages/quotes/email/Email.tsx
@beganovich @turbo124 The PR adds a "First Reminder" option when emailing quotes. Screenshot:
=> [Cleanup] Adding "First Reminder" When Emailing Quote

src/common/interfaces/statics.ts, src/pages/settings/e-invoice/peppol/Preferences.tsx
This adjusts the purchase links to include `account_key` or `license_key` parameters.
=> E-invocing: Adjust purchase links

src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx, src/pages/settings/e-invoice/peppol/Onboarding.tsx
This includes the following improvements for invoicing:
- Licence checks are skipped when in development, so we don't run in rate limiting issue.
- Additional legal identifiers form is now cleared upon successful submit.
=> E-invoices: Few improvements

src/pages/settings/e-invoice/EInvoice.tsx, src/pages/settings/e-invoice/common/components/ValidationAlert.tsx, src/pages/settings/e-invoice/common/hooks/useCheckEInvoiceValidation.ts
This removes the following alert:
=> E-invoicing: Remove invalid company alert

src/components/Banner.tsx, src/components/banners/EInvoiceCredits.tsx, src/components/layouts/Default.tsx, src/pages/settings/e-invoice/peppol/Preferences.tsx
This adds two banners. For low credits and no credits.
PR for translations: https://github.com/turbo124/invoiceninja/pull/114
=> E-invoicing: Banners for low credits

src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
This improves validation on additional tax identifiers setup.
=> E-invoicing: Improve validation

src/pages/settings/e-invoice/EInvoice.tsx
This removes logic for disabling save button.
=> E-invoicing: Remove logic for disabling save button

src/common/helpers/request.ts
This handles 401 and 403 gracefully showing messages to contact support in case of this.
=> E-invoicing: Gracefully handling 400s 

src/common/interfaces/expense.ts, src/pages/clients/show/pages/Expenses.tsx, src/pages/expenses/common/hooks.tsx, src/pages/expenses/index/Expenses.tsx, src/pages/vendors/show/pages/Expenses.tsx
@beganovich @turbo124 The PR includes the implementation of the "Project" column to all Expense tables. Screenshot:
=> [Cleanup] Adding "Project" Column For Expense Tables

src/components/forms/InputCustomField.tsx, src/pages/settings/company/components/Details.tsx, src/pages/settings/custom-fields/components/Field.tsx
@beganovich @turbo124 The PR updates the styling of select fields for:
- All pages in Company Details
- Select fields used for creating custom fields
- All select field custom fields
Screenshot:
=> [Cleanup] Select Field Changing | Company Details Page

src/pages/settings/e-invoice/peppol/Onboarding.tsx
This refactors validation on final onboarding form, preventing runtime crashes.
=> E-invoicing: Onboard validation in safer way

src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
Backend implementation: https://github.com/invoiceninja/invoiceninja/pull/10275
=> E-invoicing: Remove additional identifiers

src/pages/clients/edit/components/AdditionalInfo.tsx, src/pages/recurring-invoices/common/components/InvoiceDetails.tsx
@beganovich @turbo124 The PR includes fix for option value types in the "Payment Terms" and "Quote Valid Until" dropdowns. Let me know your thoughts.
=> [Bugfix] Fixes For Option Value Types For "Payment Terms" And "Quote Valid Until"

src/pages/settings/localization/components/Settings.tsx, src/pages/settings/user/components/Notifications.tsx
@beganovich @turbo124 The PR updates selector field styling on the User Details and Localization settings pages to align the rest of the app. Let me know your thoughts.
=> [Cleanup] Changing Selector Fields To New Styling

src/pages/settings/tax-settings/TaxSettings.tsx
This includes couple changes to tax settings, including automatic setting of tax values when calculate taxes is on, in-app guide and hiding the invoice tax rates.
=> Improvements for tax settings

src/pages/invoices/common/hooks/useTabs.tsx
This shows einvoice tab on invoices only when sending einvoices is on.
=> E-invoice sending settings

src/common/hooks/useCommonActions.ts, src/components/CommonActionsPreferenceModal.tsx, src/pages/invoices/edit/components/CommonActions.tsx, src/pages/purchase-orders/PurchaseOrder.tsx, src/pages/purchase-orders/common/components/CloneOptionsModal.tsx, src/pages/purchase-orders/common/hooks.tsx
@beganovich @turbo124 The PR includes implementing "Common Actions Section" for Purchase Orders. Screenshot:
=> [Feature] Implementing "Common Actions Section" | Purchase Orders

src/common/helpers/invoices/invoice-sum.ts
Improves the UI calculations when PEPPOL is enabled, in particular for invoice surcharges.
=> Fixes for peppol calculations

src/pages/reports/index/Reports.tsx
@beganovich @turbo124 The PR includes fixes for sorting numeric columns in the Report preview table. Let me know your thoughts.
=> [Bugfix] Fixing Issue For Sorting Number In Reports Preview Table

src/App.tsx, src/common/hooks/useReactSettings.ts, src/common/hooks/useSystemFonts.ts, src/pages/settings/user/components/Preferences.tsx
This allows users to use system fonts.
Settings > User details > Preferences
=> Option to use system fonts

src/App.tsx, src/common/hooks/useReactSettings.ts, src/common/hooks/useSockets.ts, src/common/queries/sockets.ts, src/components/Notifications.tsx, src/components/PublicNotificationsModal.tsx, src/components/layouts/Default.tsx, src/pages/settings/user/components/Preferences.tsx
This is a frontend addition for: https://github.com/invoiceninja/invoiceninja/pull/10361
=> Notifications: Generic message

src/pages/tasks/common/hooks/useInvoiceTask.ts
@beganovich @turbo124 The PR fixes incorrect hour formatting in the description when invoicing tasks. Let me know your thoughts.
=> [Bugfix] Incorrect Formatting Of Hours In Description When Invoicing Task

src/components/tables/Table.tsx
@beganovich @turbo124 The PR includes fixes for table horizontal scrolling. Let me know your thoughts.
=> [Bugfix] Table Horizontal Scroll

src/common/helpers/request.ts
@beganovich @turbo124 The PR removes the logic for displaying toaster errors on 401 and 403 errors from the **/quota** endpoint.. Let me know your thoughts.
=> [Cleanup] Removing Toaster For /quota Endpoint Errors

src/common/hooks/useRefetch.tsx, src/pages/vendors/Vendor.tsx, src/pages/vendors/routes.tsx, src/pages/vendors/show/hooks/useTabs.tsx, src/pages/vendors/show/pages/Activities.tsx
@beganovich @turbo124 The PR includes the implementation of the 'Activity' tab for the Vendor show page. Screenshot:
=> [Feature] Implementing "Activity" Tab For Vendor Show Page

src/pages/settings/tax-settings/TaxSettings.tsx
This toggles inclusive taxes when toggling on calculate taxes.
=> Toggle inclusive taxes off when calculate is enabled

src/App.tsx, src/components/layouts/Default.tsx
This fixes the issue with popup showing on guest pages.
=> Fixes for socket preferences

src/components/PublicNotificationsModal.tsx
Fixes for "save_changes" translation string.
=> Update translation string

src/pages/settings/e-invoice/peppol/Onboarding.tsx
This fixes blank errors.
https://github.com/invoiceninja/invoiceninja/pull/10414
=> Fixes for einvoice errors handling

src/components/dropdown/Dropdown.tsx, src/pages/clients/show/components/ClientPrivateNotes.tsx, src/pages/clients/show/components/ClientPublicNotes.tsx, src/pages/clients/show/components/EmailHistory.tsx, src/pages/clients/show/components/Gateways.tsx, src/pages/recurring-invoices/common/components/ConfirmActionModal.tsx
@beganovich @turbo124 The PR implements the functionality to delete gateway tokens. Screenshot:
=> [Feature] Implementing Delete Functionality For Gateway Tokens

src/components/Tabs.tsx, src/pages/settings/company/CompanyDetails.tsx
Fixes https://github.com/invoiceninja/ui/issues/2153.
=> Fixes for mobile navigation

src/pages/settings/user/common/hooks/useUserDetailsTabs.tsx, src/pages/settings/user/components/Connect.tsx
@beganovich @turbo124 The PR includes making Gmail/Microsoft Connect/Disconnect options available only for paid plans. Let me know your thoughts.
=> [Bugfix] Making "Connect/Disconnect Gmail/Microsoft" Options Only For Paid Plans

src/components/TabGroup.tsx, src/components/cards/Slider.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx, src/pages/payments/common/components/PaymentSlider.tsx, src/pages/quotes/common/components/QuoteSlider.tsx, src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx, src/pages/tasks/common/components/TaskSlider.tsx, src/pages/tasks/kanban/components/ViewSlider.tsx
This includes couple fixes for slider component, including:
- Better spacing for name, with automatic truncate
- Nicer positioning for close button
- Nicer spacing for tabs
- Visually divide elements
=> Slider fixes & improvements

src/pages/settings/e-invoice/common/components/EUTaxDetails.tsx
This fixes handling additional identifiers for GB region (and improves validation handling).
=> E-invoicing: Fixes for GB identifiers

src/common/hooks/useRefetch.tsx, src/common/queries/designs.ts, src/pages/settings/invoice-design/InvoiceDesign.tsx
@beganovich @turbo124 The PR includes fixes to invalidate the cache when updating all records on the invoice design page. Let me know your thougts.
=> [Bugfix] Invalidating Cache When Updating All Records [Designs]

src/pages/invoices/common/hooks/useProductColumns.ts, src/pages/invoices/common/hooks/useTaskColumns.ts, src/pages/settings/invoice-design/pages/general-settings/components/ProductColumns.tsx, src/pages/settings/invoice-design/pages/general-settings/components/TaskColumns.tsx
@beganovich @turbo124 The PR includes changes to the 'Line Total' column - if the column is included in product/task variables, it will be displayed, otherwise, it will be hidden. Additionally, its position will match the position specified in the variables. Let me know your thoughts.
=> [Bugfix] "Line Total" Column On Line Items Table

src/common/queries/company-gateways.ts, src/pages/settings/gateways/create/Create.tsx, src/pages/settings/gateways/create/components/DuplicatingGatewayModal.tsx
@beganovich @turbo124 The PR includes the implementation of a notification modal that appears when a user attempts to create a gateway that is already active. Screenshot:
=> [Cleanup] Duplicating Gateways Notification Modal

src/components/DataTable.tsx, src/components/datatables/DateRangePicker.tsx
These fixes empty on click when clicking date range picker.
=> Fixes for date range column handling

src/pages/clients/show/components/Gateways.tsx
=> Update translation for default payment method

src/pages/reports/common/constants/columns.ts, src/pages/reports/index/Reports.tsx
@beganovich @turbo124 The PR includes fixes for number formatting when previewing reports. The solution now formats numbers using the user's preferred decimal separator and number precision from settings. I have included this logic for all necessary columns. Let me know your thoughts.
=> [Bugfix] Display Value Formatting Issue | Reports

src/common/hooks/useAtomWithPrevent.ts, src/pages/invoices/Invoice.tsx
@beganovich @turbo124 The PR includes changes to disable the leave page functionality when the invoice is locked. Let me know your thoughts.
=> [Bugfix] Disabling Prevent Leaving Page Functionality When Invoice Is Locked

src/pages/clients/common/components/BulkUpdatesAction.tsx
Add support for bulk updates for remaining cycles on recurring invoices.
Add support for defaults to be set using useEffect()
=> Bulk recurring updates add remaining cycles

src/common/interfaces/company-gateway.ts, src/pages/settings/gateways/edit/Edit.tsx, src/pages/settings/gateways/edit/components/WebhookConfiguration.tsx
@beganovich @turbo124 The PR includes implementing the "Settings" card instead of "Webhooks" for STRIPE_CONNECT, only for the HOSTED platform. Screenshot:
=> [Feature] Settings Card For Stripe Connect | Payment Gateways

src/common/hooks/useSockets.ts
=> Disable Pusher stats

src/pages/purchase-orders/edit/hooks/useHandleLineItemPropertyChange.ts
This is same patch we applied here https://github.com/invoiceninja/ui/pull/2351.
=> Improvements on PO performance

src/pages/settings/client-portal/components/Settings.tsx
Changes the display text for the client portal url from a query param to URI.
=> Change query param to URI

src/components/DataTable.tsx
@beganovich @turbo124 The PR includes fixes for the date range picker on the invoices table.
Closes #2359 
=> [Bugfix] Date Range Picker Filtering | Invoices

src/components/import/UploadCompanyImport.tsx, src/pages/settings/backup-restore/components/Restore.tsx
Provides chunked upload support, only for company backups.
Please review, requires latest v5-develop API changes.
=> Add ability for chunked file uploads

src/pages/settings/import-export/common/components/Import.tsx, src/pages/settings/import-export/common/components/UploadImport.tsx
Allows uploading quickbooks backup and restoring data into Invoice Ninja.
=> QB uploads

package.json, src/common/hooks/useSockets.ts, src/components/Notifications.tsx
This fixes multiple sockets connections and implements clean up concept.
=> Fixes for multiple sockets connection

src/common/hooks/useLogo.ts
@beganovich @turbo124 The PR includes fixing the logo URL issue. 
Closes #2374 
=> [Bugfix] Fixing Logo URL Issue

src/pages/tasks/common/components/TaskDetails.tsx, src/pages/tasks/common/helpers/calculate-time.ts, src/pages/tasks/kanban/components/TaskClock.tsx
@beganovich @turbo124 The PR includes a fix for duration time preview when it exceeds 24 hours. Screenshots:
Closes #1896 
=> [Bugfix] Fixing Duration Time Formatting If It Is Longer Than 24h

src/common/hooks/permissions/useHasPermission.ts, src/pages/settings/users/edit/components/Permissions.tsx
@beganovich @turbo124 The PR includes implementing the "Disable Emails" permission. Screenshot:
`Note`: We are missing the "disable_email" translation keyword in the files, so if you agree, please just add it there.
=> [Feature] Implementing "Disable Emails" Permission

src/pages/settings/gateways/create/components/Credentials.tsx
@beganovich @turbo124 The PR includes fixing the display message issue for the testing credentials modal on the edit payment gateway page.
Closes #2381 
=> [Bugfix] Fixing Display Message For Testing Credentials Modal

src/pages/purchase-orders/edit/Edit.tsx
This fixes issue with PO template dialog dismissing.
=> Fixes for purchase orders template dialog

src/components/GoogleOAuth.tsx
This dynamically loads and imports Google login, resulting in less cookies being set.
https://github.com/invoiceninja/ui/issues/2393
=> Dynamically load Google module

src/common/hooks/useDataTablePreferences.ts, src/components/DataTable.tsx, src/pages/clients/show/Client.tsx, src/pages/clients/show/hooks/useTabs.tsx
@beganovich @turbo124 The PR includes fixes for double-querying caused by setting values from preferences after calling the query with default parameter values. Let me know your thoughts.
=> [Bugfix] Double-Querying

src/pages/clients/common/components/LocationModal.tsx, src/pages/clients/common/components/Locations.tsx
@beganovich @turbo124 The PR includes quick fixes for updating locations on the UI when the array is empty (there are no locations anymore). Let me know your thoughts.
=> [Bugfix] Updating Locations On UI When Array Is Empty

src/components/DataTable.tsx, src/components/tables/Table.tsx
@beganovich @turbo124 The PR includes fixes for dashboard table height caused by adjusting logic to resolve the double-querying issue. The PR includes adjusting logic to wait until everything has been prepared for calculation. Let me know your thoughts.
=> [Bugfix] Table Height Calculations | Dashboard Tables

src/pages/clients/common/components/Settings.tsx, src/pages/clients/common/hooks/useClientColumns.tsx, src/pages/clients/show/components/ClientPrivateNotes.tsx, src/pages/clients/show/components/ClientPublicNotes.tsx, src/pages/credits/common/hooks.tsx, src/pages/expenses/common/hooks.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx, src/pages/invoices/common/hooks/useInvoiceColumns.tsx, src/pages/payments/common/hooks/usePaymentColumns.tsx, src/pages/products/common/hooks.tsx, src/pages/projects/common/hooks.tsx, src/pages/projects/show/components/ProjectPrivateNotes.tsx, src/pages/projects/show/components/ProjectPublicNotes.tsx, src/pages/quotes/common/components/QuoteSlider.tsx, src/pages/quotes/common/hooks.tsx, src/pages/recurring-expenses/common/hooks.tsx, src/pages/recurring-invoices/common/hooks.tsx, src/pages/tasks/common/hooks.tsx, src/pages/transactions/common/hooks/useTransactionColumns.tsx, src/pages/vendors/common/hooks.tsx
@beganovich @turbo124 The PR includes fixes for notes colors for both light and dark mode and a fix for the logic on client notes. Let me know your thoughts.
=> [Bugfix] Notes Colors And Logic Fixes

src/components/DropdownDateRangePicker.tsx, src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 The PR includes fixing an issue with range preferences on the dashboard.
Closes #2417 
=> [Bugfix] Range Preferences | Dashboard

src/pages/settings/account-management/component/plan/NewCreditCard.tsx
=> Disable automatic Stripe loading

src/pages/authentication/components/SignInProviders.tsx
@beganovich hot patching to develop, appears to be an issue with node v22 and msal init + https?
=> Adjustments for msal initialization

package-lock.json, package.json
Add msal/node to mitigate crypto() not found.
=> Add msal dependency

package-lock.json, package.json, src/pages/authentication/components/SignInProviders.tsx, src/pages/settings/user/components/Connect.tsx
This creates MS module on demand, instead of bundling boot in index of module, preventing crypto errors.
=> Async creation of MS module

src/components/CurrencySelector.tsx, src/pages/dashboard/components/Totals.tsx
@beganovich @turbo124 The PR includes adding an 'all' currency option as a preference for dashboard. Screenshot:
Closes #2435 
=> [Feature] 'All' Currency Option As Preference

src/pages/reports/common/hooks/useShowReportField.ts, src/pages/reports/common/useReports.ts, src/pages/reports/index/Reports.tsx
Add project reports into the UI.
@beganovich, this required some changes to how we handle different file types, previously we only supported CSV downloads, in this PR i've added the ability to inspect the payload to differentiate between PDF / CSV.
=> Reports - Projects

src/components/DataTableColumnsPicker.tsx, src/components/Modal.tsx, src/components/icons/CircleXMark.tsx, src/components/icons/GridDotsVertical.tsx, src/components/icons/XMark.tsx
@beganovich @turbo124 The PR includes redesigning the edit columns modal per Figma design. Screenshot:
`Note`: The buttons will be refactored by merging other PRs on the redesign branch.
=> [Cleanup] Edit Columns Modal Redesign

src/common/colors.ts, src/components/forms/Checkbox.tsx, src/components/forms/Combobox.tsx, src/components/forms/InputLabel.tsx, src/pages/clients/Client.tsx, src/pages/clients/index/Clients.tsx, src/pages/clients/show/Client.tsx, src/pages/credits/Credit.tsx, src/pages/credits/index/Credits.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/invoices/index/Invoices.tsx, src/pages/payments/Payment.tsx, src/pages/payments/index/Payments.tsx, src/pages/projects/Project.tsx, src/pages/projects/index/Projects.tsx, src/pages/projects/show/Show.tsx, src/pages/purchase-orders/PurchaseOrder.tsx, src/pages/purchase-orders/index/PurchaseOrders.tsx, src/pages/quotes/Quote.tsx, src/pages/quotes/index/Quotes.tsx, src/pages/settings/invoice-design/pages/custom-designs/components/ChangeTemplate.tsx, src/pages/tasks/Task.tsx, src/pages/tasks/index/Tasks.tsx
@beganovich @turbo124 The PR includes redesign of the "Load Template" modal according to the Figma design. Screenshot:
=> [Cleanup] Redesign of "Load Template" Modal

src/components/Modal.tsx, src/components/forms/Button.tsx, src/components/forms/InputField.tsx, src/components/icons/ArrowRight.tsx, src/pages/credits/common/hooks.tsx, src/pages/dashboard/hooks/useGenerateActivityElement.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx, src/pages/invoices/edit/components/Actions.tsx, src/pages/purchase-orders/common/hooks.tsx, src/pages/quotes/common/components/QuoteSlider.tsx, src/pages/quotes/common/hooks.tsx, src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx, src/pages/recurring-invoices/common/hooks.tsx, src/pages/vendors/common/hooks/useActions.tsx
@beganovich @turbo124 The PR includes redesigning the add comment modal per Figma design. Screenshot:
=> [Cleanup] Redesigned Comments Modal

src/common/constants/exports/recurring-invoice-map.ts
Adds the remaining_cycles prop to recurring invoice exports.
=> Add remaining cycles to recurring invoice export

src/components/datatables/DateRangePicker.tsx
@beganovich @turbo124 The PR includes fixes for the date range picker tippy position issue. Let me know your thoughts.
=> [Bugfix] Date Range Picker Tippy Position Issue

src/common/colors.ts, src/components/EmailRecord.tsx, src/components/TabGroup.tsx, src/components/cards/Element.tsx, src/components/cards/Slider.tsx, src/components/forms/Toggle.tsx, src/components/icons/ChevronUp.tsx, src/components/icons/CloudPlay.tsx, src/components/icons/CopyToClipboard.tsx, src/components/icons/EnvelopArrowRight.tsx, src/components/icons/History.tsx, src/components/icons/SquareActivityChart.tsx, src/pages/invoices/common/components/InvoiceSlider.tsx, src/pages/invoices/common/components/ViewLineItemExpense.tsx, src/pages/invoices/common/components/ViewLineItemTask.tsx, src/pages/invoices/edit/components/EmailHistory.tsx, src/pages/purchase-orders/edit/components/EmailHistory.tsx, src/pages/quotes/common/components/QuoteSlider.tsx, src/pages/quotes/edit/components/EmailHistory.tsx
@beganovich @turbo124 The PR includes refactoring all 4 tabs of invoice slider as per Figma's design. Screenshot:
=> [Cleanup] Invoice Slider Redesign

src/common/colors.ts, src/components/DocumentsTable.tsx, src/components/ResourceActions.tsx, src/components/Tabs.tsx, src/components/dropdown/Dropdown.tsx, src/components/forms/Combobox.tsx, src/components/forms/InputField.tsx, src/components/forms/NumberInputField.tsx, src/components/forms/SelectField.tsx, src/components/icons/CloudUpload.tsx, src/components/icons/Lock.tsx, src/components/icons/LockOpen.tsx, src/components/icons/MediaPause.tsx, src/components/icons/MediaPlay.tsx, src/components/tables/Td.tsx, src/components/tables/Th.tsx, src/pages/settings/company/documents/components/Upload.tsx, src/pages/tasks/common/components/TaskDetails.tsx, src/pages/tasks/common/components/TaskStatus.tsx, src/pages/tasks/common/components/TaskTable.tsx, src/pages/tasks/documents/Documents.tsx, src/pages/tasks/kanban/components/TaskClock.tsx
@beganovich @turbo124 The PR includes a redesign of Task entity pages according to Figma's design. Screenshots:
=> [Cleanup] Task Pages Redesign

src/components/forms/MarkdownEditor.tsx
Improves toolbar layout + functionality for font/font size selections.
=> Improve TinyMCE functionality

src/components/forms/Combobox.tsx, src/components/icons/Check.tsx, src/components/products/ProductSelector.tsx
@beganovich @turbo124 The PR includes a redesign of the combobox in general according to the Figma design. Screenshots:
=> [Cleanup] Combobox Redesign

src/pages/quotes/common/components/QuoteSlider.tsx
@beganovich @turbo124 The PR includes a redesign of the Quote slider according to the Figma design. Screenshot:
=> [Cleanup] Quote Slider Redesign

src/pages/payments/common/components/PaymentSlider.tsx
@beganovich @turbo124 The PR includes redesign of Payment slider according to Figma design. Screenshot:
=> [Cleanup] Payment Slider Redesign

src/pages/recurring-invoices/common/components/RecurringInvoiceSlider.tsx
@beganovich @turbo124 The PR includes a redesign of the Recurring Invoice slider according to the Figma design. Screenshot:
=> [Cleanup] Recurring Invoice Slider Redesign

src/pages/settings/company/documents/components/Table.tsx
@beganovich @turbo124 The PR includes a redesign for the company documents table. Screenshot:
=> [Cleanup] Company Documents Table Redesign

src/components/CompanySwitcher.tsx
@beganovich @turbo124 The PR includes removing an unnecessary part of the condition and making ONLY the owner able to add a new company. Let me know your thoughts.
=> [Bugfix] "Add Company" Action

src/common/hooks/useAuthenticated.ts
Fixes issue described in https://github.com/invoiceninja/ui/issues/2471#issuecomment-2776939336.
=> Fixes for resolving current index (login) 

src/components/Breadcrumbs.tsx, src/components/CustomSurchargeField.tsx, src/components/Tabs.tsx, src/components/cards/Card.tsx, src/components/layouts/Default.tsx, src/pages/invoices/common/components/InvoiceTotals.tsx, src/pages/invoices/common/hooks/useResolveTotalVariable.tsx
@beganovich @turbo124 The PR includes redesign of the Invoice Total section according to the Figma design. Screenshot:
=> [Cleanup] Invoice Total Section Redesign

src/components/layouts/Default.tsx, src/pages/settings/account-management/component/plan/Popup.tsx
This fixes following:
- Spacing for large devices (upgrade popup)
- Unlock pro CTA now navigates to the setting
=> Fixes for account management

src/pages/invoices/common/components/ClientSelector.tsx
@beganovich @turbo124 The PR includes fixes on existing develop for removing unnecessary `view_in_portal` action on create pages because the link is not available there. Let me know your thoughts.
=> [Bugfix] Removing "View In Portal" Action When Link Is Not Available

src/pages/invoices/edit/components/Activities.tsx, src/pages/invoices/edit/components/Documents.tsx, src/pages/invoices/edit/components/EmailHistory.tsx, src/pages/invoices/edit/components/History.tsx, src/pages/invoices/edit/components/Payments.tsx, src/pages/invoices/edit/components/Settings.tsx
@beganovich @turbo124 The PR includes a redesign of the remaining non-redesigned tabs for the invoice entity. Screenshot:
=> [Cleanup] Redesign Of The Rest Invoice Tabs

src/components/CopyToClipBoardIconOnly.tsx, src/components/Tabs.tsx, src/components/forms/Checkbox.tsx, src/pages/invoices/common/components/ClientActionButtons.tsx, src/pages/invoices/common/components/ClientSelector.tsx, src/pages/invoices/common/components/InvoiceDetails.tsx, src/pages/invoices/create/components/CreatePage.tsx, src/pages/invoices/edit/Edit.tsx
@beganovich @turbo124 The PR includes a redesign of the top of the invoice page according to the Figma design. Screenshot:
=> [Cleanup] Client Selector && Two Field Cards Redesign

src/common/helpers/invoices/invoice-sum.ts
Change in calculation for tax rounding.
=> Refactor for tax rounding

src/components/DropdownDateRangePicker.tsx, src/components/forms/SelectField.tsx, src/components/tables/Pagination.tsx, src/pages/clients/common/components/Documents.tsx, src/pages/clients/common/components/Locations.tsx, src/pages/clients/common/components/Settings.tsx, src/pages/clients/edit/Edit.tsx, src/pages/clients/edit/components/Address.tsx, src/pages/clients/edit/components/Contacts.tsx, src/pages/clients/edit/components/Details.tsx, src/pages/dashboard/components/Totals.tsx, src/pages/invoices/common/components/InvoiceDetails.tsx
@beganovich @turbo124 The PR includes a redesign of the edit client page along with all tabs there. Screenshot:
Let me knw your thoughts.
=> [Cleanup] Edit Client Page Redesign

src/pages/projects/show/Show.tsx
=> Fixes for current hours formatting

src/pages/products/common/components/CreateProduct.tsx, src/pages/products/documents/Documents.tsx, src/pages/products/edit/Edit.tsx, src/pages/products/edit/ProductFields.tsx
@beganovich @turbo124 The PR includes a redesign of Product pages according to the design. Screenshot:
=> [Cleanup] Product Pages Redesign

src/components/layouts/Default.tsx, src/pages/invoices/edit/Edit.tsx, src/pages/invoices/edit/components/Activities.tsx, src/pages/invoices/edit/components/EInvoice.tsx, src/pages/recurring-invoices/common/components/InvoiceDetails.tsx, src/pages/recurring-invoices/common/components/InvoiceFooter.tsx, src/pages/recurring-invoices/create/components/CreatePage.tsx, src/pages/recurring-invoices/edit/Edit.tsx, src/pages/recurring-invoices/edit/components/Activities.tsx, src/pages/recurring-invoices/edit/components/Documents.tsx, src/pages/recurring-invoices/edit/components/EInvoice.tsx, src/pages/recurring-invoices/edit/components/History.tsx, src/pages/recurring-invoices/edit/components/Schedule.tsx, src/pages/recurring-invoices/edit/components/Settings.tsx
@beganovich @turbo124 The PR includes a redesign of recurring invoice pages. Screenshot:
=> [Cleanup] Recurring Invoice Pages Redesign

src/pages/expenses/common/hooks.tsx
unsets the invoice_id on clone
=> Refactor for props on expense when cloning

src/pages/invoices/common/components/ClientActionButtons.tsx, src/pages/projects/create/Create.tsx, src/pages/projects/documents/Documents.tsx, src/pages/projects/edit/Edit.tsx, src/pages/projects/show/Show.tsx, src/pages/projects/show/components/ProjectPrivateNotes.tsx, src/pages/projects/show/components/ProjectPublicNotes.tsx
@beganovich @turbo124 The PR includes a redesign of Project pages according to the design. Screenshot:
=> [Cleanup] Project Pages Redesign

src/components/Tabs.tsx, src/pages/quotes/common/components/QuoteDetails.tsx, src/pages/quotes/common/components/QuoteFooter.tsx, src/pages/quotes/create/components/CreatePage.tsx, src/pages/quotes/edit/Edit.tsx, src/pages/quotes/edit/components/Activities.tsx, src/pages/quotes/edit/components/Documents.tsx, src/pages/quotes/edit/components/EmailHistory.tsx, src/pages/quotes/edit/components/History.tsx, src/pages/quotes/edit/components/Settings.tsx
@beganovich @turbo124 The PR includes a redesign of Quote pages according to the design. Screenshot:
=> [Cleanup] Quote Pages Redesign

src/components/CountrySelector.tsx, src/components/CurrencySelector.tsx, src/components/EUCountrySelector.tsx, src/components/LanguageSelector.tsx, src/components/UKRegionSelector.tsx, src/components/USStateSelector.tsx, src/components/e-invoice/EInvoiceGenerator.tsx, src/pages/clients/show/components/ClientCard.tsx, src/pages/payments/apply/Apply.tsx, src/pages/payments/create/Create.tsx, src/pages/payments/documents/Documents.tsx, src/pages/payments/edit/Edit.tsx, src/pages/payments/edit/PaymentFields.tsx, src/pages/payments/edit/PaymentOverview.tsx, src/pages/payments/edit/PaymentOverviewInvoice.tsx, src/pages/payments/edit/components/Activities.tsx, src/pages/payments/refund/Refund.tsx, src/pages/settings/integrations/api-webhooks/Create.tsx, src/pages/settings/integrations/api-webhooks/Edit.tsx, src/pages/settings/localization/components/Settings.tsx
@beganovich @turbo124 The PR includes a redesign of Payment pages according to the design. Screenshot:
=> [Cleanup] Payment Pages Redesign

src/components/DocumentsTabLabel.tsx, src/components/cards/Slider.tsx, src/pages/tasks/common/components/TaskStatus.tsx, src/pages/tasks/kanban/Kanban.tsx, src/pages/tasks/kanban/components/EditSlider.tsx, src/pages/tasks/kanban/components/TaskClock.tsx, src/pages/tasks/kanban/components/ViewSlider.tsx
@beganovich @turbo124 The PR includes a redesign of the Task Kanban page according to the Figma design. Screenshot:
=> [Cleanup] Task Kanban Redesign

src/pages/clients/create/ common/components/CreatePage.tsx, src/pages/clients/edit/components/Contacts.tsx, src/pages/clients/show/pages/Activities.tsx
@beganovich @turbo124 The PR includes adding smooth scroll after the add_contact button is clicked to avoid manual user scrolling if there are more than 2 contacts added. Video:
https://github.com/user-attachments/assets/5ea2f9a2-0c0b-47e3-85e9-af93dd4c5132
=> [Cleanup] Adding Client Contacts UX Improvement

src/pages/quotes/common/hooks.tsx
This PR is related to this discussion: https://github.com/invoiceninja/invoiceninja/discussions/10954#discussioncomment-13081588
=> feat: added a net amount column to the quotes overview

src/common/queries/purchase-orders.ts, src/pages/purchase-orders/create/components/CreatePage.tsx, src/pages/purchase-orders/edit/Edit.tsx, src/pages/purchase-orders/edit/components/Activities.tsx, src/pages/purchase-orders/edit/components/Details.tsx, src/pages/purchase-orders/edit/components/Documents.tsx, src/pages/purchase-orders/edit/components/EmailHistory.tsx, src/pages/purchase-orders/edit/components/Footer.tsx, src/pages/purchase-orders/edit/components/History.tsx, src/pages/purchase-orders/edit/components/Settings.tsx, src/pages/purchase-orders/edit/components/VendorSelector.tsx
@beganovich @turbo124 The PR includes redesign of Purchase Order pages according to design. Screenshot:
=> [Cleanup] Purchase Order Pages Redesign

src/pages/recurring-expenses/components/AdditionalInfo.tsx, src/pages/recurring-expenses/components/Details.tsx, src/pages/recurring-expenses/components/Notes.tsx, src/pages/recurring-expenses/components/Taxes.tsx, src/pages/recurring-expenses/documents/Documents.tsx
@beganovich @turbo124 The PR includes redesign of Recurring Expense pages according to Figma design. Screenshot:
=> [Cleanup] Recurring Expense Pages Redesign

src/pages/vendors/Vendor.tsx, src/pages/vendors/edit/components/Form.tsx, src/pages/vendors/show/pages/Activities.tsx, src/pages/vendors/show/pages/Documents.tsx
@beganovich @turbo124 The PR includes a redesign of all Vendor pages according to the Figma design. Screenshot:
=> [Cleanup] Vendor Pages Redesign

src/components/layouts/ActivitySelector.tsx, src/pages/reports/common/hooks/useShowReportField.ts, src/pages/reports/common/useReports.ts, src/pages/reports/index/Reports.tsx
Implements an additional filter for activity reports, to filter by activity types.
=> Add options for activity exports by Type

src/components/import/UploadImport.tsx, src/pages/settings/import-export/common/components/UploadImport.tsx
@beganovich @turbo124 The PR includes adding more CSV file MIME type versions for correct importing on Firefox. 
Closes #2548 
=> [Bugfix] Firefox CSV Import Issue

src/pages/settings/templates-and-reminders/TemplatesAndReminders.tsx
@beganovich @turbo124 The PR includes fixes for the duplicated "Partial Payment" template issue along with the subject and body prop key issue. Let me know your thoughts.
=> [Bugfix] Partial Payment Template Issue

src/components/cards/Element.tsx, src/components/forms/Radio.tsx, src/pages/settings/localization/Localization.tsx, src/pages/settings/localization/components/CustomLabels.tsx, src/pages/settings/localization/components/Settings.tsx, src/pages/settings/user/UserDetails.tsx, src/pages/settings/user/components/AccentColor.tsx, src/pages/settings/user/components/Connect.tsx, src/pages/settings/user/components/CustomFields.tsx, src/pages/settings/user/components/Details.tsx, src/pages/settings/user/components/Notifications.tsx, src/pages/settings/user/components/Password.tsx, src/pages/settings/user/components/Preferences.tsx, src/pages/settings/user/components/StatusColorTheme.tsx, src/pages/settings/user/components/TwoFactorAuthentication.tsx
@beganovich @turbo124 The PR includes a redesign of the User Details and Localization pages in Settings according to the Figma design. Screenshots:
=> [Cleanup] Redesign User Details && Localization

src/pages/settings/gateways/common/hooks/useActions.tsx
Adds the ability to clone a gateway.
=> Clone Gateway Action

src/App.tsx, src/common/colors.ts, src/common/hooks/useDataTablePreferences.ts, src/components/DataTable.tsx, src/components/forms/Checkbox.tsx, src/components/tables/Th.tsx, src/components/tables/Tr.tsx, src/pages/tasks/common/components/AddTasksOnInvoiceAction.tsx
@beganovich @turbo124 The PR includes performance improvements for re-rendering rows in the Data Table when it is displayed, along with small UX improvements when data is loading. Let me know your thoughts.
=> [Bugfix] Datatable Performance && Add Tasks  On Invoice Action Fix

src/pages/invoices/common/components/ClientSelector.tsx
@beganovich @turbo124 The PR includes a fix for the undefined invitation value issue when the last contact is unselected. Let me know your thoughts.
=> [Bugfix] Unselecting Last Contact Fix

src/components/DataTable.tsx
@beganovich @turbo124 The PR includes fixes for conflicts with keys in the data table. Let me know your thoughts.
=> [Bugfix] Keys Conflict On DataTable (Duplicating Columns On Quotes Table)

src/pages/products/common/components/ProductForm.tsx
@beganovich @turbo124 The PR includes changing the Cost field into a decimal number field. Let me know your thoughts.
=> [Bugfix] Cost Field | Decimal Field | Products

src/pages/invoices/common/hooks/useResolveInputField.tsx, src/pages/settings/tax-settings/TaxSettings.tsx, src/pages/settings/tax-settings/components/DefaultLineItemTaxes.tsx, src/pages/settings/tax-settings/components/Selector.tsx
@beganovich @turbo124 The PR includes implementation of default item tax rates functionality. Screenshot:
`Note`: I've used "default_item_tax_rate" on the Tax Settings page. If you agree with it, please just add it to the translation files.
=> [Feature] Default Item Tax Rates

src/components/DataTable.tsx
@beganovich @turbo124 The PR includes fixes for the pagination issue. Let me know your thoughts.
=> [Bugfix] Pagination Data Table

src/pages/invoices/common/components/InvoicePreview.tsx
Adds in an additional ref to allow auto loading of the livepreview on the first page load.
=> Add initial load live preview adjustment

src/pages/clients/statement/Statement.tsx
Provide email statement option for clients with Edit Client permissions.
=> Client statement permissions

src/pages/clients/edit/components/Details.tsx, src/pages/credits/edit/components/Settings.tsx, src/pages/expenses/create/components/Details.tsx, src/pages/invoices/edit/components/Settings.tsx, src/pages/projects/common/components/CreateProjectModal.tsx, src/pages/projects/create/Create.tsx, src/pages/projects/edit/Edit.tsx, src/pages/purchase-orders/edit/components/Settings.tsx, src/pages/quotes/edit/components/Settings.tsx, src/pages/recurring-expenses/components/Details.tsx, src/pages/recurring-invoices/edit/components/Settings.tsx, src/pages/settings/subscriptions/common/components/Overview.tsx, src/pages/tasks/common/components/TaskDetails.tsx, src/pages/tasks/common/hooks.tsx, src/pages/tasks/kanban/components/EditSlider.tsx, src/pages/vendors/edit/components/Form.tsx
=> Update user translation to Assigned user

src/pages/invoices/common/hooks/useCustomBulkActions.tsx, src/pages/invoices/edit/components/Actions.tsx, src/pages/settings/invoice-design/pages/custom-designs/pages/create/Create.tsx
Reinstates reversals as a menu option
Set a fixed height for the monaco editor when creating a new template
Change translation when saving a new design
=> 2025 08 29 reinstate reversals

src/pages/authentication/components/Header.tsx
This removes accent border on login pages.
=> Remove top border on login

src/components/CloudflareChallenge.tsx, src/pages/authentication/Register.tsx
This wraps signup page with Cloudflare challenge check.
=> Cloudflare signup challenge

src/pages/dashboard/components/SearchGroups.tsx
@beganovich @turbo124 The PR adds missing groups to the search modal in the navigation bar. Let me know your thoughts.
=> [Bugfix] Search Modal Missing Groups

src/common/hooks/useBulkUpdatesColumns.ts, src/common/queries/tasks.ts, src/components/projects/ProjectSelector.tsx, src/components/task-statuses/TaskStatusSelector.tsx, src/pages/clients/common/components/BulkUpdatesAction.tsx, src/pages/tasks/common/hooks.tsx
@beganovich @turbo124 The PR includes the implementation of 'bulk_update' action functionality for tasks. Let me know your thoughts.
=> [Feature] Bulk Update Action | Tasks

src/pages/clients/show/components/Gateways.tsx
@beganovich @turbo124 The PR includes a fix for the confirmation dialog when deleting gateways on client show page. Let me know your thoughts.
=> [Bugfix] Gateways Confirmation Modal

src/common/hooks/useDataTablePreferences.ts, src/common/hooks/useReactSettings.ts, src/components/DataTable.tsx, src/pages/clients/show/pages/Credits.tsx, src/pages/clients/show/pages/Expenses.tsx, src/pages/clients/show/pages/Invoices.tsx, src/pages/clients/show/pages/Payments.tsx, src/pages/clients/show/pages/Projects.tsx, src/pages/clients/show/pages/Quotes.tsx, src/pages/clients/show/pages/RecurringExpenses.tsx, src/pages/clients/show/pages/RecurringInvoices.tsx, src/pages/clients/show/pages/Tasks.tsx, src/pages/vendors/show/pages/Expenses.tsx, src/pages/vendors/show/pages/PurchaseOrders.tsx, src/pages/vendors/show/pages/RecurringExpenses.tsx
@beganovich @turbo124 The PR includes fixes for double querying on show pages when navigating from main list pages. Let me know your thoughts.
=> [Bugfix] Duble Querying When Navigating From Main List Tables

src/components/banners/VerifyPhone.tsx, src/resources/css/app.css
@beganovich @turbo124 The PR includes fixes for the color scheme on the verify phone input field. Screenshot:
=> [Bugfix] Verify Phone Input Field Color Scheme

src/common/queries/invoices.ts
@beganovich @turbo124 The PR includes fixes to avoid refetching invoices once auto-bill is triggered, as we already refetch through sockets. Let me know your thoughts.
=> [Bugfix] Auto-Bill Refetch Invoices

src/pages/expenses/common/hooks/useCalculateExpenseAmount.ts, src/pages/expenses/create/components/Details.tsx
@beganovich @turbo124 This PR includes fixes for net amount calculations on expenses and recurring expenses. Let me know your thoughts.
=> [Bugfix] Net Amount Calculation | Expenses | Recurring Expenses

src/pages/authentication/Login.tsx
Fixes https://github.com/invoiceninja/ui/issues/2717
=> Fix autocomplete on login page for Safari

src/pages/documents/builder/Builder.tsx, src/pages/documents/pages/blueprints/builder/BlueprintBuilder.tsx
This fixes the issue with WSS connection.
DOC-325
=> Fixes for websocket connection

src/pages/documents/builder/Builder.tsx, src/pages/documents/pages/blueprints/builder/BlueprintBuilder.tsx
This pins the left and right sides while scrolling.
https://github.com/user-attachments/assets/4ff08415-0f90-4a7f-bdc0-8276302ddee3
=> Pin files and toolbars on builder pages

src/components/SignatureFontSelector.tsx
@beganovich @turbo124 The PR includes fixes for the generate email signature functionality for DocuNinja users. Screenshots:
=> [Bugfix] Email Signature Generating Fixes
